### ISSUE TITLE
Choose a name for Book 3

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#1]
Is this okay as a working title? I don't think we can use just "Repeats" because it isn't in line with the other titles we have used. Suggestion below:
Benesh for Ballet: Book 3
Centre Practice and Repeated Sequences
in Word Definitions, DanceForms Animations, and Benesh Movement Notation 
@rsryman

**Comment by rsryman** [comment]
Very good. We can use this as a working title, and it may very well be the final title. I'll give it some thought over the next few days. As a start I have attached a very sketchy draft outline:
[iBook3 Repeats Outline.docx](https://github.com/rryman/BeneshForBalletBook3/files/39544/iBook3.Repeats.Outline.docx)

**Comment by agryman** [comment]
@rsryman welcome to GitHub. I see you figured out how to comment, attach a file, and close the Issue.

The reason I suggested that you and Robyn use GitHub is to keep your work organized so you can easily find past decisions and discussions. This works best if you create a separate Issue for each task, problem, review, etc. In this case, you closed the issue, but attached a new document to it and started a new work activity. So really you are overloading this Issue. To get the most benefit from the Issue tracker, should create a new Issue for the task of developing the Outline and attach your document there. 

The GitHub user interface takes a little getting used to. If you'd like some demos of how to use Issues, please schedule a Google Hangout session with me and @rryman .

**Comment by rsryman** [comment]
I unintentionally closed the issue. I now see the choice of buttons below. Yes, let's schedule a Hangout session. Will try to use your calendar.

**Comment by rryman** [comment]
Here is the Book 3 cover. It is easy to change the title once we have completed the content of the book and we decide what is most suitable. I used the RAD Set Exercises and Variations spelling for Centre Practice. Do you like the colour of the cover? If not, we can do a Google Hangout and I will share my screen and we can change the colour together. Green reminds me of Spring, and Spring reminds me of new growth, and new growth reminds me of repeating things, and the book is about repeats, so therefore I chose green for the cover. There are lots of other colours and lots of variations on the colour green. I really don't mind what colour we make it, as long as it isn't red or blue, and it doesn't clash on the "book shelf" with the other two covers. See attached JPG:
![book3cover](https://cloud.githubusercontent.com/assets/15850667/11300454/2ee4cd64-8f5d-11e5-86c7-36ba2a01cd8d.jpg)

**Comment by rryman** [comment]
Rhonda, you don't seem to have seen this assigned task so I am adding another comment so that you will be alerted to it. Please look at the book cover and let me know if you like the colour, or if you want to do a Google Hangout to update the colour.
@rsryman
