### ISSUE TITLE
Legato Lines and Repeats

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#10]
I emailed Liz and she said that neither she nor Diana knew whether you had to use the legato line at the end of the repeat, so suggested putting it in. She said she would notate the example with part-bar repeats so that it would not be an issue. I plan to try notating Ben's echappe and tour with part-bar repeats, so we have both options.

I have assigned this to you just so I know you have read it. You don't need to do anything with it. Just close it once you have read it, unless you have a comment.

**Comment by rsryman** [comment]
Very interesting!
