### ISSUE TITLE
Chapter 5 Animations narrow format

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#100]
**DONE**
Please confirm what I need to do next:

I currently have 9 pdfs from MacBenesh for pages: 46, 47 (2 versions), 48 (2 versions), 49, 50, plus, the Russian version of relevés to be called Sissonne Simple and added after the current p. 49, yes? (Can you locate the necessary glossary info for this?)

I can make all narrower to fit on 2 staves except for pages 47 & 48 which will be one as-narrow-as-possible stave per version, yes?

**Comment by rryman** [comment]
Yes, that all sounds fine.
I already have glossary entries for Sissonne Simple Derriere and Devant as separate entries. I am assuming you want me to put in links to both? I do not appear to have sound clips for either of these.

**Comment by rryman** [comment]
Sissonne Simple, Russian - There are differences in the notation versus the animation.
Do you want to change the animation or the notation?
Here are the differences I spotted:
Animation: Bar 1 - arm doesn't arrive in 2nd until feet close in 5th
Notation: Bar 1 - arm arrives in 2nd on the relevé
--
Animation: Bar 2 Count 1 - left foot closes 5th derrière
Notation: Bar 2  Count 1 - left foot closes 5th devant
--
Animation: Bar 2 Count 3- left foot closes 5th derrière
Notation: Bar 2 Count 3 - left foot closes 5th devant
--
Animation: Bar 2 Timing - one, an, two, three, four?
Notation: Bar 2 Timing - one, an, two, an, three (hold four)
--
Notation: Bar 3 Count 1 - why a static direction sign and not quarter turn sign here (like the rest)?

**Comment by rryman** [comment]
Releve (page 49)
Bar 1 Count 3: wrists up (so shouldn't they be in the notation)?

**Comment by rryman** [comment]
Grand Battement page 47 - Do you want Rose to do this (if so should I take out the Glossary link to raccourci and just have it as a related term in the Glossary). See blue notes on page 47.

**Comment by rryman** [comment]
I didn't get through pasting the notation and checking the animations for Chapter 5. Unfortunately, I have to have a shower and go grocery shopping. I have yoga tomorrow morning.

**Comment by rryman** [comment]
Developpe page 48
Differences:
Notation has no head in beginning and end - animation does.
Notation has RAD 4th arms - animation has Italian Croise devant arms.
Change the notation or change the animation?

**Comment by rryman** [comment]
Pirouette en Dedans page 51
I wouldn't use the qualification signs to first in Bar 4.
The notes on this page said that we were going to add to the notation:
"In Silence" - Restretch legs as arms open through 2nd and lower to bras bas.

**Comment by rsryman** [comment]
3 sound clips uploaded to Dropbox For Robyn > iBook3 > SissonneSimple

**Comment by rsryman** [comment]
BMN pdf uploaded to Dropbox For Robyn > iBook3 > MacBeneshCh3&5:
Ch5SissonneSimple

**Comment by rsryman** [comment]
Re your question: Releve (page 49) Bar 1 Count 3: wrists up (so shouldn't they be in the notation)? Jenna is Generic, so we should use a simple demi-bras position in the animation and no wrist directions in the BMN. I will make sure the defined position is used in the animation, OK?

**Comment by rsryman** [comment]
Uploaded to Dropbox For Robyn > iBook3 > Ch5:
Ch5RelevéDevantDerrièreFR.mov
Ch5RelevéDevantDerrièreBK.mov

Note Jenna uses demi-bras (BMN no wrist directions needed)

**Comment by rsryman** [comment]
Uploaded to Dropbox For Robyn > iBook3 > Ch5:
Ch5GlisséDégagéFR.mov
Ch5GlisséDégagéBK.mov

**Comment by rsryman** [comment]
Re your note: Grand Battement page 47 - Do you want Rose to do this (if so should I take out the Glossary link to raccourci and just have it as a related term in the Glossary). See blue notes on page 47.

In Ch5 we have only used Anna and Maria once each, so let's just have 1 Rose and leave Jenna here? Then you can leave Enveloppé and Raccourci on page 47 (good since no room on p 48?). I remember discussing this but can't remember why we wanted to use Rose here.

**Comment by rsryman** [comment]
BMN pdf uploaded to Dropbox For Robyn > iBook3 > MacBeneshCh3&5:
Ch5Relevé(narrow)

**Comment by rsryman** [comment]
BMN pdf uploaded to Dropbox For Robyn > iBook3 > MacBeneshCh3&5:
Ch5DéveloppéA(narrow)
Ch5DéveloppéB(narrow)

**Comment by rryman** [comment]
I think it may have had to do with the retire on the developpe and
enveloppe.
Would Russian and Italian pass the foot through retire devant and retire
derrierre, or would they pass through the side of the leg instead?

**Comment by rryman** [comment]
Detourne sound clip needed for page 49.

**Comment by rsryman** [comment]
Yes, RAD passes through retiré devant/derrière while Cecc and Russian pass
side of knee.

Best to use Rose so we can use English terminology in the i-box text and
only define Enveloppé on this page, with cross-reference (and Related Term)
to Raccourci in the Glossary.

I'll get to this tomorrow.

**Comment by rsryman** [comment]
Sound clip for Dérourné uploaded to For Robyn > iBook 3 folder:

Détourné.m4a

**Comment by rsryman** [comment]
Grand Battement page 47 with Rose uploaded to For Robyn > iBook3 Repeats > Ch5:
CH5GrandBattementRoseFR.mov
CH5GrandBattementRoseBK.mov

**Comment by rsryman** [comment]
Re your comment: 
Pirouette en Dedans page 51
I wouldn't use the qualification signs to first in Bar 4.
The notes on this page said that we were going to add to the notation:
"In Silence" - Restretch legs as arms open through 2nd and lower to bras bas.

Does the RAD syllabus now omit the forward qualification to 1st? I thought this applied to a higher placement (hands chest ht as in Cecc 5th en avant).
I will redo the BMN in narrower format and add the "In silence" ending frame but await your confirmation re qualification before uploading new clip.

**Comment by rsryman** [comment]
Uploaded to For Robyn > iBook3 Repeats > Ch5

Ch5BattementGlissé(narrow)
Ch5BattementGlissé(narrower)
Ch5PirouetteEnDedans(narrow)

**Comment by rryman** [comment]
Rhonda, please look at the notation and animation on page 48. The heads in the notation do not match the heads in the animation. Do you want to change the animation or the notation?

**Comment by rryman** [comment]
Page 47 - Grand Battement A - I took the turned head out of Bar 2 Frame 2.

**Comment by rsryman** [comment]
Re p. 47 Grand Battement Bar 2 ct 1: delete head (better to retain pure
turn).

Re p. 48 Développé, I will change the animation to start with head erect
but please add slight incline to the BMN on ct 1?

**Comment by rryman** [comment]
I would like to discuss your response, so please call me when it is convenient.

**Comment by rsryman** [comment]
Re p 47 Grand Battement and p. 48 Développé, I uploaded revised pdf files to 
For Robyn > iBook3 Repeats > Ch5
