### ISSUE TITLE
Proofreading Chapter 5

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#101]
**Rhonda will proofread Chapter 5 later.**
Rhonda, please download the updated version of the Book from DropBox and proofread all aspects of Chapter 5.
Please use this thread to communicate any errors (notation, animations, text, glossary, links, etc.) or anything we have missed.
I will proofread this Chapter as well, as I haven't done so yet.

*As we discussed Aug 31, Rhonda will go through all Robyn's comments in this thread so you can update the iBook, before she begins to proofread Ch5 and submit her own comments. RRK*

**Comment by rryman** [comment]
Page 44 "i" box:
Bars 9-16. 	Repeat Bars 1-8 in 2nd, closing the degagé 5th front (Bar 16).
**with degagé side closing 5th front** ???
 Bars 17-24. 	Repeat Bars 1-8 in 5th, with degagé front lowering into 4th (Bar 24). 
Bars 25-32. 	Repeat Bars 1-8 in 4th, with degagé front closing 5th (Bar 32).

**Comment by rryman** [comment]
Battement en Croix Page 45 Glossary Definitions:
Do you think it is confusing that I have only used glisse, degage, and jete?
I have added "Battement" before glisse, degage, and jete.

**Comment by rryman** [comment]
Battement en Croix Page 45 Animation versus notation:
Intro: The incline on the animation is to the right and not the left.
Do you want me to change the notation and the "i" text?
Or is the animation incorrect?

**Comment by rryman** [comment]
Grand Battement, English Glossary definition:
Enveloppe - I took out the note - Note: we may need to cross-reference the terms enveloppé and raccourci on p. 18? Perhaps use “enveloppé/raccourci”?

I added the links to the bottom of page 18.
Do we still need an Appendix entry for enveloppe/raccourci?

**Comment by rryman** [comment]
Developpe, Italian Page 48

Crap!!! the movement line for the right arm is now incorrect. I will redo the movement line on both examples Bar 1 count 4 and in the top example Bar 2 count 2 to match the stave below.

**Comment by rryman** [comment]
Pirouette en Dedans with Fouette, English - page 51
Discrepancy of sizes - front and back. Can this be fudged more to make the differences in sizes a little less?  Is the animation for the front view started as far forward as possible? I assume because the arms finish in 5th Rose can't be moved any further forward? Perhaps the back view of Rose could start further back? **However, if you think readers should just get used to it, then let's leave it as is.**

**Comment by rryman** [comment]
Pirouette en Dedans with Fouette, English - page 51
I will fix "i" box text to match the change in arm in the notation on count 2-an.

**Comment by rsryman** [comment]
Hi sis,

I've replied to all your Ch5 Proofreading comments on GitHub, and will now
do the relevant updates to the BMN and animations.

I'll be home this afternoon if you need any clarifications.

**Comment by rsryman** [comment]
I will close this issue for now and reopen it when I begin to proofread the entire book.
