### ISSUE TITLE
BeneshBasics8 - revisited

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#102]
As we have made changed to the content of Benesh Basics 8 we need to update the opening page blurb. Here's what I have changed it to ... please wordsmith ...

Basic technique exercises are repeated during barre and centre work until they are mastered. Repetitions can be the same, other side, alternating sides, or reverse. The material to be repeated is enclosed in paired *repeat* signs to help indicate the structure of the sequence. Solid *repeat* signs are used when the start and end of the repeated phrase coincide with bar lines. Dotted/dashed *repeat* signs are used when repeated phrases do not coincide with bar lines.

**Comment by rsryman** [comment]
This reads well, although the start is a bit abrupt. I'll close for now but may rethink this if it jumps out at me when I'm proofreading.

**Comment by rsryman** [comment]
As per our phone conversation, I have updated and uploaded a template for BB8 Part-bar Repeats (as an intro & complement to the new page in BB9): TEMPLATE_Ch4BB8p41.docx
