### ISSUE TITLE
Ch7AllegroEnchainements

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#103]
I have found a way to link words to the glossary, so we can do things a bit differently for Chapter 7 if we want. However, this needs to be thought through carefully. If we add links to the Glossary Terms do we then need to state the alternative names in the "i" box information.

In the latest version of the Book I uploaded to DropBox you will see Glossary links on page 61 and in the titles on Page 62. We can consider a different colour for these links if we decide to go this route.

**However, we may want to consider keeping this chapter simple and just let the reader go to the Glossary if they want to know what other schools call these steps and to read the definitions. What's your thoughts on this?**

**Comment by rsryman** [comment]
I like that it makes less clutter at the top of each page, but the bold blue font is a bit overpowering. Is it possible to link to the Glossary from within the i-box? Perhaps restate the title of the enchaînement at the top of the i-box, or perhaps link to the blue-underlined term within the i-box word description?

**Comment by rryman** [comment]
Sorry, I tried that and it didn't seem to let me link to the Glossary from
the "i" box ;(
I'll give it another try just to confirm.

**Comment by rryman** [comment]
Nope, I confirmed it won't link to the Glossary from the "i" box text. Unfortunately, the way to link text to the Glossary is different than linking to a website, page within the book, etc.

**Comment by rryman** [comment]
I don't like the blue underlined text either. Do you want to just leave it all plain and let the reader find their own way to the Glossary?

**Comment by rryman** [comment]
Rhonda and I discussed this one the phone. We are not linking Glossary terms in this chapter.

**Comment by rsryman** [comment]
Suggestion for CH 7 simplest ex:

Simple enchaînement to start CH 7: SISSONNE ORDINAIRE AND ÉCHAPPÉ SAUTÉ (using Rose)

4/4 Allegro (I need to find music) Start 5th R fr croisé, arms 1st

Bar 1, count 1: sissonne ordinaire devant, arms 3rd, R en avant; 2: petit assemblé devant; 3: sissonne ordinaire derrière, arms 3rd, L en avant; 4: petit assemblé derrière
Bar 2, count 1: échappé sauté to 2nd, arms 2nd; 2: close 5th changé, arms bras bas; 3-4: entrechat stretch plié

Repeat all: legs in reverse, same side; arms same, but FIN over the legs stretch (to eliminate final plié)

**Comment by rryman** [comment]
If you wish to shake it up a bit ... start with left foot in front ... lots of the enchainements in this chapter start right foot front facing croise ... however, up to you ... as I said during our phone call, we are not alternating starting feet in this chapter so it really doesn't matter either way.

**Comment by rsryman** [comment]
OK, I'm just finishing the front view and will send it tomorrow with notation before I start on the back view.

**Comment by rryman** [comment]
Page 68, 69, and 70 ... Assemble Soutenus ...
I just noticed that the movement lines for the arms lowering to 5th en bas from high demi-second start a bit low. Is this worth the hassle of fixing in all 3 examples, or is it close enough not to matter?

**Comment by rsryman** [comment]
Please see sample animation uploaded to For Robyn > iBook3 Repeats: 
SissOrdinÉchappéSautéFR.mov

To illustrate word description above - CH 7: SISSONNE ORDINAIRE AND ÉCHAPPÉ SAUTÉ (using Rose), OK? I see that the Gr Changement begins with R ft fr so before I do the back view and BMN please confirm whether you'd like this to start R ft fr or L ft fr. It's easy to change now.

**Comment by rryman** [comment]
Re SissOrdinÉchappéSautéFR.mov
The animation looks to start with the left foot front. I like it, as most of the other enchainements in this chapter start with the right foot, so it is a bit of a change. I'll just have to reword the description above when I am creating the "i" box text. Will you be creating the notation in MacBenesh?

**Comment by rryman** [comment]
Same music track as jete battu and fouette battu on page 73?

**Comment by rsryman** [comment]
Ys, I thought it was far enough separated and it works well.

**Comment by rryman** [comment]
Okay I have added the track to the bottom of the "i" box.

**Comment by rryman** [comment]
Ch7SissonneOrdinaireÉchappé - notation
For your original Benesh file (I will change it via Adobe Illustrator on my version):
1) Incorrect 5th on the close from the echappe and therefore incorrect for the rest of the sequence.
2) I think we should eliminate the 5th position in the air on the echappe out because Rose doesn't seem to join her feet in 5th like she does for the sissonne ordinaires.
3) Do we need to restate the direction sign to show that she stays facing that direction on the repeat (or would a direction sign only be used if it was different)?

**Comment by rryman** [comment]
I am still missing the back and front view of the animation for Assemble Soutenu: dessus and dessous.
Have you put it anywhere in the DropBox?
