### ISSUE TITLE
Review Centre Work Without Repeats

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#104]
Robyn will start creating Review Questions as per her conversation with Rhonda this morning.

**Comment by rsryman** [comment]
This is a summary of approaches based on iBook 2:
*Question 3.1* Number 1: (1-~5 windows) Drag the button image or terminology to the appropriate notation.
*Question 3.2* Number 1: (~2 windows) Match the animation (up to 4 examples) to the appropriate notation.
Number 2: Drag the button image/terminology to the appropriate notation.
*Question 3.3* Number 1: (1-~5 windows) Select A-C, answering a specific question about the notated enchaînement taken directly from the chapter, e.g, musical or dancers' counts, amount and direction of turn.

We discussed very basic questions briefly by phone but I thought you would do this and didn't take notes. Based on what I was thinking, I have uploaded a .doc template for Question 3.1:
*Review3.1.docx*

Now I'll start on the MacBenesh clips. You may have wanted a more basic approach so please feel free to suggest another direction.

**Comment by rsryman** [comment]
I uploaded the composite pdf so you can check all BMN examples before I clip each one. See:
Ch3 Review

To be decided: 
1. Whether to show R or L ft fr
2. Whether or not to add arms to simple clips like plié. If I don't use arms for rise/relevé page, it makes sense to make it page 1, followed by simple pliés with arms on page 2.
3. Best stave width for clarity, and whether to clip a whole stave at a time or by each unit.
4. In développé & enveloppé/raccourcie, show both opening & closing or just one as relevant?

**Comment by rsryman** [comment]
See updated file, uploaded to For Robyn > iBook3 Repeats: Review3.1-3.docx

I added Question 3.2 (to be discussed before I create the BMN and animations) and also suggestions for Question 3.3.

**Comment by rryman** [comment]
I have uploaded the latest Book to DropBox.
Review 3.1 Page 30 is complete.
Please check it and let me know if there are any errors, or if anything needs to be changed.

**Comment by rsryman** [comment]
I just tried to download the ibook but it's not there.

**Comment by rryman** [comment]
I have implemented your edits noted above (and added some of my own).
I have uploaded the updated book.
I have done all I can on Review 3.
Please check it and see if you agree with what I have done.
Page 30: I have added two questions here that you had indicated in your Word Doc as 3.3 but they are the same format as the questions in 3.1 so I included them here. Please check all the edits in this section.
Page 31: Review 3.2 needs 3 animations.
Page 32 Review 3.3 needs 2 animations (if you think this is worth keeping in the book)
I decided to include it as the animations illustrate the theory of closing signs (rises) versus static signs (releves) which students seem to find difficult to understand.
Reviews 3.2 and 3.3 - I made the animations as small as possible without cutting off the feet (the grand battement back is a bit cut off, but you can still see the action). I made the notation as large as possible. Do you find it clear enough to read?
Let me know if you spot any errors, or want anything done differently.

**Comment by rsryman** [comment]
See 3 animations uploaded For Robyn > iBook3 Repeats

BB7Reviewp31bBK
BB7Reviewp31cBK
BB7Reviewp31dBK

**Comment by rsryman** [comment]
See 2 animations uploaded For Robyn > iBook3 Repeats

BB7Reviewp32cBK.mov
BB7Reviewp32dBK.mov

**Comment by rryman** [comment]
I have added these .mov files to the review.
If you feel Review 5 is now completed, please close this issue.
