### ISSUE TITLE
Table of Content Image

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#106]
Rhonda if you are looking for something to do, I need an image for the TOC (the notation that goes on each of the green TOC pages). Presently the one from Book 2 is there. This image needs to be one stave and needs to represent the content of Book 3. I feel it needs to be something with repeats.

Here's a list of the ones I think may work. Do you have a preference?
Page 39 repeated jump sequence with alternating repeats - I think this is my second pick.
Page 41 repeats with FIN.
Page 42 repeats with Exclusion Bracket.
Page 49 Grand Battement with movement lines (bottom example).
Page 50 Developpe with retires (top example) - I think this is my pick.
Page 63 Other Repeats (top example).

Most of the other options are either too plain, or have more than one stave. I don't think we should use one stave from a longer example do you?

**Comment by rsryman** [comment]
I like page 39 best since it has jumps that seem to build from Book2, so readers might find it more reassuring/less threatening?
Page 50 is Cecchetti based, so perhaps not "generic" enough? Also, it is relatively complex.

**Comment by rryman** [comment]
Okay. I went with the image on page 39. I fiddle with the size of the notation image and the text box. I tried to make the text box big enough so the user wouldn't have to scroll to see all the content, but some of our chapters just have too many sections to make this work consistently. I ultimately decided to leave it as it is. Please look at the TOC (the green background pages) and see what you think.

**Comment by rsryman** [comment]
The green background notation image is very clear. I think you are referring to the "text box" as the white lettering that starts with the TOC page for Chapter 1, yes? I agree that it's better to keep the font size consistent, as you have done, even if the reader has to scroll.
