### ISSUE TITLE
Review 7 - Allegro Enchaînements

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#107]
**This has become (page 84) Review 7.2 with two questions just using Ch7.1bBK.mov; Ch7.1cBK.mov; Ch7.1dBK.mov**
I have uploaded 4 animations to test part bar repeats and other side-reverse repeats:

Ch7.1aBK.mov (label: Same Side)
Ch7.1bBK.mov (label: Other Side)
Ch7.1cBK.mov (label: F/B Reverse)
Ch7.1dBK.mov (label: Other Side + F/B Reverse) 

Drag the label to the corresponding notation. (F/B Reverse = Front/Back Reversal)

**Comment by rryman** [comment]
We mainly call then "Reverse Repeats". Do you really want me to start calling them Front/Back Reversal?

**Comment by rsryman** [comment]
No, be consistent where possible.

**Comment by rryman** [comment]
**Rhonda**
See update Gr Battement exercise, uploaded: Review5GrandBattement
We can use any of these, depending on real estate:
a) Repeat other side
b) Repeat in reverse (legs only)
c) Repeat other side with second ending
Let me know which you want and I'll do corresponding animations.
If we use c) there will be other questions to ask.

**Robyn""
For b) why wouldn't we use repeat reverse legs and same arms, i.e., the upper and lower markings?
Should we restate the direction sign in the second stave in the "empty" repeat bars, as you asked me to do in the Sissonne Ordinaire on Page 68?
I think if we do this then I am okay with using the top two examples.
This would work out well, as it will be an example using upper and lower markings and the glissé animations you gave me will be an example of reverse on the other side.
Thoughts?

**Rhonda**
Duh, I forgot this was in this chapter. Yes for b) use repeat reverse legs and same arms, i.e., the upper and lower markings. OK to restate direction sign. OK, let's use a) and b).

**Comment by rryman** [comment]
Is this correct? If so, please create the animations.
![rev7 3](https://cloud.githubusercontent.com/assets/15850667/18650335/91c453f8-7e92-11e6-9821-2db250589b81.jpg)

**Comment by rryman** [comment]
Latest book uploaded to DropBox.
Review 7.1 (page 83) Only Question 1 is implemented. Please look at it and see if you agree with this type of question for Review 7. If so, I will continue along this track with some of the other allegro enchainements.
Review 7.2 (page 84) complete. Please check.
Review 7.3 (page 85) started. Please check notation and if in agreement, please create back views of the animations.
Review 7.4 (page 86). What do you think about using entrechat quatre and royal with the 2nd animation end the repeat with the stretch bend, i.e., the same notation but without the exclusion bracket?
Review 7.5 (page 87). What do you think about using sissonne ordinaire and echappe saute with the 2nd animation end the repeat with the bend, i.e., the same notation but without the FIN?
If you don't agree with these suggestions, please offer alternatives.

**Comment by rsryman** [comment]
p. 82: there is quite a bit of room at the bottom of this page and also p. 29 & p. 55, so consider making the Note in a larger font?

p. 83 Q 1: Yes, good. For Q 2 you could use the same notation (top 2 staves) and ask which match the ending Bars 15-16.
p, 84 Good.
p. 85 In the reverse repeat/same arms, restate head other side in Bar 8. 
Animations uploaded: 
Review7GrandBattementBKa.mov 
Review7GrandBattementBKb.mov

Review 7.4 (page 86). Good idea to end with relevé, perhaps with arms to demi-bras, head incline and turned R? In Question 2, we could drag a label to the new end positions to make sure they notice it.
Review 7.5 (page 87). If we finish with relevé in 7.4 lets end in plié here. Just take out the FIN. These two nicely cover FIN and Exclusion Bracket.

Review 7.6 (page 88). Good idea, with FIN over Bar 7/Dancers' Count 7 and delete stave notation from empty bars, yes? In Question 2, we could drag a label to the tour ending in 5th and the tour ending in lunge.

GENERAL QUESTION: Should we think about when we use the red foot for clarity?

**Comment by rryman** [comment]
To be consistent, you should use a red foot for all the jump animations in Review 7 because we used a red foot in all of them in Chapter 7.

**Comment by rsryman** [comment]
Review 7 is shaping up well.

Here are 4 more options for 7.1 (including the one we discussed, see Q3 below): 
Q2: Which example below is a rond de jambe sauté en dehors? (B) USE SAME EX. 1-3 AS Q1
Q3: Which example below shows the ending actions in Bars 15-16. USE NEW BMN AS DISCUSSED: one with L ft cdp dev, one with r ft cdp dev, one with L ft cdp dev, all ending 5th L ft fr (as notated)
Q4: Which option below describes the number of jeté actions (1 to other) in each 8-bar phrase: A. 2; B. 3; C. 6 (C)
Q5: Which option below describes the number of temps levé actions (1 to same) in each 8-bar phrase: A. 2; B. 3; C. 6 (A)

I'll now work on animations for pp. 86-88.

**Comment by rsryman** [comment]
Since the music for the Entrechat Quatre (p. 72) actually ends on ct 15, I decided to end this one in plié and the Sissonne Ordinaire (p. 70) one in relevé, just opposite of what we decided by phone.

Re Review 7, see 3 new animations uploaded:
Review7SissOrdÉchSautéBK.mov
Review7EntrQuatRoyalBK.mov
Review7TourEnchaînementBK.mov

I also uploaded a revised animation for p. 79 )also the top animation for p. 88), since I found something strange on the landing of the first tour:
TourEnchaînementBK.mov

**Comment by rryman** [comment]
I am a bit confused about the TourEnchainement movies.
You want me to use Review7TourEnchaînementBK.mov and TourEnchaînementBK.mov in Review 7.6.  
You want me to replace the back animations on page 79 and 80 with the TourEnchaînementBK.mov. What about the front views on page 79 and 80?

**Comment by rryman** [comment]
What do you think about making a note somewhere, that due to the fact that many review questions only have two options, it is in the reader's best interest to use this section as a review, instead of a quiz, i.e., don't just find the correct answer and move on, but take time to follow along both notation examples with the corresponding animations to understand the differences?

**Comment by rsryman** [comment]
None of the questions in Review 3 have only 2 options, but this good advice
actually applies to all questions where you can "assume" the remaining
label or selection.

Re pages 29, 55 and 82, perhaps move the images down a bit and add para 2:

Rather than selecting the correct answers and assuming that the remaining
choice is correct, take time to understand the differences by following
along all notation examples and corresponding animations.

Also, since you have so clearly modified the part bar repeat signs, no need
to make the Note bigger.

PS: What vegetable would you suggest for standing rib roast and mashed
potatoes? Is Arthur getting a lot of broccoli at home? I normally make
carrots and peas but they are high in sugar.  Green beans? Brussel sprouts?

**Comment by rryman** [comment]
Did you see my TourEnchainement movies post?

**Comment by rsryman** [comment]
See revised animation uploaded:

Review7EntrQuatRoyalBK+.mov

**Comment by rryman** [comment]
Thanks. I am using this one even if it is a bit odd that she bends and stretches once the music has finished. It highlights choreographically why we used the exclusion bracket and straightened the legs instead.

**Comment by rsryman** [comment]
I'll go with your logic.

**Comment by rryman** [comment]
I have completed Review 7. Make sure you look at all the questions again.
I am not convinced that I have created the notation examples correctly.
Please check them all carefully.
