### ISSUE TITLE
Review 5.5 Part-bar/Solid with FIN

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#108]
Back view animation for the following notation please:
![ch5battementglissesolid](https://cloud.githubusercontent.com/assets/15850667/18618535/c6c0d05e-7db6-11e6-8dd4-ff119090a8a4.jpg)

**Comment by rsryman** [comment]
As discussed, we are changing the starting position to 5th L ft, the rest is the same.

Animation uploaded: Review5BattementGlissDégBK.mov
