### ISSUE TITLE
Chapter 8 - Next Steps

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#109]
The animation doesn't slide into lunge on count 1 - he seems to go through 4th with both knees bent. Do you want me to change the notation?

**Comment by rryman** [comment]
As discussed via phone, I have changed the notation to a slide into 4th demi-plie (with no qualification on the slide line). I have updated the book accordingly.

**Comment by rsryman** [comment]
p. 89 rewording suggestion: Now that … , here is an excerpt that illustrates what we'll be covering….

Otherwise Next Steps looks good -- pending the BMN revisions (not yet in the version I have).
At this point, can we safely delete the Appendix?
