### ISSUE TITLE
Notation of Ben's Tour Enchaînement

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#11]
Is this how you would notate Ben's Enchainement with cross-phrased repeats? If so, should we notate it this way only and explain cross-phrased repeats? Or should we still give both examples?
[ÉchappéBattuTourAcrossPhraseRepeats.pdf](https://github.com/rryman/BeneshForBalletBook3/files/44195/EchappeBattuTourAcrossPhraseRepeats.pdf)

**Comment by rsryman** [comment]
Yes, this is how I envisioned it.

I think cross-phrasing often confuses people (dance-wise you don't think of this phrase as being cross-phrased), but here it simplifies the notation. The i-icon text would clarify the timing (i.e., the plié intro to the first phrase is on "4" but to the 2nd phrase it's on "8"). Might be useful to show both notational options.

**Comment by rryman** [comment]
Why do you like the landing in plie and stretch in bars 7 & 8 in the "Entrechat Quatre and Entrechat Royal", but you didn't want me to add it in Ben's Tour enchainement?
It seems a bit inconsistent to me.

**Comment by rsryman** [comment]
Can't seem to find this on Github so I'll answer here.

Inconsistent or an illustration of different intentions? Perhaps when we
see this in the book we can make a better decision.

**Comment by rryman** [comment]
I have made notes in the mock-up to cross reference "Entrechat Quatre and Entrechat Royal"and Ben's Tour enchainement to show the implicit verses explicit landing in plie and restretching.
I am now closing this issue. We can come back to it if necessary, once we flesh out the book.
