### ISSUE TITLE
Review Instructions

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#110]
Text to be reworded on pages 29, 55, and 82.
Change second paragraph to be more generic ... Rhonda to wordsmith.

Each Review section contains a different number of questions. You know you have finished each section when you reach the "Number of Answers Correct" page. To move to the next question in a section, swipe within the question box (bounded with a light grey rectangle) or tap the red arrows at the bottom. To move between the different Review sections, tap on the right or left side of the screen (outside of the black bounding rectangle).

**Comment by rsryman** [comment]
Very clear but a bit long? Do you think this reduced version is clear enough:

Each Review section contains several questions. To move to the next question within each section, swipe inside the light grey rectangle or tap the red arrows at the bottom until you reach the "Number of Answers Correct" page. To move between different Review sections, tap on the right or left side of the screen outside the black rectangle.

Review 7 is challenging but fair. Great work, sis!

**Comment by rryman** [comment]
Sis, I don't really like the beginning paragraph we presently have. Can we say something along the lines of ...

Test your ability to read Centre Work covered in this chapter by doing the following reviews. To gain the most out of this review, we recommend you take time to understand the differences by following along all notation examples and corresponding animations in each review section.

Each Review section contains several questions. To move to the next question within each section, swipe inside the light grey rectangle or tap the red arrows at the bottom until you reach the "Number of Answers Correct" page. To move between different Review sections, tap on the right or left side of the screen outside the black rectangle.

**Comment by rsryman** [comment]
Yes, let's streamline it as you have suggested. Do you think it is
confusing that we say "reviews" in sentence 1 and "review" in sentence 2? A
few suggestions:

Reinforce your understanding and test your ability to read Centre Work
covered in this chapter by doing the following reviews. To gain the most
out of each question, [delete: we recommend you] take time to understand
the differences by following along all notation examples and corresponding
animations [perhaps delete: in each review section].

Each Review section contains several questions [we say "questions" a lot;
could we say "sub-sections" here?]. To move to the next question within
each section, swipe inside the light grey rectangle or tap the red arrows
at the bottom until you reach the "Number of Answers Correct" page. To move
between different Review sections, tap on the right or left side of the
screen outside the black rectangle.

**Comment by rryman** [comment]
How about:

Reinforce your understanding and test your ability to read Centre Work covered in this chapter by doing the following review. To gain the most out of this review, take time to understand the differences by following along all notation examples and corresponding animations.

This review contains 3 sections and each section contains several questions. To move to the next question within each section, swipe inside the light grey rectangle or tap the red arrows at the bottom until you reach the "Number of Answers Correct" page. To move between different sections, tap on the right or left side of the screen outside the black rectangle.

**Comment by rsryman** [comment]
Bingo!
