### ISSUE TITLE
Recent Changes and To Do's

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#114]
I have uploaded updated .iba and .ibooks files.
1) The Glossary should now be complete. Just awaiting further edits from you.
**Agreed** 2) I don't plan to change the colour buttons because the readers don't see them and they give us a bit of a clue as to what definitions belong to Books 1, 2, and 3. This may come in handy at some point.
3) I will proofread only the Glossary terms that "pop up" in the pages of the book.
4) I still have to finish proofreading the "i" boxes.
**√** 5) Page iii - List of Chapters: text updated, page numbers, and links updated ***please check***
**√** 6) Appendix added. Page 94 (I have taken the "s" off "links" and put a "G" at the start of Glossary. **Is the image okay? Placement?**
**√**7) Page 95 - **please check wording and images**
**Maybe we should change "…, but you can access the Glossary in two ways:" to "…, so there are two ways to access the Glossary:" -- your call. The only other rewording to consider is to change "as illustrated on page 94" to "as illustrated on the previous page" -- your call. You have also moved "icons" to after its image.** 
**√** 8) Page 96 - relinked **please check**
**√** 9) Page 99 - relinked **please check**
**√** 10) Page 100 - "Sources" relinked **please check**
**√** 11) I also had to redo the Chapter and Section headings in RED on pages 95, 97, 100, and 101 because they changed when I added the Appendix section.

I sincerely hope I caught all the broken links!

**√**The only outstanding item above is p. 95.

**Comment by rryman** [comment]
Do a Google Hangout with Rhonda and check the data about the book in the "Inspector Window" in the .iba file.

**Comment by rsryman** [comment]
See comment above re p. 95.
