### ISSUE TITLE
Letter to Proofreaders

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#115]
Here's what we have so far:
[ProofreadingBook3Request.docx](https://github.com/rryman/BeneshForBalletBook3/files/539998/ProofreadingBook3Request.docx)

People to ask:
Liz Cunliffe, Eliane Mirzabekiantz, Anuschka Roes, Susanna Cheung, Barbara Dearborn, Rosalynd Elliott, and Carla McGree-Eakin?

**Comment by rryman** [comment]
Corrections:
There are now 101 (not 99) pages in the book.
Should we include a timeline in the first letter, or does that belong in the follow-up letter?

**Comment by rryman** [comment]
Updated version:
[ProofreadingBook3Request.docx](https://github.com/rryman/BeneshForBalletBook3/files/540026/ProofreadingBook3Request.docx)

**Comment by rryman** [comment]
Sis, do you have a copy of the follow up letter you sent to proofreaders for Book 2 so we can use it as a template for the Book 3 letter?
If not, I will try to dig through my old email messages.

**Comment by rsryman** [comment]
I found a letter or Book 1, coppied below. Will continue to look re Book2.

[ProofreaderLetter.docx](https://github.com/rryman/BeneshForBalletBook3/files/540093/ProofreaderLetter.docx)

**Comment by rsryman** [comment]
Draft Guidelines letter attached, for comments:

[ProofreaderGuidelinesBook3.docx](https://github.com/rryman/BeneshForBalletBook3/files/544579/ProofreaderGuidelinesBook3.docx)

**Comment by rryman** [comment]
I have added the following two documents to BeneshForBalletBook4 Repository.
ProofreadingBook3Request.docx
ProofreaderGuidelinesBook3.docx
