### ISSUE TITLE
Revisions Based on Reviewer Feedback

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#116]
**DONE**
Eliane Oct 23/16: Thank you Robyn, p25 grand battement : I would see the head inclined toward the left and turn right. How it is written, I look down and not towards the upper arm as the animation shows it.

The intention is an effacé line, slightly raised to complement the high grand battement. 

- [x] Robyn to alter the BMN: raise the head one pixel to be clearer in the small iPad screen.
Rhonda to update the animations:  slight head raise and turn+incline right.
Rhonda to reply to EM in Dropbox.

2 updated animations uploaded to Dropbox:

- [x]  CH3GrandBattement&ClocheFR.mov

- [x] CH3GrandBattement&ClocheBK.mov

**Comment by rsryman** [comment]
Per Ros's feedback, right red foot updated in 4 files uploaded to DropBox:

BB9NestedRepeats2BK.mov
Ch7.2Animation1.mov
Ch7.2Animation2.mov
Ch7.2Animation3.mov

**Comment by rryman** [comment]
Sis, I know I said I wouldn't post on GitHub as I was implementing the corrections, but you had already started a thread for this issue so I thought I should include the update here.
As per our telephone conversation ...
[x} BB9NestedRepeats2BK.mov is fine.
The endings are different for the following 3 files:
[_] Ch7.2Animation1.mov
[_] Ch7.2Animation2.mov
[_] Ch7.2Animation3.mov
They disappear after I play them on my Desktop computer.
On my iPad they disappear but pop back to the beginning quickly.

**Comment by rsryman** [comment]
I added 2 seconds to the end of each and uploaded all 3 files to Dropbox. Better?

**Comment by rryman** [comment]
Yes, thank you!
