### ISSUE TITLE
Waiting for Rhonda's Reply

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#118]
Book 3:
1. Glossary - grand plie "closed **and crossed**" (open 4th)?
2. Cecchetti assembles - 5th not 1st in the air? Pop-up explaining alternate?

Worksheets (Book 1)
1. Look at Page 4 - is greyed out notation okay? Is it an improvement? Is it too light?
Continue updating the rest of the pdf?

**Comment by rryman** [comment]
Also:
1. Book 3 Flyer - did you proofread the latest version based on the updated Metadata?
Are there any edits?

**Comment by rsryman** [comment]
We were going to do this together as I was having problems finding the
right versions, and also the reference to 26 enchaînements (+ over 100
animations ??).

**Comment by rryman** [comment]
Worksheets Book 1

- [ ] Rhonda likes greyed signs as is. Robyn to continue updating the rest of the PDF.

**Comment by rryman** [comment]
Still outstanding ... Rhonda doing more research ...
Book 3:
- [ ] 1.Glossary - grand plie "closed and crossed" (open 4th)?

- [ ] 2.Cecchetti assembles - 5th not 1st in the air? Pop-up explaining alternate?

**Comment by rsryman** [comment]
Re pp. 76-78 Assemblés
When we decided to do the "nowadays" head, it should have twigged me to do the same for the aerial position. I won't begin to update the animations until you confirm/agree. This is the simplest solution I can think of, but please weigh in. 

p. 76: Rhonda to update 2 animations. Robyn to change the 2 aerial 1st position signs to 5th position signs, sorry. You will also need to change the aerial position in the bottom right popup. 
Re the traditional aerial position, there are two possibilities (I prefer the 2nd):
Add a popup above the bottom left popup: aerial position in 1st with pulse beat - one frame only, with text: 
"The Intro Bar 4 count 3 and Bar 4 count 3 above, show the aerial position done nowadays: 5th position. 
The notation in the popup below shows the traditional usage. In Cecchetti's day, the dancer strove to do a plié à quart in 1st position in the air, bending the knees slightly to bring together the flat of the toes of both feet before alighting in 5th position."
OR
Expand the bottom right popup to include 2 frames: brush and arms open with head pure incline and aerial position in 1st with pulse beat - one frame only, with text: 
"The Intro Bar 4 counts 2-3 and Bar 4 counts 2-3 above, show the head and aerial position done nowadays: head slightly inclined, turned, and raised over the foot that brushes, then aerial 5th position. 
The notation in the popup below shows the traditional usage: a pure incline over the foot that brushes, then aerial 1st position. In Cecchetti's day, the dancer strove to do a plié à quart in the air, bending the knees slightly to bring together the flat of the toes of both feet before alighting in 5th position."

p. 77 Rhonda to update both animations (from p. 76 updates); Robyn to update notation (1st position -> 5th position, twice)

p. 78 Rhonda to update both animations; Robyn to update notation (1st position -> 5th position)

**Comment by rryman** [comment]
**Rhonda:**
p. 7 Should we add a clarification to the start of para 2: 
“This sample review contains only one question. The full review contains three sections and each section contains several questions.…”

**Robyn:**
“This sample review contains only one section with two questions. The full review contains three sections and each section contains several questions.…”
Rhonda do you agree with this wording?

**Comment by rryman** [comment]
If we change the notation for the Cecchetti assemble to be 5th in the air ... it also has to be updated in the Review Question 8 of 9, and 9 of 9!

**Comment by rsryman** [comment]
Agreed.

**Comment by rryman** [comment]
Sample Book P 7.
If we are updating the text, then I think we should take out the link to the "GO TO: NEXT SET OF REVIEW QUESTIONS" and take out "To move between different sections, tap on the right or left side of the screen outside the black rectangle." ... as now there is only one section.

So now it will read:
**Reinforce your understanding and test your ability to read Centre Work by doing the following review. To gain the most out of this review, take time to understand the differences by following along all notation examples and corresponding animations.

This sample review contains only one section with two questions. The full review contains three sections and each section contains several questions. To move to the next question within a section, swipe inside the light grey rectangle or tap the red arrows at the bottom until you reach the "Number of Answers Correct" page.**

Text now reads:

**Comment by rryman** [comment]
See updated GitHub comment about P. 7

**Comment by rryman** [comment]
New Sample Book 3 Uploaded to DropBox.

**Comment by rryman** [comment]
Glossary definition for Grand Plie.
The confusion for me is the Glossary definition for 4th is described as "open" and in the Grand plie definition 4th opposite 5th is described as "closed". I know you have taken this from the Cecchetti dictionary, but in this case I like find your RAD wording less problematic.

Could the definition be?:
Grand plie (big or full bend) is done with the knees bending outward as much as possible, in all positions of the feet. In 1st, 4th crossed, and 5th positions, the bending action causes the heels to be released from the floor. During the straightening of the legs, the heels are lowered to the floor as soon as possible, making the movement continuous. In 2nd position and open 4th however, because there is a wider base, the heels remain on the floor.
