### ISSUE TITLE
Cecchetti Assemblé

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#119]
1. Rhonda waiting to hear back from Sandy and Norma Sue before Robyn changes notation examples on pages 76, 77, 78, 83 (Q 8of9 and 9of9).

2. Rhonda says she will keep the animations as is.

3. If notation changes to aerial position in 5th, Rhonda will provide Robyn with the notated analysis of the aerial position in 1st (or skimming info instead of aerial position?) and the pop-up text (see entry below copied from GitHub #118).

Below is Rhonda's GitHub entry about this issue back when it was originally discussed:
"As we discussed by phone, I used Pilkington's notation showing 1st in the air and think it needs to be in our BMN. I made Maria pass through 1st but not hold the position. This "sole-to-sole" aerial position is part of Cecchetti technique so I think Cecchetti readers will understand the intention.

This brings up an interesting theory question - BEYOND THE SCOPE OF THIS BOOK - but interesting to consider. This intention might better be shown by some sort of zoning rather an aerial position. We'd need a Cecchetti expert to say whether the soles skim and hold or skim in passing. Until then, we should go with Linda's analysis."

**Comment by rryman** [comment]
See GitHub #118 re this discussion.

**Comment by rryman** [comment]
Copied from GitHub #118

Re pp. 76-78 Assemblés
When we decided to do the "nowadays" head, it should have twigged me to do the same for the aerial position. I won't begin to update the animations until you confirm/agree. This is the simplest solution I can think of, but please weigh in.

p. 76: Rhonda to update 2 animations. Robyn to change the 2 aerial 1st position signs to 5th position signs, sorry. You will also need to change the aerial position in the bottom right popup.
Re the traditional aerial position, there are two possibilities (I prefer the 2nd):
Add a popup above the bottom left popup: aerial position in 1st with pulse beat - one frame only, with text:
"The Intro Bar 4 count 3 and Bar 4 count 3 above, show the aerial position done nowadays: 5th position.
The notation in the popup below shows the traditional usage. In Cecchetti's day, the dancer strove to do a plié à quart in 1st position in the air, bending the knees slightly to bring together the flat of the toes of both feet before alighting in 5th position."
OR
Expand the bottom right popup to include 2 frames: brush and arms open with head pure incline and aerial position in 1st with pulse beat - one frame only, with text:
"The Intro Bar 4 counts 2-3 and Bar 4 counts 2-3 above, show the head and aerial position done nowadays: head slightly inclined, turned, and raised over the foot that brushes, then aerial 5th position.
The notation in the popup below shows the traditional usage: a pure incline over the foot that brushes, then aerial 1st position. In Cecchetti's day, the dancer strove to do a plié à quart in the air, bending the knees slightly to bring together the flat of the toes of both feet before alighting in 5th position."

p. 77 Rhonda to update both animations (from p. 76 updates); Robyn to update notation (1st position -> 5th position, twice)

p. 78 Rhonda to update both animations; Robyn to update notation (1st position -> 5th position)

**Comment by rryman** [comment]
If this is the text you want for the Pop-up with only the aerial 1st position and not the analysis, then I suggest adding something like **(the notation analysis is beyond the scope of this book)** at the end of the pop-up text?

The Intro Bar 4 counts 2-3 and Bar 4 counts 2-3 above, show the head and aerial position done nowadays: head slightly inclined, turned, and raised over the foot that brushes, then aerial 5th position.
The notation in the popup below shows the traditional usage: a pure incline over the foot that brushes, then aerial 1st position. In Cecchetti's day, the dancer strove to do a plié à quart in the air, bending the knees slightly to bring together the flat of the toes of both feet before alighting in 5th position.

**Comment by rryman** [comment]
Rhonda, here is the text I ended up using in the modified pop-up on page 76. If you want it reworded, please copy and paste it into a new comment with your edits so I can just cut and paste it into the book.
___
The Intro Bar 4 counts 2-3 and Bar 4 counts 2-3 above, show the head and aerial position done nowadays: head slightly inclined, turned, and raised over the foot that brushes, then aerial 5th position.

The notation in the popup below shows the traditional usage: a pure incline over the foot that brushes, then aerial 1st position. In Cecchetti's day, the dancer strove to do a plié à quart in the air, bending the knees slightly to bring together the flat of the toes of both feet before alighting in 5th position. (The notation of the analysis of plié à quart is beyond the scope of this book.)

**Comment by rryman** [comment]
Robyn has updated and uploaded a new version of the book to DropBox:

- [ ] Page 76 main notation.
- [ ] Pop-up image and text on left side of page.
- [ ] Pop-up image on right side of page.
- [ ] Page 77 main notation.
- [ ] Page 78 main notation.
- [ ] Page 83 Q8of9 main notation and 4 assemble examples below.
- [ ] Page 83 Q9of9 notation of 4 assemble examples.

Rhonda have I missed anything? Did I introduce any new errors?

**Comment by rryman** [comment]
Sis, if we are being really picky about matching the animation to the notation in the Cecchetti assembles, it really doesn't look to me like Maria brushes her leg in second as high as it is notated. I know I mentioned this to you before and you said that you took the height of the notation from Linda's analysis, but it sure doesn't look like Maria is brushing to hip height to me!

**Comment by rsryman** [comment]
I'll have a look at all of this as soon as I get set up. Love, sis

**Comment by rsryman** [comment]
The notation is correct on pages 76-78 and 83. 

Suggested update to the last sentence in the popup, since the analysis would need to address the foot zoning as well as relaxed knees in the plié à quart (brackets not needed?): 

Detailed analysis of this aerial position is beyond the scope of this book.

**Comment by rryman** [comment]
I have implemented the update to the pop-up on page 76.
