### ISSUE TITLE
Use of Different Sorts of Repeat Signs

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#12]
1) Should we also have a cross-phrased version for the "Entrechat Quatre and Entrechat Royal"?
2) Should "Grand Changement and Echappe Battu" be cross-phrased rather than part-bar?

**Comment by rsryman** [comment]
Can we see this in your mock-up and discuss by Hangout?

**Comment by rryman** [comment]
I making notes in blue in Book 3 as I create the mock-up. I can share the mock-up book with you if you want, but it is a work in progress so I am hesitant to do so until I get it to a stage where it is all a bit more sorted out so I won't confuse you by still having a mix of old and new.

**Comment by rsryman** [comment]
I understand. Candy and Daniel are expected any moment so perhaps we can
differ this until they leave on Saturday.

**Comment by rryman** [comment]
I'll keep working on the mock-up and then we can decide what to do once Candy leaves.
