### ISSUE TITLE
Use of Canadian English spelling

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#120]
Why use American English if we sell very little in the US? What would you say about using Canadian English spelling in our iBooks 3 and 4, since that is how my default spell checker is set? It seems consistent with British and Australian usage, e.g. practice n versus practise v (although our punctuation is more in line with US).

A global search of "practice" also pick up "practiced" --> practised
I found only 2 changes in the body of Book 3: practiced --> practised on p. 2 para 2 & 3
A global search of the Glossary picked up up several, which we could do together via Hangout.

I found no instances of "travelling" versus "traveling" only "travels," and only 1 instance of "edited" (correct) on p. 100. Any other things you can think of??

**Comment by rryman** [comment]
I suggest the best way to handle this is to do a Google Hangout where I
share my screen as we edit the book together.

**Comment by rsryman** [comment]
I went through the entire Glossary and looked for "non-ballet French" words used in definitions. In our Google Hangout tomorrow we can do global searches on word in the imbedded "SpellingTemplate.docx" MS Word file. 

On my MacBook, the non-Canadian English words are underlined in red.

[SpellingTemplate.docx](https://github.com/rryman/BeneshForBalletBook3/files/584579/SpellingTemplate.docx)

**Comment by rsryman** [comment]
I'm home and at the computer. Whenever you are ready just start the Hangout
and I'll answer the alert. Love, sis

**Comment by rryman** [comment]
I thought we set our Google Hangout for 10:00?
You are not answering my Google call and your phone went straight into
voicemail.

**Comment by rsryman** [comment]
We cannot find a Canadian dictionary on line so we decided to use British spellings:
[BritishSpellingTemplate.docx](https://github.com/rryman/BeneshForBalletBook3/files/586499/BritishSpellingTemplate.docx)
 https://en.oxforddictionaries.com/

**Comment by rryman** [comment]
I have moved this document and link to BeneshForBalletBook4 Repository; Issue #1 - Online Dictionary for Book 4
