### ISSUE TITLE
Wording for Repeated Bars - Pages 36, 37, and 38

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#121]
Sis, before I send the PDFs of these three pages to Susanne I thought I would cut the text into a Word doc so you could view it altogether.

When you are fresh, and have some time, please take a look at the attached document and let me know if you think any of it should be reworded.

[TextP36,37.38.docx](https://github.com/rryman/BeneshForBalletBook3/files/586657/TextP36.37.38.docx)

[TextP36,37.38.pdf](https://github.com/rryman/BeneshForBalletBook3/files/586659/TextP36.37.38.pdf)

**Comment by rsryman** [comment]
Looks good to me. We'll see what Susanna and Liz say.

**Comment by rryman** [comment]
Emails sent to Susanne and Liz. Awaiting their input.

**Comment by rryman** [comment]
Updated with Rhonda via a Google Hangout on Monday 21st November 2016. Rhonda to check updated Book in Dropbox to make sure pages 36, 37, and 38 are now correct. I uploaded both the updated .iba and .ibooks file.

**Comment by rryman** [comment]
Pages 36, 37, and 38 were reviewed and agreed upon.
