### ISSUE TITLE
Latest Version of Benesh for Ballet Book 3 Worksheets

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#122]
Sis, please check that this is the most up-to-date version of Book 3 Worksheets:

[BB3WorksheetsSept9.2018.pdf](https://github.com/rryman/BeneshForBalletBook3/files/2554978/BB3WorksheetsSept9.2018.pdf)

**Comment by rsryman** [comment]
I have a more recent pdf:
[BB3WorksheetsSept12,2018.pdf](https://github.com/rryman/BeneshForBalletBook3/files/2558782/BB3WorksheetsSept12.2018.pdf)
