### ISSUE TITLE
Proofreading - BB3 Worksheets - Footer

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#123]
The month stated in the copyright line needs to be updated when Robyn does final edits in Adobe Illustrator.

**Comment by rsryman** [comment]
If it would be easier, I can update the footer in the Word files for Worksheets 3-4 with whatever we decide.

**Comment by rryman** [comment]
Let's discuss this when I have finished proofreading BB3 Worksheets and I am ready to do all the Adobe Illustrator updates on BB2. I'll try to guesstimate how much time editing the BB2 worksheets will take and you can update the footer before I start.
