### ISSUE TITLE
Temps Levé and Petit Échappé

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#14]
I just uploaded the front and back view animations into Dropbox "For Robyn."

1. To reflect the cushioned re-stretch at the end of the sequence, should we add 2 bent knee signs to Bar 8 ct 1 and show the restretched 5th in the final "empty" frame? If so, edit the i-icon text:
**Bars 9-16.** Repeat other side, re-stretching on the final count OR on Bar 16 count 2.

2. Re Robyn's comment about Glossary: Are we re-defining terms defined in previous books? I think we did for some terms in Book 2, introduced in Book 1. TO BE DISCUSSED. I'll open a separate Issue for this.

**Comment by rryman** [comment]
Animations, notation, and "i" text updated 30/11/2015.
**Rhonda, please check if the ending notation is correct and if the "i" update is okay.**
If we use this example to show "nested-repeats" I will have to update that notation as well.
**Rhonda, please assign it back to me once you have checked the notation and "i" box info.**

**Comment by rsryman** [comment]
Let me know when you have uploaded a version of iBook 3 for me to check.

**Comment by rryman** [comment]
I'll save what changes I have made so far and I will upload the latest version of the book to dropbox. I think I have run out of steam for today anyway!!!

**Comment by rryman** [comment]
Latest version uploaded.

**Comment by rsryman** [comment]
I hear you. Same here... Pat on heads and time for some TLC from hubbies.

**Comment by rsryman** [comment]
Is the pulse beat needed on Bar 16 ct 1? It suggests to me that ct 1 is held - although that would leave Anna hanging in the air in this case. I measured the last bar and see that it is less wide than any but the empty intro bars, but do you think you could make it a bit less wide and the "Bars 9-15" bar a bit wider?

i-icon text checked√  

Leave pop-up info as is and defer Glossary/sound clips for now.

**Comment by rryman** [comment]
Pulse beat used in RAD Set Exercises and Variations. Robyn to send example to Liz to check if it is also correct not to use the pulse beat in the repeat bar.

**Comment by rryman** [comment]
I sent the example to Liz and she says we don't have to use the pulse beat in the empty repeat bar.
I have also sent Liz an example of the same allegro exercise without the bent knees on Bar 8 count 1 to see if we can get away with keeping the notation simple and let the reader assume that they don't have to straighten their legs before repeating to the other side. I'll let you know the verdict.

**Comment by rsryman** [comment]
OK, this is the only AllegroWithRepeats we need to keep open for now?

**Comment by rryman** [comment]
Yes, let's keep it open until I hear back from Liz.

**Comment by rryman** [comment]
Here is what Liz had to say:
"Given that the tempo is allegro I think you can get away with the simple version: so I'd go along with omitting  the demi-plie at the end of the sequence.  You'd have to be a technical nerd to try to read a straightening of the knees into the repeat, certainly if that is what I wanted the dancer to do I'd put both the demi-plie on the landing and the straightening on the last beat before the repeat sign. The only effect that omitting the plie could logically have is that the final straightening might happen before the last count - the assumption being that you straighten immediately not necessarily in rhythm - although it wouldn't be wrong to do so."
**We need to discuss this via Google Hangout so we can look at the endings of all the enchainements and decide what to do in each case.**

**Comment by rryman** [comment]
I have updated all the notation as best I can. We will need to recheck it all once we get to that chapter and we will need to also check the text in the "i" boxes.
