### ISSUE TITLE
Glossary Entries

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#15]
We should decide which terms need Glossary entries. 

1. Clear for terms which do not appear in Books 1 or 2. Rhonda to supply new definitions. Robyn to add "button" to access.
2. When should we include/repeat Glossary entries for terms previously used/defined?
3. We may need to update definitions for some terms previously defined, e.g, pointe tendu (English) -> dégagé (cross-reference pointe tendue (Italian) and ?? (Russian).

**Comment by rryman** [comment]
I think you should check with me before you supply me with new definitions because they may already be available to copy from Book 1 and Book 2. If not, I can let you know and you can create a new definition.

I think we are going to have to deal with this one glossary definition at a time as they occur.

**Comment by rsryman** [comment]
Agreed. I just wrote a note on this issue related to glossary entries for retiré. I wanted to copy it here, - but now I can't find where it is! I thought it was in an Issue about Images (re FootToKnee contact).

**Comment by rsryman** [comment]
To be added to iBook3 if and when needed (stored here for safety):

![image](https://cloud.githubusercontent.com/assets/15932418/11695795/15e0c9f4-9e7f-11e5-8d60-43baf2bd8c4b.png)

**Comment by rryman** [comment]
Please look at page 9 and tell me how you would like these terms linked to the appropriate Glossary definitions you have provided? Do you want me to separate Degage, English and Degage, Russian into there own boxes. Do you want me to take out Pointe Tendue, Italian because you haven't given me a definition? Do you want me to put in the Degage, Italian definition into the Glossary but not link it from this page because the foot in on the floor not off the floor and if so do you want me to cross-reference it from Degage, English and Degage, Russian?

**Comment by rsryman** [comment]
I'm still trying to figure out how much vocab to use in BB7 versus the next chapter. We normally link to glossary entries in content chapters but in this book we show enchaînements versus single steps. I'm just starting to cross-reference battement actions. Vaganova has a slightly different terminology. Can we  defer a decision until we get into the content chapter?

**Comment by rsryman** [comment]
Here is a mockup for the next two mvt lines pages. Four animations uploaded to BB7MvtLines folder: 

BB7DévEnvSideBK.mov
BB7GrandBattementDevDerBK.mov*
BB7BattementGlissé5thBK.mov
BB7BattementJeté5thBK.mov

*Don't add this to the book until we decide on the zoom (arms to 5th en haut or held in 2nd on p. 17)

[WORDTEMPLATE_mvtlines2.docx](https://github.com/rryman/BeneshForBalletBook3/files/60569/WORDTEMPLATE_mvtlines2.docx)
[WORDTEMPLATE_mvtlines3.docx](https://github.com/rryman/BeneshForBalletBook3/files/60570/WORDTEMPLATE_mvtlines3.docx)

**Comment by rryman** [comment]
Yes, we can defer the decision until the content chapter. I don't think there is any need for any other glossary terms (except Pointe Tendue, Italian) to be linked in the BB7 chapter.

**Comment by rsryman** [comment]
I have uploaded a word file: Book3GlossaryEntries.docx

It contains Glossary Definitions for terms up to the end of Chapter 3, entered in chart format that follows the page order of our iBook. 
Please read the note at the top of the file and input entries in the chart only (disregard the definitions after the chart as they were for my use only, in compiling the entries).

I have also uploaded PronunciationSoundFiles. If you view them by date, the order will follow the order of presentation in our iBook. I created sound files for all terms in the chart, even those with bracketed page numbers (indicating they probably will not be linked to a button, so you will probably not need to use all 30). IF THERE IS ANYTHING YOU DON'T UNDERSTAND, PLEASE CALL ME.

**Comment by rryman** [comment]
I did the best I could with the sound clips and glossary entries. I updated the document in red for the entries I don't know how to link. I also couldn't find places for all the sound clips. I think I need to upload the latest version of the book and we will need to do a Google Hangout.

**Comment by rsryman** [comment]
Fast work!

My cover note explained that I created sound entries for every glossary
entry but not all have links in the book yet. Just keep on hand.

**Comment by rryman** [comment]
We completed the Glossary updates via Google Hangout. They will all have to be checked when we are both feeling clearer headed.

**Comment by rsryman** [comment]
Not sure how far we got with the above message from back in January 27.

I have updated the glossary definitions fiile and uploaded it to DropBox:
Book3GlossaryEntriesRHR.docx

See 3 new/revised entries (red font): Relevé, Détourné and Sissonne Simple on Pointes

**Comment by rryman** [comment]
The glossary definition for Sissonne Simple on Pointes is missing the French meaning.

A spring from two feet to one foot with the free foot placed sur le cou-de pied or at the knee, then closing in 5th position either sans changer or changée. Sissonne simple devant is first practiced starting in 5th position, demi-plié:  spring up onto the pointe of the back foot, raising front foot sur le cou-de-pied devant before finishing in 5th position demi-plié. Sissonne simple derrière is done with the back foot raised sur le cou-de-pied derrière. When done changée at the knee, the front foot lifts and passes around the knee before closing behind (en dehors) and the reverse (en dedans). In the English and Italian schools these actions are called relevé devant, derrière and passé (done with the foot placed at the front of the knee but passing just above the ankle before closing in 5th).
RELATED GLOSSARY TERM: relevé
