### ISSUE TITLE
Assemblé Soutenu

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#19]
Might these (dessus + dessous) be a good place to introduce repeats within repeats? 

The current version is an 8-bar sequence. The original Richard Maddock music track has 16 bars, so we could use the whole clip to repeat the basic sequence twice in all.

For now, I'll animate the 8-bar version but we might expand this later if needed.

**Comment by rsryman** [comment]
See 4 animations uploaded to Dropbox "For Robyn." 

Thanks for adding the label. I have been forgotting to do this.

**Comment by rryman** [comment]
I have added the new animations. Now that the foot is burgundy, it looks even more like Maria goes through 5th in the air and not 1st. Do you still want the notation to remain as it is, or should I change the aerial position, or take the aerial position out?

I have added your comment to each page about using nested repeats so we will remember to consider it when we get to making decisions about this section of the book.

**Comment by rsryman** [comment]
As we discussed by phone, I used Pilkington's notation showing 1st in the air and think it needs to be in our BMN. I made Maria pass through 1st but not hold the position. This "sole-to-sole" aerial position is part of Cecchetti technique so I think Cecchetti readers will understand the intention.

This brings up an interesting theory question - BEYOND THE SCOPE OF THIS BOOK - but interesting to consider. This intention might better be shown by some sort of zoning rather an aerial position. We'd need a Cecchetti expert to say whether the soles skim and hold or skim in passing. Until then, we should go with Linda's analysis.

Per our last phone conversations, can we close this Issue for now? Also all issues for AllegroWithRepeats?

**Comment by rryman** [comment]
Rhonda, if you look at your very first entry in this "issue" you will see that you said:
"Might these (dessus + dessous) be a good place to introduce repeats within repeats?
The current version is an 8-bar sequence. The original Richard Maddock music track has 16 bars, so we could use the whole clip to repeat the basic sequence twice in all.
For now, I'll animate the 8-bar version but we might expand this later if needed."

So for page 74, weren't you planning on doing a 16 bar version with the entire sequence dessus and then repeated in reverse with dessous?

**Comment by rsryman** [comment]
The problem would be tight real estate on the page: the entire 16-bars
would need at least 3 staves: the first 8-bar phrase over 2 staves and the
reverse in the 3rd stave showing the different heads. Could we accommodate
this?

I think we are givng more variety by altering the phrase as on p. 74, to
require readers to carefully read the different sequence rather than just
adding the sequences on the previous two pages.

Your thoughts?
