### ISSUE TITLE
Content of Book 3

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#2]
Original document posted by Rhonda.
[iBook3.Repeats.Outline.docx](https://github.com/rryman/BeneshForBalletBook3/files/40105/iBook3.Repeats.Outline.docx)
@rsryman

**Comment by rryman** [comment]
Document updated by Robyn. I think we need to simplify Benesh Basics 7 by moving repeats to Benesh Basics 8. Just give some simple centre exercises that don't need repeats (and use the exercises again when we introduce repeats in Benesh Basics 8).
[iBook3.Repeats.Outline.RHR.docx](https://github.com/rryman/BeneshForBalletBook3/files/40116/iBook3.Repeats.Outline.RHR.docx)

**Comment by rryman** [comment]
I have been working with the outline trying to piece Book 3 together in iBooks Author. I have moved FIN and Exclusion Bracket to Benesh Basics 8 for now. We can work out where we need to introduce them as we start to fill in the content of the book.

**Comment by rsryman** [comment]
Attached outline updated (moved FIN & excl brackets from BB9 to BB8)
[iBook3.Repeats.Outline.RHR+RR.docx](https://github.com/rryman/BeneshForBalletBook3/files/41998/iBook3.Repeats.Outline.RHR.RR.docx)
