### ISSUE TITLE
BeneshBasics Images for Foot-to-Floor Relationships

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#21]
I have uploaded 7 images for page 6, with 2 choices for 1st full pointes (See "BB7" folder). We may want to say that the precise placement of feet in 1st full pointes depends on context, e.g., rise versus relevé (and can be specified with zoning theory?).
**Doesn't this also apply to demi-pointes as well as pointes and most positions of the feet? In which, case do we show pics of both options for each position in the Benesh Basic pages, or make a note and link to a page in the Appendix which would make the BB pages look less cluttered?
If we mention zoning theory then we will need to show it in the Appendix page. How do you zone the difference?**

I used the 336x352 window dimensions. If you need the figure to fill the window, etc. let me know. 
**Is there any way you can eliminate all white space from Benesh Basics images when you export them? If not, I can try using an image editing program and will crop out the white space. The extra white space doesn't allow me to fiddle with the placement of the images on the page. They overlap each other. We don't need extra white space under Jenna's feet either because there is no playback bar like there is for animations.**

I'll create dégagé images for page 9 but wait to upload them until you confirm dimensions (these show arms in 2nd).
**No extra white space please.**

**Comment by rryman** [comment]
Is there any way you can eliminate all white space from Benesh Basics images when you export them? If not, I can try using an image editing program and will crop out the white space. The extra white space doesn't allow me to fiddle with the placement of the images on the page. They overlap each other. We don't need extra white space under Jenna's feet either because there is no playback bar like there is for animations.

**Comment by rsryman** [comment]
Rhonda to resend all images at minimal consistent width and height without white space below, as specified above. (Note to myself: 279 the lowest possible width for animations.)

**Comment by rsryman** [comment]
See uploaded jpg images in folders: BB7FlatToRise, BB7Dégagé, BB7FootToKnee.

Note to myself: Re BB7FootToKnee, I used Jenna with the RAD placement for retiré positions (Foundation p. 15, Dictionary p. 70). As we discussed, we will include glossary definitions IF we use specific dancers, OR if we decide to use terms to describe movements in enchaînements. The Russians call this "passé" or "tire-bouchon."

**Comment by rryman** [comment]
Is it worth sending the retiré images to Anuschka for her input?

**Comment by rsryman** [comment]
Good idea. Let's send the page when your first draft is done.

**Comment by rryman** [comment]
I don't know what you mean by "send the page". Do you want me to do a screen shot and send the screen shot to her?

**Comment by rsryman** [comment]
Sorry, yes just a pdf or screen shot. Is there a better way?

**Comment by rryman** [comment]
I have sent the attached image to Anuschka and asked for her input.
![retirepage](https://cloud.githubusercontent.com/assets/15850667/11575684/685544ba-99e0-11e5-87c4-81a9be5e17f6.jpg)

**Comment by rsryman** [comment]
I think the long toe segment makes the retiré derrière back view look more crossed. 

Are these any better (edit thigh x-value 6 "clicks" 39.98 -> 41.48): 

BB7_FootToKneeRback+
BB7_FootToKneeLback+

**Comment by rsryman** [comment]
Perhaps we should avoid using the term retiré here. Also I suggest we take out the sentence about pirouette, since the Russian placement is higher. Re the last sentence in para 1, I suggest something like: "Lower placements were covered in Book 2 (pages 14 & 15)." This should leave more space to offset the sentence below the BMN. 
Did we discuss linking to an Appendix that shows the contact sight centered on the knee line and sitting atop it (the Russian placement). Perhaps summarizing the 3 placements?

**Comment by rsryman** [comment]
This is the file I'd like to send to Ana. I'll ask her if the text and DanceForms figures are OK, and whether we should include the information in square brackets: "for passé and tire-bouchon positions and movements."
Questions:
1. If we say "This position is used [for passé and tire-bouchon positions and movements] in the Russian school," perhaps we should add on the previous page:  "This position is used for retiré positions in the English and Italian schools." I would need to send the images to Sheila Kennedy to confirm, since I think the Cecchetti retiré derrière is more crossed. This is where we get into sticky territory and simplify things by avoiding any reference to schools and using Jenna for both pages and. Let's wait to decide until I get an answer from Sheila.
2. We might want to add the "contact sign centred" placement on this page if possible. I could show only the figure's lower body to save space.

[FOOT-KNEE(Russian).pdf](https://github.com/rryman/BeneshForBalletBook3/files/55491/FOOT-KNEE.Russian.pdf)

**Comment by rsryman** [comment]
I just thought of a better wording: "The precise point of contact is understood in context but may be specified by the use of Zoning theory, which is beyond the scope of this book." OR "The precise point of contact is understood in context but may be specified via Zoning theory, which is beyond the scope of this book."

**Comment by rryman** [comment]
Can we please Google Hangout on this as I am not sure how to proceed on adding this to the book?

**Comment by rsryman** [comment]
See attached 
[FootKneeSummary.pdf](https://github.com/rryman/BeneshForBalletBook3/files/55988/FootKneeSummary.pdf)
mock-up of a summary page. As expected, the figures have to be very tiny for all 18 to fit on one page, and there is very little room for the BMN. At least it shows the different placements re bottom/middle/top of the kneecap, albeit too small to see clearly? Perhaps this page should be an Appendix. No need to decide now, we'll see if this is needed in the body of the book.

I am also attaching a mock-up of page 15, contacts to middle and top of kneecap, following the format on page 14. Bigger images, more room for notation and text. If we decide to use this page, I will send you 6 new full size figures to update page 14. We might also update the text and captions, in line.
[FootKneeMid&Top.pdf](https://github.com/rryman/BeneshForBalletBook3/files/56017/FootKneeMid.Top.pdf)

**Comment by rsryman** [comment]
I am attaching 3 mock-ups for page 15, in Word - they are 1 page each so if they are changed let me know if I should send these as pdf files. The only difference is the figures showing retiré devant, English from back versus front view (and two references in the text to explain this). We can hangout if needed.

[FOOT-KNEE(3schools).docx](https://github.com/rryman/BeneshForBalletBook3/files/57091/FOOT-KNEE.3schools.docx)
[FOOT-KNEE(3schools)ALT.docx](https://github.com/rryman/BeneshForBalletBook3/files/57090/FOOT-KNEE.3schools.ALT.docx)

**Comment by rsryman** [comment]
Yes, we read context, context, context. Another good catch, thanks - I think I'm going cock-eyed.

See revised image in DropBox BB7FootToKnee folder: BB7_FootToKneeJenna(RSL).jpg

I didn't change Anna on p. 16 (high placement, big to joint **above** knee joint) because the image was confirmed by Ana Jojic. On p. 15 Jenna shows low placement derrière (big toe joint just **below** centre of knee joint). The middle placement would be big toe joint **at** back of knee joint? Not much difference, but I can lower the p. 15 Jenna derrière images a bit if that would be clearer.

**Comment by rsryman** [comment]
Please have a look at the images Anuschka approved for RAD retiré derrière, uploaded to BB7FootToKnee folder:

BB7_RretderrAR.jpg
BB7_LretderrAR.jpg

What about using these for Jenna on p. 15?

**Comment by rsryman** [comment]
At least this is a clear image of a balletically acceptable position that illustrates the notation. I think it's ok.
