### ISSUE TITLE
BeneshBasics animations for Closing Signs

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#22]
I am following the notes on page 10 to create animations. Clarifications:

1. I'll time these to 4 metronome beats (1 sec hold at start + end), and use the metronome app to set a moderate tempo (Andante: 60 bpm).
2. I thought we said we'd use RL from 5th then LR from 3rd. Please confirm.

Should I wait for your notation before animating page 11, etc.? 

Please remind me how to create a new label for "BB7" issues.

**Comment by rsryman** [comment]
Uploaded to Dropbox: BB7p10_Tendu5th

For the metronome markings, I consulted:
http://www.goodwinshighend.com/music/classical/tempo_glossary.htm

**Comment by rsryman** [comment]
Also uploaded animation from 3rd RL since it was easy to edit and mirror. Can change if needed.

**Comment by rsryman** [comment]
Two animations uploaded to BB7 folder, RL from 5th & 3rd:

BB7p10_Tendu5thBK
BB7p10_Tendu3rdBK

**Comment by rryman** [comment]
Animations added.

**Comment by rryman** [comment]
Did you leave the same amount of white space under these animations as you did for the allegro animations? I seem to be having trouble with the playback bar cutting off the feet, even though I haven't reduced the size of the animations that much!

**Comment by rsryman** [comment]
I'll double-check.

**Comment by rryman** [comment]
Thanks! Much better.
