### ISSUE TITLE
Degage a la seconde

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#23]
The two images for degage a la seconde look like the working leg is off the floor because of the perspective. Is there anyway to fudge these two positions so the pointed foot looks like it is touching on the floor?

**Comment by rsryman** [comment]
Yes, sorry, I remember we had this problem in Book 1. New images uploaded to BB7:

BB7_dégagéRsideflat 
BB7_dégagéLsideflat

**Comment by rryman** [comment]
Down one pixel would be good. However, we can live with it as is if you want.
Do you want me to use a floor line for this page as well, or leave it out?
Do you want to do a Google Hangout and see if I can share my screen with you so you can see the page?

**Comment by rsryman** [comment]
I like this page. Spacing is fine. The floor line looks good. We should do whatever we did in Book 1 if possible. The two back view figures look slightly smaller, although the hands appear in line with the surrounding figures.
Sure we can Hangout when I send you the 2 updated jpg files with the toe tip a touch lower to side.

**Comment by rsryman** [comment]
See two files uploaded to BB7: BB7_sideflatL and BB7_sideflatR
