### ISSUE TITLE
AboutBalletClass text

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#29]
![image](https://cloud.githubusercontent.com/assets/15932418/11723957/14fe6ce2-9f3f-11e5-9dc8-bb51532a3b3a.png)

**Comment by rryman** [comment]
Rhonda, please cut and past this text into GitHub. I can't copy this text as it is in PNG format.

**Comment by rsryman** [comment]
I see that this text is now in Book3. I like the final paragraph you added.

I think the anecdote on Taglioni is more appropriate to the Repeats Chapter, so let's leave the current quote in. We need to confirm that it is attributed to Nureyev (I've heard it forever). Did you find this in a published source? I googled a bit but couldn't find anything, so if we can't confirm just take out his name.

**Comment by rryman** [comment]
What is considered a reliable quote source?
http://www.azquotes.com/quote/532388
https://en-pointe.com/dance-quotes/
http://www.52weeksofballet.com/2011/08/only-way-to-do-it-is-to-do-it.html
http://likesuccess.com/topics/4694/one-day/18

Should I something like ... Attributed to Rudolf Nureyev on the internet.

**Comment by rsryman** [comment]
I think we should use the quote, unattributed.

See:

http://www.barrypopik.com/index.php/new_york_city
Entry from June 23, 2012
“Miss one day of practice, I notice; miss two, the critics notice; miss
three, the audience notices”

A famous quote is popular with anyone who practices, from pianists to
ballet dancers to golfers. “If I miss one day’s practice, I notice it. If I
miss two days’ practice, the critics notice it. If I miss three days’
practice, the public notices it.” The first to notice the drop in
performance is the performer, then trained persons (such as professional
critics or a teacher or friends), and then the general public.

The Hungarian composer and pianist Franz Liszt
<http://en.wikipedia.org/wiki/Franz_Liszt> (1811-1886) was credited with
the saying in 1894. The Russian composer and pianistAnton Rubinstein
<http://en.wikipedia.org/wiki/Anton_Rubinstein> (1829-1894) was credited
with the saying in 1905. The German composer and pianist Hans von Bülow
<http://en.wikipedia.org/wiki/Hans_von_B%C3%BClow> (1830-1894) was credited
with the saying in 1910. The Polish composer and pianistIgnacy Jan
Paderewski <http://en.wikipedia.org/wiki/Paderewski> (1860-1941) was
credited with the saying in 1911. Paderewski receives almost universal
credit today, but the early citations of others (especially in a music
publication such as *The Etude*) probably indicate that he did not coin the
saying.

**Comment by rryman** [comment]
How do you make it so it doesn't seem like we are saying it?
Do you just put nothing ... or do you say "Quote Unattributed" ... "Original Source Unknown"?

**Comment by rsryman** [comment]
I think longstanding sayings (like "An apple a day…") don't need
attribution. This saying seems to be in the popular domain.

See:
http://web.ku.edu/~edit/attribute.html

**Comment by rsryman** [comment]
Duplication in Issues 29 and 40?
