### ISSUE TITLE
RiseVersusRelevé

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#30]
See mockup for pp. 13-14 in .doc and pdf formats. 
[RiseVsRelevé.docx](https://github.com/rryman/BeneshForBalletBook3/files/58688/RiseVsReleve.docx)
[RiseVsRelevé.pdf](https://github.com/rryman/BeneshForBalletBook3/files/58687/RiseVsReleve.pdf)

Which do you prefer? When you approve the contents I'll upload jpegs for the Jenna figures.

Animations for p. 14 were tricky to create. Comments welcome. 
Uploaded to BB7 RiseVersusRelevé folder:
BB7Tendu5thDemiFullDrawBK.mov
BB7Tendu5thDemiFullRelevéBK.mov

**Comment by rryman** [comment]
docx works best ... I can easily cut and paste both text and images.

Page 13 completed. Rhonda please let me know:
1) floor lines or no floor lines? (perspective of feet?)
2) size of notation?
3) size of figures?
4) captions centred versus left justified
5) accuracy of notation?
6) bolding of words - I haven't read your other comment on this issue yet, but will do so and update this page if necessary to match you other comments?
![risereleve1](https://cloud.githubusercontent.com/assets/15850667/11748961/eac26b8a-9ff8-11e5-9ad1-dec493c8369a.jpg)

**Comment by rryman** [comment]
1) Layout?
2) Accuracy of notation?
3) Bolding?

![risereleve2](https://cloud.githubusercontent.com/assets/15850667/11749265/b4b81736-9ffa-11e5-9f8c-d80383dd64be.jpg)
