### ISSUE TITLE
WordTemplate

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#31]
Black title: Helvetica 48
Text in body: Palatino 20
Caption: Helvetica: 15

I gave up on resetting the line spacing in Format > Paragraph > Line spacing. Help!

Please specify the font and size for RED TITLE (CONTINUED) and also footnotes, etc.
**Red Titles Palatino 24; Footnotes Helvetica: 15**

[WORDTEMPLATE.docx](https://github.com/rryman/BeneshForBalletBook3/files/59756/WORDTEMPLATE.docx)

**Comment by rryman** [comment]
[WORDTEMPLATEUpdate.docx](https://github.com/rryman/BeneshForBalletBook3/files/59818/WORDTEMPLATEUpdate.docx)

**Comment by rryman** [comment]
Updated Word Template - Animations down to 220 pt height (I just pray the playback bar doesn't cut off the feet on anyone's iPad!!!)
This template is not quite exactly correct, but it seems impossible to make things identical!
[WORDTEMPLATEUpdate+.docx](https://github.com/rryman/BeneshForBalletBook3/files/59878/WORDTEMPLATEUpdate.docx)

**Comment by rryman** [comment]
Which layout do you prefer for pages 10, 11, 12, 14, and 17?
1) Layout 1 has smaller animations, across the page text, and middle justified images.
![closingsign1](https://cloud.githubusercontent.com/assets/15850667/11756811/9d7f383a-a02a-11e5-9c55-1d966d79b473.jpg)

2) Layout 2 has larger animations, narrower text box and images left justified.
![closingsign2](https://cloud.githubusercontent.com/assets/15850667/11756813/a37e55e0-a02a-11e5-8ed6-f11c12147f58.jpg)
