### ISSUE TITLE
Proofreading - General

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#33]
Rhonda said:
Defer proofreading pages i-iii and p. 4 until first draft is complete, then proofread all before distributing draft to readers. Rhonda to start proofreading iBook3 from page 1, Dec 10/15. To be decided if Robyn should export all as .doc or pdf so Rhonda can update text without retyping all.

**Comment by rsryman** [comment]
For now I can retype. For new content, you want .doc format in my mockups. DOes attaching .doc files through GitHub work for you?

Can this be closed for now?

**Comment by rryman** [comment]
Yes, attaching .doc files in GitHub works for me. Yes, this can now be closed.
