### ISSUE TITLE
Proofreading - BB7 Intro page

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#35]
Rhonda suggested:
To begin reading exercised in Centre Practice, you need to understand theory introduced in Book 1 (the five-lined stave, frames, and positions of the arms, feet and body) [I think we can delete "and feet in relation to the floor" which we review here] and Book 2 (reading sequences of frames, basic movement lines, and legato lines." [Again, we can delete "foot contacting leg signs" which we also review here.] In this Chapter you will extend your reading of static positions of the feet taken flat, demi- and full pointes, summarized in Book 1, pp. 64-65, to include closing actions. And you will encounter more movement lines.

Robyn input:
**To begin reading exercises in Centre Practice, you need to understand theory introduced in Book 1 (the five-lined stave, frames, and positions of the arms, feet and body) and Book 2 (reading sequences of frames, basic movement lines, and legato lines. In this Chapter you will extend your reading of static positions of the feet taken flat, demi- and full pointes, summarized in Book 1, pp. 64-65, to include closing actions. You will also encounter more movement lines.**

**Comment by rsryman** [comment]
Text is fine. Under another Issue, I just suggested simplifying the footnoting format. 

I think we can close this Issue now.
