### ISSUE TITLE
Captions for Notation Examples

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#38]
I noticed you used a caption for the notation examples for the mock-up of the In-Frame Movement Lines page. Did you do this just so I could create the notation, or did you want captions added below each notation example on page 10, 11, 12, and 14? If so, what would you like them to say?

**Comment by rsryman** [comment]
I created them to guide both of us. Let's leave them for now. As we do the rest of BB7 we can decide whether they are necessary or redundant. Omitting them would leave more real estate and make for a cleaner page.

**Comment by rryman** [comment]
I am making an executive decision and not putting captions for sequences in the BB7 chapter. Let's let the animations do the talking. We can keep them under the notation where there is either no illustration, or only a static image.

**Comment by rsryman** [comment]
I think this is a good decision.
