### ISSUE TITLE
Writing Style

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#4]
Arthur @agryman 
Please reword the following paragraph in a more "story telling" way so Rhonda and I can understand, by example, how to modify the tone of our writing.

In Benesh for Ballet: Book 1 we introduced positions of the arms, positions of the feet, positions of the body, arabesques, and attitudes. Building on this theory, Book 2 introduced the basic structure of jumps performed without travel, as well as jumps with beats and turns, and the timing of basic allegro enchaînements. In Book 3 we will explore centre practice and repeated sequences.

**Comment by agryman** [comment]
Here's a rewrite:

You were introduced to positions of the arms, positions of the feet, positions of the body, arabesques, and attitudes in Benesh for Ballet: Book 1. Building on this theory, you then learned about the basic structure of jumps performed without travel, as well as jumps with beats and turns, and the timing of basic allegro enchaînements in Book 2. Here in Book 3 you will explore centre practice and repeated sequences.

**Comment by rsryman** [comment]
So you suggest a refocus from "we" to "you" better to engage readers, yes?

**Comment by agryman** [comment]
Yes. The rule in writing is the "we" refers to the authors and "you" refers to the reader. In a refereed journal, the text is formal so you don't refer to the reader. In an informal text, it's more engaging to refer to the reader.

**Comment by rryman** [comment]
Thanks Arthur. I have copied and pasted this updated text into Book 3.
Rhonda and I will work with your suggestions.
@agryman

**Comment by rryman** [comment]
Rhonda made this note in her "Proof-reading" thread:
General question/comment about informal writing style suggest by Arthur: I will aim for informality but try to avoid the passive voice.

**Comment by rsryman** [comment]
Can this be closed for now?

**Comment by agryman** [comment]
Yes, I'll close it now.
