### ISSUE TITLE
About This Book - Page 2

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#40]
Rhonda provided text doc under "Proofreading Page 1" which is now closed.
Robyn has input text, but suggests adding a sentence at the end to reflect what we plan to do in the book, i.e.,
"The simplified centre practice exercises presented in Chapter 3 will be shown without repeats. For notation reading practice, we have alternated which leg starts in front. Once Repeat Sign theory has been introduced in Benesh Basics 8, you will be able to read other centre practice exercises with repeats in Chapter 5."

**Rhonda, please feel free to reword this. I just think something is necessary because you talk about "Each movement is practiced on the right and left an equal number of times to develop symmetry, one of the basic hallmarks of classical ballet.", but we won't be doing that in Chapter 3 as Repeat Sign theory won't be introduced until BB8 and used in Chapter 5.**

**Comment by rsryman** [comment]
I think we just addressed this in another issue. OK for now?
