### ISSUE TITLE
BB7 - Across-Frame Movement Lines (page 19 as of 2015/12/14)

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#41]
Rhonda, Monica calls these "Between-Frame" movement lines in her book. Which do you prefer? Should I email Liz and ask what they call them now?

Rhonda states:
"When the movement line is too small to show the path within one frame, it is drawn across frames."

**This is true for the battement glissé (English) / battement dégagé (Italian), but you have choice of in-frame or across-frame for battement jeté (English, Italian) / battement tendu jeté (Russian) and battement en cloche.
1) What about only having the battement glissé (English) / battement dégagé (Italian) on page 19.
2) Battement jeté (English, Italian) / battement tendu jeté (Russian) on page 20 with one animation and both notated examples (in-frame and across-frame).
3) Battement en cloche on page 21 with one animation and both notated examples (in-frame and across-frame).**

Rhonda states:
"Using this convention, a slightly outwardly curved movement line denotes movement without flexion:"

**This sentence is misleading to me, because I don't think of these across-frame (between-frame) movement lines as being outwardly curved.**

**Comment by rryman** [comment]
We have decided to put both glisse and jete examples on page 19 (all across frame notation) and cloche on page 20 with an explanation about options for in-frame and across-frame.
Cloche: Andante 4/4, Arms 2nd. R derriere. Cloche devant knee height, derriere knee height, devant hip height, derriere hip height.

**Comment by rsryman** [comment]
I checked the CBMN notes and could not find a use of "across frame movement lines." 

I found  "between frame movement lines" used in 2 files:
BMN4BalletTeachers_contents.pdf
RB4BT_LessonPlans_all_US.pdf

I really like the phrase "across-frame" but I suppose we should go with the BI standard, but hyphenated:  "between-frame movement lines"

**Comment by rsryman** [comment]
Robyn said: We have decided to put both glisse and jete examples on page 19 (all across frame notation). Don't we need an explanatory note about jete being high enough for in-frame option as well, because the text at the top of the page specifically says "When the movement line is too small"?
**Agreed. Please add to bottom of p. 19: "When the foot brushes to about knee height, it is also possible to use an in-frame movement line, as illustrated/shown [your choice/whichever fits] on the next page."**
Page 20 en cloche with an explanation about options for in-frame and across-frame.
Cloche: Andante 4/4, Arms 2nd. R derriere. Cloche devant knee height, derriere knee height, devant hip height, derriere hip height.
**Suggested text: Both in-frame and between-frame movement lines may be used to show the foot brushing to about knee height or higher, as illustrated below for battement en cloche to 45 and 90 degrees:** 

Animation to be uploaded to BB7MvtLines folder asap

**Comment by rsryman** [comment]
See animation to uploaded to BB7MvtLines folder: BB7BattementClocheBK.mov

Note that the foot starts dégagé derrière opposite 1st (not 5th). It took some fiddling to get the body to sway forward/back but not sideways, and to make leg visible devant and appear the right height derrière. FIne-turning needed?

**Comment by rryman** [comment]
I don't think it needs any fine-tuning ... though it would be interesting to see Jenna "fine-turning" :)
I think you have managed a very realistic rendition.

**Comment by rryman** [comment]
Rhonda, for page 19 you told me to notate the battement jete at knee height (i.e., notation signs centred on the knee line). Please look at your animation: BB7BattementJeté5thBK.mov. Jenna's foot looks quite a bit lower than knee height. With the notation beside the animation, it looks like I have notated it incorrectly. Either you will have to raise the height of the leg in the animation, or I will have to lower the signs in the notation. Please advise.

**Comment by rsryman** [comment]
We're just heading out. I'll look at this first thing tomorrow. 

Is there enough white space below the starting dégagé back?

**Comment by rryman** [comment]
There is enough white space under the en cloche animation - but only because I can leave it quite big as it is the only animation on this page.
There is not enough white space for the other animations in BB7 which have feet dégagé derriere.
In some cases the playback bar disappears in time.
I knew there was a reason I couldn't make these animations this small. Damn!
What should we do about this? It will be a bugger to change all the formatting again, but I guess I'll have to if there is not another solution.

I am done for the day! I will upload the latest version of the book to Dropbox.

**Comment by rsryman** [comment]
Let me see if I can adjust the BB7 animations with dégagé derrière. First I'll try to zoom out a bit and upload a sample; if that doesn't work I'll increase the altitude a bit.

See animation with foot adjusted cf battement en cloche to knee ht, uploaded to BB7MvtLines:

BB7BattementJetéKneeHtBK.mov

**Comment by rryman** [comment]
Thanks. I have input BB7BattementJetéKneeHtBK.mov.

**Comment by rsryman** [comment]
Robyn, re p. 19, I think the bottom sentence should read: "When the foot brushes front or back at about knee height, it is also possible to use an in-frame movement line, as illustrated on the next page." Is there room to offset this sentence by adding even a small space above it? If not, could we add an asterisk after the words "front" and "back" in the bottom caption, and precede the bottom sentence with an asterisk?
I looked through BB7 to flag pages that contain animations where the foot brushing derrière hits the playback bar. The worst is p. 17, bottom animation, but it's not really bad. On pp. 18-19 the bar disappears before the foot brushes derrière. Can we trust that this happens on all iPads? My sense would be to put revising these animations on a TODO list if any of the readers find them a problem.

**Comment by rsryman** [comment]
I just went into Github to read Issue 41 and see that I SHOULD be reading
the post every time I get a notification.

**Comment by rryman** [comment]
In that case, you may want to go into all the closed issues and just skim
through my comments on the very last post.

**Comment by rsryman** [comment]
Done. I think we're caught up on the closed issues.
