### ISSUE TITLE
BB7 - Foot Contacting Leg Page 16 (as of 2015/12/15)

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#42]
I had to change the format of this page quite a bit from the Word docx mock-up you did. Is this page okay?
![footcontactlegp16](https://cloud.githubusercontent.com/assets/15850667/11821587/52e6aa90-a338-11e5-87eb-b59f9154ad53.jpg)

**Comment by rsryman** [comment]
This looks lovely. Nice work! Ready to close item?
