### ISSUE TITLE
Redundancy Avoidance

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#43]
Do you think it is necessary to mention anything about "redundancy avoidance" at the beginning of BB7? We were not very specific about this in Book 2. We only mentioned why things were or were not restated (very subtly) in Reading Sequences page 9 in Book 2.

**Comment by rsryman** [comment]
Did something specific in Book 3 trigger this thought? I'll keep this in mind as I retread BB7.

**Comment by rryman** [comment]
When Arthur was proofreading Book 2 he asked why some signs were repeated and why some were not. It made me realize we hadn't really explained redundancy avoidance, and the exceptions, anywhere. It made me think that maybe newbies to notation might like an explanation rather than just letting them infer it by example. I didn't want to change book 2  at that late stage as Arthur did the very final proof, but It came back to me when I was working on the book yesterday. I know the book is supposed to be a resource for workshops, courses etc., so maybe it isn't necessary?

**Comment by rsryman** [comment]
Yes, hard to justify a new theory entry in the 3rd book. Let's think about how/where to work it in.

Perhaps a mention regarding the supporting foot in centre practice exercises?

**Comment by rryman** [comment]
Maybe on page 21 - the opening page of Simple Centre Practice?
Something like:
When reading sequences you have been applying the principal in BMN called 'redundancy-avoidance'. You will have noticed that only changes in position are recorded because it is unnecessary, and therefore inefficient, to repeat information. The exceptions to the use of redundancy-avoidance are the repetition of information in order to provide a reference to the centre of the frame, the relationship of the arms to each other when only one has moved, and the supporting foot must always be shown when the working leg is recorded.

Then we can go on to say something about centre practice ... quote the Foundations book on page 61 perhaps?
In the initial stages of training, centre practise exercises should be simple and basic, reinforcing stability, balance, and turnout, while introducing basic coordination of the arms and legs.

Go to the next page or tap the following links to go to any section of this chapter:
* List of simple centre practice exercises.

**Comment by rsryman** [comment]
I think it would be better to cover this on p. 10, when  it is first encountered in the context of repeating the supporting foot. Also, there is more room on the p. 10 than on p. 21.  
Perhaps add this para at the bottom left of the page:
"When reading sequences you will remember that only changes in position are notated. It is considered redundant to rewrite a body part that has not moved. In BMN this principle is called **redundancy avoidance**. In the examples above, the arms begin en bas and remain there so they are not rewritten. These examples also illustrate one common exception: on counts 1 and 3, the supporting foot is rewritten to provide a frame of reference for the centre of the notation frame."

**Comment by rryman** [comment]
That works for me. However, it will only fit at Helvetica 15 pt, but I think that is okay as we have other "extra" information formatted that way on other pages.
May I change the last part of the last sentence to:
These examples also illustrate one common exception: on counts 1 and 3, the supporting foot is rewritten to provide a frame of reference **for the working leg**. ?

**Comment by rsryman** [comment]
Yes, I considered whether to make a general statement or refer specifically to this example. I'm OK with your suggestion, but without boldface, yes? If anything should be boldface it should be **frame of reference** OK? And we should make a note somewhere to add this note the first time with use this device for port de bras, e.g., one hand joins the other in high 5th.

**Comment by rryman** [comment]
Bold face was just here so you could see what I wanted to be different in the sentence you had given me.
