### ISSUE TITLE
Simple Centre Work  - Suggested Content

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#45]
Change Title to "Centre Work"
Rhonda to rework wording where necessary - page 2, 5, and 21.

Simple Centre Work
1) Plie - 1st demi and stretch; full and stretch; and in 2nd, tendu close 1st. 
2) Plie - 5th and 4th opposite 5th (left front).
3) Battement Tendu in 8 Body Positions, Italian. (right front)
Page 21 Cecchetti - Nora Roche book revised 1984
Modify one count to open, one count to close.
Lento - metronome.
4) Grand battement and Battement en cloche (high leg) (left in front)
5) Basic Adage - grand plie 5th, developpe devant, rond, into arabesque, attitude, close.
One page with retire, one with movement lines only. (right in front)
6) Basic Pirouette (left in front)

Titles 
Repeated Sequences
Allegro Enchainements

**Comment by rsryman** [comment]
Robyn, please copy the text for pages 2, 5, and 21 into a .doc file for me to edit, thanks.

**Comment by rsryman** [comment]
Thanks!

**Comment by rryman** [comment]
What happened to Rise and Releve?

**Comment by rsryman** [comment]
Oops! Perhaps we should cover this at the end under Pointe Work, which often happens at the end of class? Otherwise, before pirouettes? I can Hangout now if you want to compose this together.

**Comment by rryman** [comment]
Let me know when you want to do a hangout.

**Comment by rsryman** [comment]
I think this is resolved: 

We are adding a rise to the end of each plié example (rise in 2nd; rise in 4th).
The pirouette examples use relevé actions.

To be closed when the content of the above is finalized.
