### ISSUE TITLE
Simple Centre Work - Grand Battement and Battement en Cloche

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#47]
Here's a rough sketch of my suggestion. I wasn't sure how high you want the leg (above the head?).
I am fine if you want to create something different.
![grandbattement](https://cloud.githubusercontent.com/assets/15850667/11873368/1f11b90a-a4a8-11e5-8793-3b1880321862.jpg)

**Comment by rsryman** [comment]
Nice, quite challenging. 

I can animate this at "135 degrees" - foot to just below shoulder height. Let's see how this looks before you start the Illustrator version. The starting/ending head & arms is a bit of a hybrid. See Book 1: RAD effacé devant (p. 78), Cecchetti effacé (p. 88), Russian effacé devant (p. 97). Which should I use? 

It seems closest to Russian, so I could use Anna for this. Rose for my BasicAdage, Maria for Battement Tendu in 8 Body Positions, Italian. OK?

**Comment by rsryman** [comment]
Sample uploaded to Dropbox Ch3 folder: CH3GrandBattement&Cloche.mov 

 This uses Russian effacé devant and 3rd arab. When OK'ed I'll map to Anna (blue). Since the arm starts en haut, I had to adjust. Instead of zooming out, I lowered the dancer a bit. There isn't  enough white space below to clear grey bars so I'll zoom a bit when the animation is refined.

Should we send AR notation and animation (.m4v format) to see if this is too complex/advanced?

v animation?

**Comment by rryman** [comment]
If you want to send it to Anuschka you can, but I don't think you need to if you are okay with the different levels of difficulty of exercises in this chapter. I have taken out the words "simple" and "basic".

Is there any way to lower Jenna's left shoulder, or turn her slightly so she doesn't look like she commences slightly leaning to the right?

Do you want Jenna to take 2 counts for the battement en cloche instead of holding in arabesque? It might make the en cloche a little easier to see?

**Comment by rsryman** [comment]
I'll revise the animation as you suggest.

**Comment by rryman** [comment]
The playback bar disappears before Jenna brushes to the back, so if it is consistent for all iPads then there is enough white space. I will try to keep the animation as big as I can on the page to keep as much white space as possible. It is a bit hard to tell until I do the actual notation via Adobe Illustrator.

I don't quite know what our philosophy should be re the playback bar. Assume it works the same on all iPads? Assume Apple won't change it back to the code where the playback bar stayed all the time? Assume readers can zoom the animation into its own window if the playback bar is an issue? Assume readers will tap as quickly as possible beside the dancer if the playback bar bothers them?

**Comment by rsryman** [comment]
I'm inclined to leave animations as big as possible if the playback bar
disappears in time to keep feet visible, as happens on our machines now,
rather than worry about all possibilities and therefore make the animations
smaller just in case. What do you think?

**Comment by rryman** [comment]
Okay. So let's leave it as is and if our readers complain then we will have to fix it at that point in time.

**Comment by rryman** [comment]
Before I update the notation (and take out the legato line) on Page 25, please look at the placement of "Andante" and let me know if I should shift it and if so, how. Higher than the in front sign, move the whole starting position to the right, leave it as is?

**Comment by rsryman** [comment]
In BB7 you have it flush left with the stave. I like it there. Re height,
you can lift it slightly for clarity, without losing real estate (the arm
starts high), perhaps top aligned with in front sign. I think the whole
starting position is fine, not worth fiddling with spacing.
