### ISSUE TITLE
SimpleCentreWork-BasicAdage

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#48]
See attached draft notation: top version broken down, bottom version using summary movement lines. 

Robyn to see if this notation works. Rhonda to animate it. When draft notation and animation are agreed on, Robyn to create notation in Illustrator.

![basicadage](https://cloud.githubusercontent.com/assets/15932418/11873868/ab16e5a4-a4aa-11e5-9fd3-bcbf2782e14e.jpeg)

**Comment by rryman** [comment]
Works for me! Two things:
1) No straightening of the head needed on Bar 2 ct. 2 in the 2nd example.
2) Why the difference in arms at the end for the 1st and 2nd examples. Shouldn't we keep them the same?

**Comment by rsryman** [comment]
They should be the same:
1) I should have restated the erect head in the top example Bar 2 ct 2 (to
keep the head erect until retiré/arms 1st ): it doesn't start to turn until
the leg&arms open, yes?
2)  I should have restated the left hand in the top example Bar 4 ct 3 (to
retain 2nd until dégagé derrière): it doesn't start to lower until the
right arm hits 2nd, yes?

**Comment by rsryman** [comment]
The legato line blends everything.

**Comment by rryman** [comment]
Rhonda, do you think we can make the notation relatively small and fit both onto one page as per this mock-up, or do you want them on two pages?
![basicadage](https://cloud.githubusercontent.com/assets/15850667/11877176/a5fb0292-a4bb-11e5-9570-bdb36de2e45b.jpg)

**Comment by rsryman** [comment]
A very efficient layout. I think the notation should be clear enough, and
each version can be zoomed into its own window if needed.

**Comment by rsryman** [comment]
I see that you wanted to discuss restating head or hand, by Hangout.

**Comment by rryman** [comment]
Rhonda please check if I understood our Google Hangout discussion correctly:

Robyn to change - Top Example
1) Bar 2 count 2 - added head erect
2) Bar 4 count 3 - add left hand level
Bottom Example
1) Leave all notation as it is

**Comment by rsryman** [comment]
Sorry, I thought I had sent this revised version yesterday.

**Comment by rryman** [comment]
Yep, sorry about that. I see your updated attachment. I will create the notation in Adobe Illustrator.
