### ISSUE TITLE
Change Centre Practice to Centre Work - Pages 2, 5, and 21

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#49]
Rhonda to rework wording where necessary - page 2, 5, and 21.
Robyn changed title of Book (see "Book Cover" issue)

**Comment by rryman** [comment]
[Book3Page2.docx](https://github.com/rryman/BeneshForBalletBook3/files/65585/Book3Page2.docx)
[Book3Page5.docx](https://github.com/rryman/BeneshForBalletBook3/files/65586/Book3Page5.docx)
[Boo3Page21.docx](https://github.com/rryman/BeneshForBalletBook3/files/65595/Boo3Page21.docx)

**Comment by rsryman** [comment]
Suggested revisions in red. We will no doubt fine tune this as we go on.
[Book3Page2.docx](https://github.com/rryman/BeneshForBalletBook3/files/65669/Book3Page2.docx)
[Book3Page5.docx](https://github.com/rryman/BeneshForBalletBook3/files/65668/Book3Page5.docx)
[Book3Page21.docx](https://github.com/rryman/BeneshForBalletBook3/files/65670/Book3Page21.docx)

**Comment by rryman** [comment]
Do you mind if I refer to "centre work exercises" as simply "centre work"?

**Comment by rsryman** [comment]
OK on both counts here, although there might be places where we need to fully say "centre work exercises."
