### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#5]
Pick an appropriate stave of notation of Centre Practice with Repeats from the book and use it to update the TOC.

**Comment by rsryman** [comment]
Do you want me to pick this stave? I don't think I have the BMN of the repeated sequences, so please send (in iBook format??). 

In the meantime, please check my uploaded animations against your full, revised BMN to confirm I have used the right number of intro bars and the correct type and number of repeats.

I think we did want to use repeats for Ben's Tour Enchaînement: once ending in 5th then repeated on the other side ending in lunge? I'll update the animations asap when I hear from you.

I haven't been able to get to the draft contents outline Issue. Did you assign it to me?

**Comment by rryman** [comment]
The TOC issue was assigned to me. I need to remember to do this as soon as we have created an appropriate stave of notation. Presently I am trying to work my way through the contents outline doc in order to create a skeleton of Book 3 with iBooks Author. I am tracking issues for myself as I go.

You need to start breaking up your issues. Please do not embed so many different issues in one comment. Please open a new issue for each new subject.
