### ISSUE TITLE
Simple Centre Work  - Formatting

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#50]
We need to make a decision on how we are going to handle the Glossary terms for this chapter before we proceed much further. I don't know how to layout these pages. Can we please discuss this before we go any further?

**Comment by rsryman** [comment]
OK, I can Hangout now if you like.

**Comment by rryman** [comment]
Call me when you want to do a hangout.

**Comment by rryman** [comment]
Discussed via Google Hangout
1) Use small font (Helvetica 20pt) for Glossary definitions and spread them (and sound clips) across the top of the page under the title of the enchaînement.
2) Use English, Russian, Italian in the title only if the name is different for each school.
3) Use either Rose, Maria, or Anna so the glossary terms can be for one school.
4) Cross-reference the names in the Glossary to the other terms for the other schools.
5) Don't repeat terms within Book 3, assume readers will go through the book in order. 
6) Use terms and definitions from Book 1 and Book 2 where appropriate (okay to repeat terms across books).
7) Font sizes for titles of enchaînements may have to vary a little depending on the length of the title (or may consider making them all a smaller font to give more real-estate on each page?)
