### ISSUE TITLE
Name Change Suggestion - Simple Centre Work to Centre Work Without Repeats

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#51]
Can we change the title to:
Chapter 3: Centre Work Without Repeats
and 
Chapter 5: Centre Work With Repeats

Do you want to create a Grand Battement and Battement en Cloche example which is simpler? Should all the exercises be of a similar technique level? Or should we make a note somewhere about the examples just demonstrating the BMN theory and not representative of a particular technique level?

**Comment by rsryman** [comment]
I like the fact that the exercises are at different levels of difficulty. 

It should be obvious that a battement to 135 degrees is done by an advanced dancer. Even so, we could add a clarification to one of the intro pages.

Do you want to run this by Anuschka (before you take the time to create the BMN)?

**Comment by rryman** [comment]
I don't think we need run it by Anuschka if you are okay with the different levels of difficulty. I have added the sentence to page 21.
Please close this issue once you have read my comment,
