### ISSUE TITLE
PirouetteExamples

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#52]
Content to be decided. Generic en dehors and en dedans from 5th/2nd/4th?  Or 3 pirouette sequences (Italian, English Russian) as below?

1. Cecchetti/Italian version (preparation with a rise), e.g., Pilkington 1984 p. 23 #1 Pirouette **en dehors from 2nd position** (this is "classic" Cecchetti) We could use Ben.
2. RAD/English **en dehors from 4th and 5th** (preparation with a relevé), something like the following (OR can you find anything similar in the new syllabus books?):
Start en face 5th. Ct 1 tendu to 2nd; ct 2 close 5th fr en plié ct 3-4 relevé in 5th; ct 5-6 relevé devant ct 7-8 pirouette en dehors closing 5th fr; Ct 1 tendu to 2nd; ct 2 close 4th derrière en plié; ct 3-4 relevé in 4th; ct 5-6 double pirouette en dehors, closing 5th bk en plié; ct 7 restretch; ct 8 hold. (In the repeats chapter, we could then repeat o/s.) Arms?? OR just the first phrase of 8 (en dehors from 5th) if we use the next (en dehors and dedans from 4th):
3. Russian tour **en dehors and en dedans from 4th position** (simple sequence based on Vaganova pp. 120-121) gives opportunity to show unique Russian arm preparation with wrists down for en dehors, as "3rd arabesque". Or is this to complex?? Hangout to discussed eventually, no rush.

**Comment by rryman** [comment]
Let's have 3 pirouette pages as we haven't done many examples of turn signs in any of the books yet. It also allows for showing a rise prep in one and a releve prep in another. I will have to find another place to write the instructions and take the "stickies" off the intro pages of each chapter.

Just be careful when you create these exercises that you don't add any new theory. Maybe notate them roughly first, scan, and upload them here?

**Comment by rsryman** [comment]
Can you take the Cecchetti BMN from Pilkington p. 23? Perhaps without the grace notes? We could change the timing of the dégagé and rise to "an, 3, an" and omit the zoning on Bar 2 ct 3. The i-icon info could explain that this simplifed version is based on the "classic" Cecchettti version. If you think it's needed we could use add 2 pop-up to show/explain the original graced frames.

I'll start animating and creating BMN for the other 2.

**Comment by rryman** [comment]
Does this work for you?
![pirouettececchetti](https://cloud.githubusercontent.com/assets/15850667/11913816/e5e7926a-a63e-11e5-9ca8-7f01121532bf.jpg)

**Comment by rsryman** [comment]
I don't think Cecchetti would ever end a pirouette like that.

**Comment by rryman** [comment]
So do you want me to jump it into 4th and just have it closing into 5th on demi-plie with only the closing sign like Linda has it?

**Comment by rsryman** [comment]
Can I get back to you tomorrow on this?

**Comment by rryman** [comment]
No hurry. I am just trying to get my stuff done to the best of my ability so I can work on the RAD Seminar material.

**Comment by rsryman** [comment]
Look at Pilkington's Cecchetti Elem 1991 p. 21, attached.
Can you adapt your BMN for Book 3 like this, but simplified:
1. no ankle flexion ticks, zoning or grace notes
2. use té -- explained in i-icon text and with a pop-up?
3. show a single pirouette in Bar 2 and a spring into 4th (perhaps include
a pop-up with the graced 2-frame ending?)

For the repeated version in a later chapter, we'll add the R foot closing
into 5th, which I understand to be the simplest way to move one foot from
4th to 5th, slight pick up and replace. Also, maybe the flexion ticks?? TO
BE DISCUSSED.

When I do the animation, I'll send it to Sheila Kennedy to confirm the
details.
OK for now?

**Comment by rsryman** [comment]
In today's Hangout we decided to omit the Cecchetti pirouette since it required too many unintroduced signs. Robyn to delete from list on page 21 and to delete page 27.

Re p. 21 list: this means that we have 3 by colored figures: Tendu (Italian/Marie), Pirouette en dehors from 4th and 5th (Rose, English),  Pirouette en dehors and en dedance from 4th (Russian). The rest by Jenna with generic text descriptions. This may not be as easy as we think (e.g., re Grand Battement text).

(I'm closing for today....)

**Comment by rryman** [comment]
Is it the generic animation that is tricky, or the generic text?

**Comment by rsryman** [comment]
So far the text, as I encountered re Grand Battement Item #54.
