### ISSUE TITLE
Book 3 - How This Book is Organized - Page 3 as of 2015/12/19

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#53]
Rhonda, in order to give us more room for other information on the opening page of a each section, I have deleted the instructions and added them to Page 3 instead. Please read the updated text and see if you want me to make any edits, and let me know if you think this is the correct place for this information.
![book3page3](https://cloud.githubusercontent.com/assets/15850667/11914219/0c3c72e2-a648-11e5-8dec-3c8a0b674baf.jpg)

**Comment by rsryman** [comment]
This reads well (although I don't have previous versions to know what has changed or been deleted to make room for para 3). I like the para 3 content and it will free up real estate throughout the book.

Just delete "across schools" in para 2 line 3 as this phrase is repeated several times on the page. 
Also, para 3 line 1 "icons" --> "icon". 
Should we add ", e.g.," before the graphic in para 3 line 4, since it is an example of popup frame graphic?

**Comment by rryman** [comment]
Should we add ", e.g.," before the graphic in para 3 line 4, since it is an example of popup frame graphic?
**If we do that, shouldn't it be also used before the graphic for "1st" as that is also only an example?**

**Comment by rsryman** [comment]
You are right. Are we being too picky? I am assigning this to Arthur to get his input.

**Comment by agryman** [comment]
I think the sentence in para 3 is too long and complex. Break it up into a few short sentences and use e.g. when the icon in specific.

**Comment by agryman** [comment]
Btw you do not have to assign issues to get input. You can simply mention the person you want input from. For example if I want Robyn's input I say, "@rryman, what do you think?"

**Comment by rryman** [comment]
Is this any better? @agryman @rsryman 

By now you should also be familiar with tapping on the Information icon "      " to see descriptions of notated sequences and the Speaker icon  "      "  to hear the pronunciation of French words. The bold face text surrounded by a picture frame, e.g.,  "      "  accesses the definitions of ballet terms and the meanings of French words. The notation surrounded by a picture frame, e.g.,  "      "  provides extra BNM theory explanations.

**Comment by rsryman** [comment]
Good. I was just looking at this page and agree with your revisions.

I tried to find a less formal word than "accesses" and could only think of
"links to," "gives" or perhaps "shows" (synonyms for "provides" used re BMN
theory explanations). Your choice.

**Comment by rryman** [comment]
My concern with this set up is that it doesn't apply "tapping" in all instances. How about?:

By now you should also be familiar with tapping on icons for further information. The Information icon " " gives descriptions of notated sequences. The Speaker icon " " provides the pronunciation of French words. The bold face text surrounded by a picture frame, e.g., " " links to the definitions of ballet terms and the meanings of French words. The notation surrounded by a picture frame, e.g., " " shows extra BNM theory explanations.

**Comment by rsryman** [comment]
I see your point. Your update is very clear.

One edit re sentence 3 (we have a few Italian terms re tempo, etc.):
The bold face text surrounded by a picture frame, e.g., " " links to the
definitions of ballet terms and the *meaning of non-English* words.

**Comment by rryman** [comment]
Okay, it now reads:

By now you should also be familiar with tapping on icons for further **details**.
The Information icon      gives descriptions of notated sequences. The Speaker icon       provides the pronunciation of French words. The bold face text surrounded by a picture frame, e.g.,      links to the definitions of ballet terms and the meaning of non-English words. The notation surrounded by a picture frame, e.g.,         provides  extra BNM theory explanations.

**I changed the first "information" to "details" so there would not be two "information" beside each other. Unfortunately this screwed up the formatting and I had to add a line break after "details" to allow the icon to go after "Information icon".**

**Comment by rsryman** [comment]
I'll check this when I download and synch the next version. In the meantime, I found a typo in the last line: BNM -> BMN

**Comment by rsryman** [comment]
I proofread the bottom para and it reads well. Two points:
Second last line: definitions -> definition (that should not change the line formatting)
Is there an extra space before the word "extra" in the last line?

**Comment by rryman** [comment]
Thanks I have made these changes. I think you can close this issue once you have read this response.
