### ISSUE TITLE
"i" box text - Adage - Page 26 as of 2015/12/20

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#55]
![adagep26](https://cloud.githubusercontent.com/assets/15850667/11920054/cf03aa4e-a732-11e5-9008-eb9d9b772ed1.jpg)

Do we need to keep restating right leg? If so, right leg versus right foot Bar 4 counts 3 and 4?
**I think not. See suggested updates in bold below**
Rose performs this adage according to the English school. 
Music. Largo 4/4 (4 bars) 
Starting Position. Facing downstage left (5), 5th right foot front (arms en bas).
Bar 1.
Counts 1-2: Grand plié (arms **open to** demi-seconde, head inclined and turned right). 
Counts 3-4: Restretch (arms **lower to** bras bas, head erect). 
Bar 2.
Counts 1-4: Right leg développé devant at hip height (arms through 1st to 4th left arm up, head turned right). 
Bar 3.
Counts 1-4: **Grand** rond de jambe en l’air en dehors, making a  ¼-turn clockwise to **face [if this wording is consistent??]** downstage right (6) (arms through 2nd to 2nd arabesque, head erect). 
Bar 4.
Counts 1-2: **Attitude** derrière en croisé (arms to 4th right arm up, head turned left). 
Count 3: **Dégagé** derrière (**right arm opens to** 2nd, head remains turned). 
Count 4: **Close** 5th derrière (arms lower to bras bas, head erect).

**Comment by rsryman** [comment]
See front view animation uploaded to Ch3 folder: CH3AdageFR.mov

I used "Largo" metronome beats (40 beats/minute). When you approve this (timing, leg heights, etc.), I'll do the back view.

**Comment by rryman** [comment]
1) I would say that I have the arms are higher in the notation of demi-seconde than in the animation. However, this is how it was notated in Book 1 and the DanceForms image in Book 1 looks to be as low as it is in the Adage animation. Therefore, I think we should just leave it as it and only change it if anyone comments.
2) I would suggest just a slight pause in tendu derrière so the reader can see the position before Jenna closes. I know the legato line says smoothly, but it would still be nice to see the position.
3) Do you still plan to map this adage onto Rose? 
4) Robyn to change both notation excerpts from "Adagio" to "Largo".

**Comment by rryman** [comment]
I have added Front and Back of Rose doing the Adage on page 26 and I have updated the textbox. There is enough white space and I think the animations are still clear enough to see.
Once you have read this comment, please close the issue unless you have anything further to add.
