### ISSUE TITLE
PliéSequences

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#57]
Sample plié in 5th and 4th uploaded to Dropbox Ch3 folder: CH3Plié5th4thFR.mov

To be discussed before we do any notation. I used the ams and head from the Adage, but we can do whatever port de bras you think would work. Perhaps different for 1st/2nd and 5th/4th?

Is the zoom OK re foot in tendu to 4th? Lots of white space above the dancer's head.

**Comment by rsryman** [comment]
Just one more tweak: I agree with your suggestion that we should end these two pages with a rise on Bar 4 counts 3-4 (Dancers' Counts 7-8) in 2nd/4th, +arms? That covers rise here and relevé with pirouette.

**Comment by rsryman** [comment]
Here is a suggestion for the 2 plié pages (maybe arms end
![pliesequences](https://cloud.githubusercontent.com/assets/15932418/11985581/439e15ca-a994-11e5-9ab6-5949c5c5e2fb.jpeg)
 higher in 4th?).

**Comment by rryman** [comment]
If we do the arms higher at the end in 4th, we can use wrists facing out and avoid the diagonal wrists?

**Comment by rsryman** [comment]
Sure, you want me to raise the arms to open 5th with hands well above head
top, yes?

**Comment by rryman** [comment]
Yes.

**Comment by rsryman** [comment]
Done and uploaded.

**Comment by rryman** [comment]
I have added it to the book.

**Comment by rryman** [comment]
Can we close this?

**Comment by rsryman** [comment]
Yes.
