### ISSUE TITLE
Pirouette,Russian

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#58]
I prepared the attached draft notation based on Vaganova and 2 Kostroviskaya sources. The version in 5th is from Kostrovitskaya, just to suggest timing (which Vaganova doesn't describe).
TO BE DISCUSSED BY HANGOUT before I go on.
![pirouette4thrussian](https://cloud.githubusercontent.com/assets/15932418/11958232/a155efd6-a894-11e5-9bc3-9d1f712d90e1.jpeg)

**Comment by rsryman** [comment]
I will follow up with Ana if Barbara doesn't surface by the new year.

**Comment by rryman** [comment]
Barbara accepted my invitation on LinkedIn. I sent her a message via LinkedIn this morning. I will let you know if I hear from her.

**Comment by rsryman** [comment]
Great news. She may be more able to provide timely feedback.

**Comment by rryman** [comment]
I will email you when/if I hear from Barbara so you can close this issue. Unless you want to keep it open because you are going to send it to Ana?

**Comment by rsryman** [comment]
I have the email ready to send to Ana tomorrow, so let's send it and see if
she responds.

**Comment by rryman** [comment]
Okay.

**Comment by rryman** [comment]
Are you waiting to hear back from Ana before you update the handwritten notation?

**Comment by rsryman** [comment]
Yes, no point in doing even a draft until I know I'm on the right track.

**Comment by rryman** [comment]
Okay. I have put a blue note in the book. Do you want to close this for now?

**Comment by rsryman** [comment]
OK.
