### ISSUE TITLE
OrderOfFootStarting

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#59]
Plie in 1st and 2nd - no foot in front, but should use R foot to change positions?
Plie in 5th and 4th - start left foot in front, use left foot to change positions?
Battement Tendu - start right foot in front as you have it, uses right working leg
Grand Battement - starts left foot in front, uses left working leg
Adage - starts right foot in front, uses right working leg
Pirouette en dehors from 5th, English - start left foot in front, turn to left?
Pirouette en dehors and en dedans from 4th, Russian - start right foot in front, turn right?

**Comment by rryman** [comment]
Okay. Can we close this?

**Comment by rsryman** [comment]
Yes.
