### ISSUE TITLE
Pirouette,English

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#60]
I don't have any RAD syllabus books here. Could you try to find a simple sequence introducing en dehors (didn't we decide to do both 4th and 5th?), or 2 short sequences that we can combine. If you can't find a sample, we can use Jenna as discussed. We decided to start 5th L ft fr and turn to left. Something simple like:

Start 5th L ft fr bras bas (4 bars of 4/4)
From 5th in 2 bars (8 cts): Tendu to 2nd (arms 1st to 2nd) and close 5th devant in demi-plié (arms 3rd, L fr); relevé 5th; relevé devant (arms 1st to 3rd); single pirouette en dehors (arms pirouette position) ending L 5th devant in demi-plié. (or we could close behind and use R leg, turn R from 4th?)
From 4th in 2 bars (8 cts): Tendu to 2nd (arms 1st to 2nd) and close 4th derrière in demi-plié (arms 3rd, L fr); relevé 4th; relevé passé devant (arms 1st to 3rd); single (or perhaps double?) pirouette en dehors (arms pirouette position) ending L 5th derrière in demi-plié. 
Re-stretch and lower arms in silence after music?

**Comment by rsryman** [comment]
In the interests of time, I'll go ahead and animate the following very basic version, based on the Foundations book, p. 73. We can get more complex in Ch 5. My only question is: on ct 3, should we use relevé in 4th/5th versus relevé devant? I'll send the .m4v file to Anuschka for her input.
![ch3pirouette englishbmn](https://cloud.githubusercontent.com/assets/15932418/12065203/e7684aa6-afa0-11e5-9b52-877c3bd89f1a.jpeg)

**Comment by rryman** [comment]
I have added both the scanned notation and the animation to the book.
Yes, I do think it would be helpful to see the releve in 4th/5th to demonstrate different notated positions in releve/demi pointe. However, if you think it is covered elsewhere then I am happy to leave it as is.

**Comment by rsryman** [comment]
We could send the animation to Anuschka and ask her which she prefers. I thought it best to wait until Monday when her holiday is over. Will copy you.

**Comment by rryman** [comment]
I guess the question is whether we are using it to illustrate notation theory, or whether we are showing a more "common" pirouette exercise.

**Comment by rsryman** [comment]
In the best scenario, we'll find find a balletically acceptable
illustration of the theory. I'll tell Anuschka that we'd prefer to use the
relevé in 4th/5th if that works.

**Comment by rryman** [comment]
Excellent plan!

**Comment by rsryman** [comment]
Anuschka confirmed the animation setting and said that a relevé in 4th and 5th is acceptable on Bars 1 and 3, ct 3. 

Revised animation uploaded: 
CH3PirouetteEnDehorsRoseFR.mov
CH3PirouetteEnDehorsRoseBK.mov

**Comment by rryman** [comment]
I have added these two animations to the book and made a note about updating the notation when I create it with MacBenesh. We now need the "i" box text info, glossary entries, and sound clips for this page.
