### ISSUE TITLE
AdageAnimation

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#61]
See 2 animations uploaded to Dropbox Ch3 folder:

CH3AdageRoseFR.mov
CH3AdageRoseBK.mov

**Comment by rsryman** [comment]
Suggestion re para 1 text: Here are two alternate ways to notate this sequence:

iBox text OK, but Rose does this so we can use RAD terms: 
Starting position: arms en bas --> bras bas

BMN: 2 suggestions:
Final closing-in-5th sign does look centred below hands: nudge to left? Both animations.
Bottom animation: In Bar 3 should we combine the movement line for the left hand since the port de bras  is phrased over the whole bar (but leave the head and right hand as is on ct 2)?

**Comment by rryman** [comment]
I will nudge the two final closing sings to the left, but let's clarify Bar 3 so I don't have to change it twice.
Won't bar 3 look odd with just the right hand restated in 2nd without the left hand in 2nd as well?

**Comment by rsryman** [comment]
Yes, theoretically correct but odd, I agree. I'll go with whatever you prefer.

**Comment by rryman** [comment]
I think we should keep it how it is. So I will nudge over the two fifth signs and replace the notation in the book. I think we can close this item when you read this comment.

**Comment by rsryman** [comment]
Done.
