### ISSUE TITLE
PirouetteRussianAnimation

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#62]
See two samples uploaded to DropBox PirouetteToBeDiscussed folder (m4v for smaller size):

CH3Pirouette4th(deddeh)8cts.m4v
CH3Pirouette4th(deddeh)16ct.m4v

We could send these to Barb if we can connect, otherwise Anna, but first should we decide:
1. an 8-ct or 16-ct version?
2. separate en dedans and en dehors - 8 cts each? 
3. start en face or croisé?

**Comment by rsryman** [comment]
I suggest the simple 8ct version starting en face, which I will send to Ana on Jan 1. 
See updated m4v file in Dropbox PirouetteToBeDiscussed folder:
CH3Tour4thR(deddeh)FR.m4v

**Comment by rryman** [comment]
I have added CH3Tour4thR(deddeh)FR.m4v to the book.
1) Have you done something different with her arms in second? The elbows look more dropped/bent or something.
2) It that a common ending to a Russian pirouette, fourth with both knees bent and wrists facing down?

**Comment by rsryman** [comment]
1) Yes, I use the Russian arm positions I worked on with Janet Springer.
I'll send the animation to Ana Jojic on Monday, after her holiday.
2) I animated as described in the Vaganova book. Perhaps Ana will suggest
an alternative ending.

**Comment by rryman** [comment]
Sounds good. Let me know when you hear anything back.

**Comment by rryman** [comment]
I like the 8 count version with both the en dehors and en dedans together.
I think it would be a good idea to start facing the corner, so the readers see a different turn sign.
I also think Anna's arms and the ending won't look as odd, if she is facing the corner.

**Comment by rsryman** [comment]
OK, this does look better and also allowed me to zoom up a bit (the tendu
front doesn't go as "low").

See uploaded file in Ch3 folder:
CH3Pirouette4thR(deddeh)+FR.m4v

I'll send Ana Jojic 2 versions of this animation -- starting en face (as
described in Vaganova) and starting croisé -- and ask her if it would be OK
to do the sequence starting croisé.

**Comment by rryman** [comment]
I have put the new one up, but if Ana likes it starting en face you can just upload the file again and I can replace the one I have just added to the book.

**Comment by rsryman** [comment]
OK, I like how you are mocking up pages with notes in blue so we know what
is to be done.

For Ch3 and BB8, I've been uploading the smaller .m4v files "ToBeDIscussed"
until we finalize what we want, then I'll upload .mov files (the format
still recommended for iBook Author?), front and back views.

**Comment by rryman** [comment]
Yes, if we can I would like to keep the file format consistent throughout the book. It is probably just my imagination, but I think the .mov files are just a little clearer on the iPad when iBooks Author "optimizes" the movie file. I think with the .m4v files the movie gets compressed twice, but that could possibly be total crap (I really don't know). 

I don't know if you can understand the following webpage better than I can?
https://support.apple.com/en-us/HT202374

**Comment by rsryman** [comment]
OK, this does look better and also allows me to zoom up a bit (the tendu
front doesn't go as "low"). See uploaded file in Ch3 folder:
CH3Pirouette4thR(deddeh)+FR.m4v

I'll send Ana Jojic the 8-ct animation starting en face (as described in
Vaganova) and the one starting croisé, and ask her if it would be OK to do
the sequence starting croisé.

**Comment by rsryman** [comment]
To address your .m4v versus .mov point, I uploaded .m4v files to our
Dropbox last week because I was trying not to overload it when you were
busy with company.

Many of the long animations are very big, e.g., CH3TenduMariaFR30fps+.mov
is 94.9 MB
That's why I put the .m4v files in ToBeDiscussed folders.

However, now that you are back and we are making ongoing decisions, it's
actually easier for me to upload .mov format.

Reading the web site you cited, I think  you are right about double
compression. The .mov is the basic QT file format extension. Perhaps .m4v
is a more universal (third party) format? If so, we are best to use .mov in
iBook Author.

**Comment by rryman** [comment]
Okay. I will try to get into the habit of deleting the .mov files once I have copied them to my computer and added them to the book. However, should I leave them up there if there is ongoing discussion about them?

**Comment by rsryman** [comment]
Better to delete from Dropbox once you have added them to the iBook to save space. I'll have a copy on my computer and we should know what is ongoing via GitHub.

**Comment by rryman** [comment]
Okay I will delete the files once I have added them to the book. I will go back and check if there are others I can now delete.

Can this issue be closed and then reopened when you hear from Ana?

**Comment by rsryman** [comment]
OK, I guess we should only keep open what we can actively work on.

**Comment by rsryman** [comment]
Email reply from Ana Jojic, Jan 10/15:
"Yes ,you can use one in cruise but for en de dans while the body is facing croise the head is facing en face, audience ,and spots there. For en dehors the head is spotting to the corner."

Rhonda to update animation and create draft BMN to send to Barbara Hannan for comments before Robyn creates the BMN in Illustrator.

**Comment by rsryman** [comment]
Ana confirmed that the spotting in the animation I sent her is correct. She said that the placement sur le cou-de-pied is taught first to children but that adults use toe at knee. 

I have updated accordingly and uploaded the animations:
TourRussianFR.mov
TourRussianBK.mov

We are going to have the same problem "matching" the starting images for the animation front versus back views: Anna appears larger from back view at the start (to fit her in frame, I had to zoom out 2 clicks and shift her a bit to the right). Does this look OK?

**Comment by rsryman** [comment]
For your reference, I redid the BMN and uploaded it to Dropbox. We may omit the H3 info in Bar 2, yes?

**Comment by rryman** [comment]
Is the H3 necessary at the end of bar 1? Can we use an end bracket instead?
Can we eliminate the erect head on count 3 and the turn on count 4?
Yes, we can eliminate the H3 info in Bar 2 and therefore let's not say anything about spotting for that turn in the "i" box.

I have added both animations. The sizes look at bit off, but readers are just going to have to get used to this concept. In later books when the dancers really travel there will be major differences, so best to start getting them used to it.
