### ISSUE TITLE
iBoxTextGuidelines

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#64]
1. When the working leg performs the entire sequence, we could add it to the intro sentence 

E.g., Battement Tendu in 8 Directions of the Body: "Maria performs this battement tendu exercise according to the Italian school, using the right leg as working leg." OR "Maria performs this battement tendu exercise according to the Italian school, using the right leg." OR "Maria performs this battement tendu exercise according to the Italian school, using the right working leg." TO BE DECIDED

2. When the working leg changes we need to be specific within the bar-by-bar description, as for example in Pirouette en dehors from 4th and 5th, English.

**Comment by rryman** [comment]
I like this wording best:
"Maria performs this battement tendu exercise according to the Italian school, using the right working leg."

Text updated accordingly for Battement Tendu and Grand Battement.
Adage text left as is.
