### ISSUE TITLE
Between-Frame Movement Lines - page 19 as of January 4th 2016

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#65]
Liz confirmed that these are called "between-frame" movement lines and not "across-frame" movement lines. I did a "find" in the book and came across the following wording. Does **across** need to be changed to **between** in this text?

When the movement line is too small to show the path within one frame, it is drawn **across** frames. Below, you can clearly see the one-frame movement line that shows a foot brushing to side. To show a low brush forward or back, however, the movement line begins in the frame of the start position (not attached), traces the path in space **across** frames, and ends attached to the sign for the end position.

**Comment by rsryman** [comment]
I reread page 19 and think the wording is OK as is. "Between-frame" is a name or label; the concept can be described by synonyms or phrases that clarify the meaning. If it bothers you as is, do you want to replace "across" with "between" twice? I think "across" is clearer.

**Comment by rryman** [comment]
If you are happy to keep "across" in the body of the text then that is good with me.

**Comment by rsryman** [comment]
Fine.
