### ISSUE TITLE
BeneshBasics8 Content and Page Formatting

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#66]
We need to rethink the format of these pages if we want to use iAnalyse files to show repeats.
How do you feel about having two pages for each?

The first page would have: 
1) the explanatory text
2) the notation fully written out
3) the notation with repeat signs
4) the back view of the animation

The second page would have:
1) the iAnalyse file (if I can get iAnalyse to go across the notation twice and I can change the colour of the moving rectangle for the repeats on other side or reverse, etc.)
2) the "i" box with verbal description?

If you think this is a good idea, I will create the notation example for "Repeat the Same Side" (on page 35) and try to create the iAnalyse file with the moving rectangle.

**Comment by rsryman** [comment]
Maybe we should discuss this before you go to a lot of work. Should the rectangle highlight the original notation? The empty frame where the repeated notation applies? Both?

How much time would it take for you to do a mock-up of the iAnalyse for p. 35? We should make sure you have a .mov file (not .m4v) so the work can be used if we decide it's a go.

**Comment by rryman** [comment]
Discussed via phone. We have decided not to use iAnalyse to illustrate repeats as it is clear enough because we are showing the notation fully written out and using the animation to demonstrate the meaning of the repeat signs.

**Comment by rryman** [comment]
Why did you reopen this issue and assign it to me?
See  "Proofreading BeneshBasics8 Ch4 #76"
