### ISSUE TITLE
BeneshBasics8 Repeated Jump Sequences P38 as of 2016/12/04

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#67]
As per our telephone conversation we are going to leave this page in.
I added a sentence to the top:
"In Book 2 you learned how to read jumps. Here is a simple sequence that illustrates the 3 basic types of repeats."
Because these are "old" animations they look like they do not have the wait before the start. They should also all have a red foot.
I copied these animations from the old Book 3 that included repeats.
I can not find the original animation files so I can't tell you the names of the DanceForms files.
At their present size the feet are slightly cut off by the playback bar. I don't want to start fiddling with the format of the page until I have received the updated animations, because for some reason your newer animations seem to allow me to make them smaller and still contain enough white space.

**Comment by rsryman** [comment]
OK, I'll find these and reformat them in the current window size, without the red foot and with a delayed start.

**Comment by rryman** [comment]
As per our phone call:
We are using a burgundy foot in all animations which have beats.

**Comment by rsryman** [comment]
OK.

Just to help me remember, the name of the color in the DanceForms crayon
colors is Maroon.

**Comment by rryman** [comment]
I have put the BB8JumpsSS_BK.mov with the Maroon foot into the book and previewed it. It fits with enough white space below it to not chop off the feet.

**Comment by rsryman** [comment]
Always a complication. The 8-bar phrases fit fine to the new metronome
beats I recorded (with a hesitation), but when the file is 16-bars, the
dancer got just out of synch. I therefore had to add empty frames to the
long one to make it fit.

Please look at the new file in the Dropbox BB8 folder: BB8JumpsALT_BK.mov

If the timing is perceptibly different from the BB8JumpsSS_BK.mov
animation, I can redo it and adjust the BB8JumpsOS_BK.mov animation (not
yet uploaded) to match.

**Comment by rryman** [comment]
You can't watch two videos at the same time, so I don't think it is an issue.

**Comment by rsryman** [comment]
The timing in the 16-bar version looks better to me, but if you don't
perceive a difference I'll go ahead and upload the OS version in the
Dropbox BB8 folder: BB8JumpsOS_BK.mov

**Comment by rryman** [comment]
Yes, I agree that the timing of the 16-bar version is better.
But I thought you were asking if I thought the difference was a problem, and I didn't think it was because you can't watch two videos at once. I didn't realise you wanted me to tell you which I liked best. Sorry.

**Comment by rsryman** [comment]
Two new animations uploaded to BB8 folder: 
BB8JumpsSS_BK.mov
BB8JumpsOS_BK.mov

**Comment by rryman** [comment]
Thanks. I have added them. I will export the book and upload a copy to DropBox.

On this page 38 do we need any word descriptions? Is the animations enough given they have been introduced to this jumping theory in book 2? The only place we could fit them is in an “i” box at the bottom of the page, or something short added to each caption. I'd rather not add anything, unless you think it is important to do so.

**Comment by rsryman** [comment]
Let's leave it for now. If our readers complain, we'll add the i-box text
description.

**Comment by rryman** [comment]
Okay with me.
