### ISSUE TITLE
Chapter 3 - Centre Work Without Repeats

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#68]
Titles suggested by Rhonda:
Plié in 1st and 2nd
Plié in 5th and 4th
Battement Tendu in 8 Directions of the Body, Italian
Grand Battement
Adage
Pirouette en Dehors from 2nd Position, Italian
Pirouette en Dehors from 4th and 5th, English
Tour en Dehors  and en Dedans from 4th Position, Russian

**May I take out "Position" from the Italian and Russian titles to match the English?**

Robyn, please move the current p. 29 to before the current p. 27 to be consistent with the order listed on p. 21.
**May I move the order on page 21 instead? Or did you want this specific order?**

**Comment by rsryman** [comment]
Fine on both of the above.

**Comment by rryman** [comment]
Tour en Dehors and en Dedans from 4th Position, Russian
Shouldn't this be:
**Tour en Dedans and en Dehors from 4th Position, Russian?**

**Comment by rsryman** [comment]
Duh, you are right!

**Comment by rryman** [comment]
Okay. I think I have fixed it in all 3 places.
