### ISSUE TITLE
Animations for Chapter 3 - Centre Work Without Repeats

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#69]
Robyn, we need to replace .m4v files with .mov files for the animations in Ch3. We can do this on a day when we are both at our computers so I can upload to Dropbox and delete as you download to you computer.
**I am at my computer today (January 4th), are you?**

Rhonda to provide back view for all animations in Ch3 (but delay doing the final 3 front&back views until feedback received).

**Comment by rsryman** [comment]
I have uploaded x files to "Ch 3 .mov files" folder:
CH3Plié1st2ndFR.mov
CH3Plié5th4thFR.mov
CH3TenduMariaFRfps.mov
CH3AdageRoseFR.mov
CH3AdageRoseBK.mov
CH3GrandBattement&ClocheFR.mov
CH3GrandBattement&ClocheBK.mov

Rhonda awaiting feedback on all 3 pirouette animations so leave the .m4v animations as is for now.

Rhonda still to create back view for: CH3Plié1st2nd, CH3Plié5th4th, CH3TenduMaria

**Comment by rryman** [comment]
I have added the following .mov to the book:
CH3Plié1st2ndFR.mov
CH3Plié5th4thFR.mov
CH3TenduMariaFRfps.mov

**Comment by rsryman** [comment]
See uploaded file: CH3Plié1st2ndBK.mov

The timing indication for both plié pages is Largo 4/4.

**Comment by rsryman** [comment]
See uploaded file: CH3Plié5th4thBK.mov

**Comment by rryman** [comment]
Thanks. CH3Plié1st2ndBK.mov and CH3Plié5th4thBK.mov has been added to the book with a note about Largo.

I thought I had sent up a note about notating the arms in plie in 1st and 2nd, but I must have forgotten to submit the comment.
Should I notate the demi-seconde lower for the demi than the full (as you seem to have done in your handwritten score)? Should the higher demi-seconde be lower than the height we have in Book 1 for the RAD demi-seconde, or the same height, i.e., just below the waist? I will use the RAD height for 1st, bottom of the in front sign sitting on the waist line, (even though from the back the arms look lower because we can't see the hands).

**Comment by rsryman** [comment]
Sorry, I don't remember the note you are talking about.

I didn't notate the hand height differently by intention. This is basically
a Cecchetti arm usage, but we are using Jenna so performance is "open." Can
you notate the hands at the height you see them in the animation? The
position is basically a code, with the arm line complementing the line of
the legs, depending on the dancer's proportions, yes?

**Comment by rsryman** [comment]
Would it help if the word notes said that the arm "opened outward toward
demi-2nd"?

**Comment by rryman** [comment]
Yes, that would be a good idea. I will make blue notes on page 22 so I remember to notate the first demi-seconde lower than the second one and the arms in first at RAD height.
