### ISSUE TITLE
Add GrandChangementFR.mov + GrandChangementBK.mov to book

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#7]
I have uploaded the 2 updated animations to Dropbox (repeated with burgundy foot).

Please watch and if OK add to book:

https://www.dropbox.com/s/7yd1slb9rb2up9p/GrandChangementFR.mov?dl=0
https://www.dropbox.com/s/i2pp57os8b4xg95/GrandChangementBK.mov?dl=0

**Comment by rryman** [comment]
Rhonda, I am attaching the notation we had for "Grand Changement and Grand Échappé Battu".
The notation only repeats once and Anna repeats 3 times.
Please let me know if you want to change the animation, or you would like me to change the notation.
[p124GrandChangementGrandÉch.pdf](https://github.com/rryman/BeneshForBalletBook3/files/41150/p124GrandChangementGrandEch.pdf)

**Comment by rsryman** [comment]
As we go through the TOC we can decide what type of repeat is most needed here (although probably as in the original iBook 2). Then I'll update the animation as needed.

**Comment by rsryman** [comment]
I have reduced the animation to 2 times not 4 but am fiddling with the ending to try to get Anna to re-stretch on bar 8 ct 1 without looking like she is snapping her knees. Not yet uploaded.

Bad news: when there is an aerial position on the anacrusis, it needs to be restated on the bar before the end repeat sign, with first part of the jump line, then FIN used. Should we talk? I think the really simple basic repeats will be illustrated in the BB and early chapters, so perhaps not too bad to get more complex with Jumps?

**Comment by rsryman** [comment]
Rhonda to update animation to end with a stretch of legs on musical counts 2&3 of the last bar. 
https://www.dropbox.com/s/7yd1slb9rb2up9p/GrandChangementFR.mov?dl=0
https://www.dropbox.com/s/i2pp57os8b4xg95/GrandChangementBK.mov?dl=0

Robyn to update notation, and consider if simple enough to also use part bar repeats. 
Rhonda think this will work: place dotted start-repeat sign after initial demi-plié, place dotted end-repeat sign after Bar 4 ct 1, showing landing in demi-plié (add knee signs*); show 3 empty bars (Bars 5-7), then a 4th "empty" bar with a dotted bar line after "empty" ct 1 (Bar 8 ct 1) and a phrased re-stretch on cts 2-3. 
*FROM MONICA'S BOOK P. 52, I COULD NEVER FIGURE OUT WHETHER THIS IS NECESSARY.
(Is this too many "issues" in one?)

**Comment by rryman** [comment]
I have added the animations and updated 2 versions of the notation. Please check both versions. We can either use both, or decide which one we like best once we have a better idea of the content of the book as it evolves.
[GrandChangementGrandÉch.pdf](https://github.com/rryman/BeneshForBalletBook3/files/43937/GrandChangementGrandEch.pdf)
[GrandChangementGrandÉchPartBar.pdf](https://github.com/rryman/BeneshForBalletBook3/files/43938/GrandChangementGrandEchPartBar.pdf)

**Comment by rryman** [comment]
Your reply did not have too many issues in it, as your comments were all relevant to this issue.

**Comment by rsryman** [comment]
Yes, move final direction sign a bit to the right. Also, can you curve the jump line below the landing in 2nd  so it isn't so close the the level sign for the left foot?

These two examples give an excellent illustration of the two ways to write this enchaînement.

**Comment by rryman** [comment]
Thanks. The notation is updated as per your input.
Can we close this issue for now?

**Comment by rsryman** [comment]
Robyn updated notation.

**Comment by rsryman** [comment]
Done.
