### ISSUE TITLE
Pirouette en Dehors From 2nd Position, Italian

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#70]
Robyn, this info is here for me to keep track of what I'm doing. No need to put this into the iBook until I get and OK on the animation (from Sheila Kennedy). I am consulting 4 sources:

1. Pilkington 1983 p.23 calls it "Pirouette en dehors from 2nd position" (starting with a rise in 5th)
2. Pilkington 1991 p.17 calls it "Grande préparation four pirouette en dehors" (with a relevé in 5th)
3. Sheila Kennedy 2001 p. 86 calls it "Grande préparation four pirouette en dehors" (with a relevé)
4. Hutchinson and Bennett 2007 p. 192 calls it "Pirouette en Dehors sur le Cou-de-pied" (with a relevé)

The Cecchetti Manual describes it on p. 120 or 142 (depending on the edition - both in Toronto).
I based the **i-box text** on Kennedy's wording (let's discuss what to leave in or take out):
Maria performs this sequence according to the Cecchetti school. It is also called Grande préparation pour pirouette en dehors[add footnote mark, to be shown at bottom of page]. 
**Music.** Xxxx 4/4 (x bars)
**Starting Position.** 5th right foot front (5th en bas).
**Pickup to ** Count4-an.[Underlined] Demi-plié 5th position.
**Bar 1.** Count 1.[Underlined] Relevé 5th sur les demi-pointes (arms 5th en avant)
                Count 2.[Underlined] Demi-plié 5th position.
                Count 3.[Underlined] Right foot dégagé to 2nd en demi-plié.
                Count 4.[Underlined] Press up on left foot, right leg dégagé height.
 **Bar 2.** Count 1.[Underlined] Demi-plié in 2nd position (4th en avant, right arm forward)
               Count 2.[Underlined] Un tour en dehors (cw),
                             right foot sur le cou-de-pied devant (arms pirouette position).
                Count 3.[Underlined] Échappé to 4th position right foot derrière 
                            (arms open to a wide 5th en avant/offering; head inclined right).
                Count 4.[Underlined] Hold. 
                             [When repeated, alternating and with double turns: Close right foot 5th derrière.]
[footnote mark] This version is described in *Notes for a Dancer*, p. 192. Cecchetti technique assumes the following: The turn is done with a press up to 1/4-pointe on the supporting foot. A controlled spotting head is understood on the turn. The foot is usually taken to the knee with more than one turn. The échappé is done with a light spring into 4th, alighting through the feet.
[Robyn, in Ch 5 we can show alternating sides and multiple turns: use a higher retiré and double turns in the empty bars.]

**Comment by rsryman** [comment]
Sheila Kennedy approved the long version to be used for Ch5: 4 sets, 2 with single turns at the ankle, two with doubles at the knee. This was correct except for the transitional plié on the "an" (not Ct 4) pick-up count. My error, I had not read Linda's version accurately. 

The animated version for Ch 3 version is without repeats, so correct as is. 
See upload: Ch3PirouetteDehCecc.mov

For p. 29, the BMN should have no bracket for the single turn (Bar 2 count 1 (not counts 1-2); the double turns shown under empty Bars 6 & 8 will have a bracket (turn on counts 1-2).

**Comment by rryman** [comment]
We have agreed not to use this pirouette in Book 3. Rhonda will keep it for a future book.
