### ISSUE TITLE
BeneshBasics8 Alternating Repeats - page 37 as of 2016/01/05

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#71]
In the interest of conserving space, is it possible to only repeat the first bar 3 times? I know it won't make for a very good exercise, but it is still an example of the alternating repeat sign and it would allow me to write out the entire sequence 4 times and still fit it all on the page (I hope).

**Comment by rsryman** [comment]
Will do.

**Comment by rsryman** [comment]
See file uploaded to BB8 .mov files: BB8RepeatsAlternating12cts.mov

**Comment by rryman** [comment]
There was a miscommunication. By repeating 3 times, I meant the original side and then 3 more times, i.e., 16 counts (4 bars). I think 4 bars should fit.

**Comment by rsryman** [comment]
Uploaded BB8RepeatsAlternating4Bars.mov

For the FIN animation BMN, use Andante (seems faster because she is moving on half beats, but same metronome).

**Comment by rryman** [comment]
And Exclusion Brackets - still March?

**Comment by rryman** [comment]
Uploaded BB8RepeatsAlternating4Bars.mov in not in DropBox

Also the files you deleted from "ForRhonda" are still there. Can I go ahead and delete them?

**Comment by rsryman** [comment]
March give a quality rather than a tempo, so it is OK to use. If you'd
rather keep consistent with Andante I'm fine with that.

**Comment by rsryman** [comment]
Try now: BB8RepeatsAlternating4Bars.mov

OK to delete everything in "For Rhonda" *except* always keep the latest
iBook.

**Comment by rryman** [comment]
March is fine. I just didn't want to create the notation and have to change it afterward.

**Comment by rryman** [comment]
Thanks. I have added BB8RepeatsAlternating4Bars.mov to the book.
