### ISSUE TITLE
BeneshBasics8 Exclusion Bracket - page 40 as of 2016/01/05

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#72]
Would it be possible to just repeat this to the other side and not have alternating repeats? It is a matter of having enough space for the notation to be fully written out.

**Comment by rsryman** [comment]
I wondered about that. Will update and upload asap.

**Comment by rsryman** [comment]
Uploaded: BB8ExclusionBracket4BarsBK.mov

**Comment by rryman** [comment]
I have updated the book with this file.
