### ISSUE TITLE
BeneshBasics8 Reverse Repeats

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#73]
Do you think we should introduce Reverse Repeats in BB8? I think it may be mainly used in Barre Work in the RAD Set Exercises and Variations. However, we could do a simple Tendu Exersice with arms in 2nd: Tendu devant, close 5th front, tendu 2nd close 5th back; then reverse it?

**Comment by rsryman** [comment]
Will do, then in BB9 we can show how to specify different arms in the empty
bars?

**Comment by rryman** [comment]
Okay. We could then do a Review Question where a tendu en croix is done to the other side and reverse and ask the reader to match the animations to the correct notation?

**Comment by rryman** [comment]
Do you prefer "Same Side Repeat" or "Repeat Same Side", etc. for the titles?

**Comment by rsryman** [comment]
Looking at the listing on p. 34, there is consistency as is (we can't
rename Repeated Jump Sequence, but it does start on a new line).

Where in the list will you add Reverse: Repeat Reverse OR Reverse Repeat?

I checked the CBMN, but it doesn't name these. The Parker text says
"reverse repeats" (p. 26), etc.

I have a slight preference for Reverse Repeats, so the first three could be
changed in line.

**Comment by rryman** [comment]
I think I will add Reverse Repeats after Alternating Repeats.
I will change the titles for the other repeats accordingly.

**Comment by rsryman** [comment]
Can we give more thought about the sequence to be notated/animated?

You suggested a simple Tendu Exercise with arms in 2nd: Tendu devant, close
5th front, tendu 2nd close 5th back; then reverse it.

This looks to much like en croix. What about tendu front, side, back, then
all reversed? That would just take 6 cts in all.

I'm heading over to Clare's to visit with Lenny, Tommy, Patti and Rachel.
Will continue later today.

**Comment by rryman** [comment]
Okay. Tendu front, side, back, then all reversed.

**Comment by rsryman** [comment]
See file uploaded to BB8 .mov files: BB8RepeatsReverseBK.mov

**Comment by rryman** [comment]
Thanks. I have added BB8RepeatsReverseBK.mov to the book.
