### ISSUE TITLE
Chapter 5 - Battement Tendu

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#75]
How about we modify the Inter Foundation Battement Tendu exercise for the centre to show repeat "en croix"?
[02_tendu_IF_2.pdf](https://github.com/rryman/BeneshForBalletBook3/files/80170/02_tendu_IF_2.pdf)

**Comment by rsryman** [comment]
Yes, I like this, but can we alter it a bit (beyond using both arms, although that may be enough if you like)? What about (Battement Tendu and Battement Jeté en Croix):
Start with intro or omit intro and start arms 2nd.
Dancer's counts 1-4 as is, then:
Dancer's count 5. Battement jeté devant (just off floor)
Dancer's count 6. Close 5th demi-plié (arms en bas)
Dancer's count 7. Restretch (arms en avant)
Dancer's count 8. Hold (arms 2nd)

**Comment by rsryman** [comment]
Just a thought about this sequence. I might be a nice idea to use this to review the movement line theory in one page, with this small refinement **[changes shown in bold]**:

Battement Tendu and Battement Jeté en Croix:
Starting Position: En face, 5th right front (arms 2nd).
Dancer's count 1. Tendu devant
Dancer's count 2. Close 5th front
Dancer's count 3. **Glissé/Degagé devant [use between-frame movement line to foot just off floor]**
Dancer's count 2. **Close 5th front**
Dancer's count 5. Battement jeté devant [use one-frame movement line to foot at knee height]
Dancer's count 6. Close 5th demi-plié (arms en bas)
Dancer's count 7. Restretch (arms en avant)
Dancer's count 8. Hold (arms 2nd)

**Comment by rryman** [comment]
Is this what you want?
[TenduRepeats1.pdf](https://github.com/rryman/BeneshForBalletBook3/files/81838/TenduRepeats1.pdf)
We were going to do Battement Jete/Glisse on the next page of Chapter 5. Did you want me to delete that page?

**Comment by rsryman** [comment]
Beautiful. I'll look at the next page when I download the iBook.

**Comment by rryman** [comment]
Personally I don't think we need another Battement jete/glisse page. I think the Tendu exercise covers all the theory in a compact way.

**Comment by rsryman** [comment]
Good, but let's do a Hangout or phone call to decide on the content of the
rest of Ch 5 before you make any changes.

**Comment by rsryman** [comment]
See file uploaded: Ch5TenduFR.mov

Is the foot high enough in 2nd? Any higher looked too high to me. 
When this is OK'ed I'll start on back views.

**Comment by rryman** [comment]
Yeah, I think we can get away with it at that height.

**Comment by rsryman** [comment]
The updated file with intro is uploaded:  Ch5TenduFR.mov

Comments welcome before I do the back view.

**Comment by rryman** [comment]
Is it possible for Jenna's head not to look "lifted" when it is turned, or is this just a perception caused by the facial structure and shading in DanceForms?

**Comment by rsryman** [comment]
Even if it's shading, I should be able to make it look better. I had used a 2.42 lift in the upper chest as the arms opened to 2nd. That made the head looked a tiny bit raised so i took it out. Also, the arms do not lift overhead and the foot extends forward/down in the window, so I lifted the dancer in the window (to avoid overlapping the grey bar) which make the perspective look "up." Is the revision any better?

See new upload: Ch5TenduFR.mov

**Comment by rryman** [comment]
Good enough. I have added it to the book and will add the back view when you upload it.

**Comment by rsryman** [comment]
See back view uploaded: Ch5TenduBK.mov

I think we agreed to change the name of this, but what? Suggestion: Battement en Croix

We will have a button on p. 24 for Battement Tendu (generic, definition will cross reference Battement Tendu Simple, Russian); for this page (p. 44) we will need 3 "buttons" for new terms: 
Battement Glissé, English
Battement Dégagé, Italian
Battement Tendu Jeté, Russian

**Comment by rryman** [comment]
I have added Ch5TenduBK.mov to the book.
**Please take a look at the .mov file. The arms look very low from the back when they move from bras bas to first into 2nd.**

I have changed the name of this page to Battement en Croix as per your suggestion.
I have add a button on sound icon to p. 24 for Battement Tendu
I have add a button on sound icon to p. 43 for:
Battement Glissé, English
Battement Dégagé, Italian
Battement Tendu Jeté, Russian
However, the names were too long to fit across with the sound icons, so I moved the sound icons up next to the page title.

**Comment by rsryman** [comment]
I have just looked at this page (p. 45) and think the labels look fine. Please keep the definition for Battement Tendu Jeté (Russian) in the Glossary but perhaps the "jeté" label should link to the shorter term: **Battement Jeté** (same format as other, with a space before the final sentence re the Russian term):

![image](https://cloud.githubusercontent.com/assets/15932418/12732727/dd33c40c-c904-11e5-91cd-86e0209da8c1.png)

Also I noticed that the glissé definition says "45°" but please update to "45 degrees" and let's remember to do a global search in the final proofread.

**Comment by rryman** [comment]
I have made the updates. I hope I understood your instructions correctly.

**Comment by rryman** [comment]
You keep ignoring my comment about the animation. Is that because you think it is fine as is?

**Please take a look at the .mov file. The arms look very low from the back when they move from bras bas to first into 2nd.**

**Comment by rsryman** [comment]
I checked this animation and see that I am using the position we defined for Russian 1st/Cecchetti 5th en avant  (back view) in iBook 1. I wonder if it appears lower because I have shifted the figure up to accommodate the tendu back. Is it any better in the uploaded file: Ch5TenduBK.mov ?

**Comment by rryman** [comment]
Thanks. I have added the updated file.

**Comment by rryman** [comment]
Sis, the only iBox text I could find for this is:
Battement Tendu and Battement Jeté en Croix:
Starting Position: En face, 5th right front (arms 2nd).
Dancer's count 1. Tendu devant
Dancer's count 2. Close 5th front
Dancer's count 3. Glissé/Degagé devant [use between-frame movement line to foot just off floor]
Dancer's count 2. Close 5th front
Dancer's count 5. Battement jeté devant [use one-frame movement line to foot at knee height]
Dancer's count 6. Close 5th demi-plié (arms en bas)
Dancer's count 7. Restretch (arms en avant)
Dancer's count 8. Hold (arms 2nd)

Have you modified it for the book somewhere and I missed it?

**Comment by rsryman** [comment]
I think we decided not to use Dancer's Counts unless necessary for a reason. 
Updated i-box info for Battement en Croix:
Jenna performs this battement sequence to the front, side, back and side.
**Music.** Andante 2/4 (2 bars intro + 16 bars)
**Starting Position.** En face, 5th right front (arms en bas).
**Intro Bar 1.** Hold.
**Intro Bar 2.** Arms lift en avant (head inclined left and lowered to face hands), then arms open to 2nd (head slightly turned right).
**Bar 1.** Right foot slides to front, tip of foot on floor: battement tendu devant (head erect).
**Bar 2.** Right foot brushes front just off floor: battement glissé/dégagé devant.
**Bar 3.** Right foot brushes front at 45 degrees/knee height: battement jeté devant, closing 5th demi-plié (arms en bas).
**Bar 4.** Restretch on count 1 (arms lift en avant by count 1 and open to 2nd by count 2).
**Bars 5-16.** Repeat Bars 1-4 en croix:
**Bars 5-8.** Three battements to side, alternating closings derrière, devant, derrière.
**Bars 9-12.** Three battements to back.
**Bars 13-16.** Three battements to side, alternating closings devant, derrière, devant.
[Robyn, I think Jenna will have to do this; we could footnote alternate Russian names for these ??]

**Comment by rryman** [comment]
Thanks I have added this to the book.
**I think it would be helpful to have the names in the iBox, because even I find it confusing to work out which height is associated with each name in each school!**

**Comment by rsryman** [comment]
OK, see updates above.

**Comment by rryman** [comment]
Okay. I have updated the iBox text and uploaded the latest version of the book.
