### ISSUE TITLE
FIN page 40

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#77]
Should the final BMN bar of the top notation be only 3 frames (no need to leave an empty frame)?

**Comment by rryman** [comment]
Indeed! I had missed the "an" sign originally and had that bar as a 4/4. I caught that mistake, but then failed to get rid of the last space! I'll fix it. So necessary to have two sets of eyes for these things!

**Comment by rryman** [comment]
Book updated with correct FIN notation. Please close this issue, unless there is more to edit on this page.
