### ISSUE TITLE
CH 5 Pirouette with Repeats

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#78]
The list on our iBook p. 42 (and Section heading page) shows Simple Pirouette. To be discussed?

I thought we were going to use the Cecchetti Pirouette from p.29, alternating 3 more times, with a changed pirouette on the 3rd and 4th repetitions (double at the knee), adapted from Pilkington 1983 p. 23. 

See uploaded file: Ch5GrandePrepPirouetteDehCecc.mov

Please confirm that the animation illustrates a single turn on ct 1 (bars 2 & 4) and a double turn on cts 1-2 (Bars 6 & 8) clearly enough.

**Comment by rryman** [comment]
We were originally not even going to use the Cecchetti pirouette for Chapter 3 because of the complications in the notation. I put it back in because you thought you could simplify the notation. Did you ever find out from Liz whether the legato overrides the releve? I personally don't remember that theory and I am not sure we should introduce it here.

I think using this pirouette again in Chapter 5 with the additions as you suggest, makes for a complicated repeat example.

**Comment by rsryman** [comment]
I defer to your judgement. Will email Liz ASAP re the legato rise.

**Comment by rryman** [comment]
The decision we made via our phone call was to take out the Cecchetti pirouette in Chapter 3 and not use it in Chapter 5 with repeats. Rhonda will still email Liz about the legato rise as we are both curious about the theory.

**Comment by rsryman** [comment]
THIS CONTENT IS STILL TO BE DETERMINED. 

Depending on what BB8 theory needs to be illustrated, perhaps from RAD set exercises.

**Comment by rryman** [comment]
Pop-up text for different movements in the empty bar - Page 51 Pirouette en Dedans with Fouette, English.
![emptybars](https://cloud.githubusercontent.com/assets/15850667/18035900/463670cc-6d2d-11e6-95eb-91f8bd1fa78c.jpg)

**Comment by rsryman** [comment]
If a movement differs slightly when the notated phrase is repeated, new
movement is written in the appropriate "empty" frame or frames. Here, the
phrase is repeated four times in all, alternating sides: Bar 1 count
3 shows a single pirouette (1-1/4 turn clockwise); Bar 2 count 3 is
understood to be a 1-14 turn counterclockwise; Bar 3 shows a double turn
(2-1/4 turns clockwise) with arms in 5th; Bar 4 count 1 shows the arms
lowering to 1st and count 3 shows a double turn (2-1/4 turns
counterclockwise) with arms in 5th.
