### ISSUE TITLE
Ben's Tour Enchaînement

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#8]
Rhonda you asked the following in the Book Contents Issues and I am moving it to its own issue thread so it doesn't get lost.
You said: "I think we did want to use repeats for Ben's Tour Enchaînement: once ending in 5th then repeated on the other side ending in lunge? I'll update the animations asap when I hear from you."
I am attaching two files.
1) The notation we used in Book 2.
2) The pdf of the original notation you created with MacBenesh.
If you want to use this sequence in Book 3, then we need to use the notation with the repeats.
Let me know if that's what you would like to do.
[p130ÉchappéBattuTour.pdf](https://github.com/rryman/BeneshForBalletBook3/files/41153/p130EchappeBattuTour.pdf)
[725TourEnchaînementBenRM.pdf](https://github.com/rryman/BeneshForBalletBook3/files/41154/725TourEnchainementBenRM.pdf)

**Comment by rsryman** [comment]
We decided to use the repeated version. 
Robyn will update the Illustrator notation. 
Rhonda will update the animations. 
Rhonda will close this item when both tasks are done.

**Comment by rsryman** [comment]
I used the pdf BMN to update Ben's animation. Frontview uploaded:
https://www.dropbox.com/s/hzvp6i3l2tbnadg/TourEncha%C3%AEnementFR.mov?dl=0

When you OK this I'll update the backview and upload.

**Comment by rryman** [comment]
Rhonda updating animation to have Ben do a single tour (with lead arm not opening) and double tour (with lead arm opening).
Robyn to take out aerial 5th in échappés and to use legato for échappé opening but not closing.

**Comment by rsryman** [comment]
I edited as follows: single turn (no lead arm), lead arm opens a bit more on the double tour, and lunge position reached 2 frames sooner. If OK, I'll do backview. See revised file:
https://www.dropbox.com/s/hzvp6i3l2tbnadg/TourEncha%C3%AEnementFR.mov?dl=0

**Comment by rryman** [comment]
Yes, the animation looks okay now. I still can't see much of a difference with the arms, but at least now with a single and then a double tour the intent of the notated arms makes sense.
Interesting how we don't notate the stretch on Bar 7 ct 2 - it is implied in the notation by not including the knees on Bar 7 ct 1. Do you want the notation kept the way it is, or should I add the knees on the landing of the single tour and straighten them on Bar 7 ct 2?

**Comment by rsryman** [comment]
As discussed by phone, keep notation as is.
Robyn to add pop-up to explain the understood re-stretch on Bar 7 ct 1. 
Perhaps add a pop-up that shows a landing in a retained demi-plié on Bar 7 ct 1, with arms lowering en bas on Bar 8 ct 1 (no need to restate legs in plié) then pushing off on ct 2?

**Comment by rryman** [comment]
I have updated the notation. Please see attached PDF.
[ÉchappéBattuTour.pdf](https://github.com/rryman/BeneshForBalletBook3/files/43244/EchappeBattuTour.pdf)

1) Please check the notation very carefully for accuracy and spacing, etc., because I had to do a lot of fiddling, flipping, cutting, and pasting so it needs a fresh eye.

2) I seem to remember the rule is that you don't need a jump line at the end of a repeat (unless there is an aerial position). Does that also apply to the legato line for the arms as well (or do I need to put it in)?

3) You said: "Perhaps add a pop-up that shows a landing in a retained demi-plié on Bar 7 ct 1, with arms lowering en bas on Bar 8 ct 1 (no need to restate legs in plié) then pushing off on ct 2?"
Wouldn't this just be confusing because it isn't what Ben is performing? Isn't it better to have the pop-up show the same notated position and explain that a restretch happens on Bar 7 ct 2 in order to plié again on Bar 8 ct1?

4) I think we should also add a pop-up with an example of the shorter exclusion bracket to show the option used in the RAD Set Exercises and Variations.

**Comment by rsryman** [comment]
Updated back view in Dropbox:
https://www.dropbox.com/s/h0vdnznwad0etqr/TourEncha%C3%AEnementBK.mov?dl=0

1) Spacing looks good. Can you lower "Bars 9-14" to centre in the space? Bar 14 ct 2: can you start the left arms movement line a bit higher to clearly separate it from the attached ending?
2) Yes, jump line not needed in Bar 8, but I'm not sure about the legato line. Simpler to omit it, since the meaning is clear, I think. This example would work for cross-phrased repeats (if we introduce these) since the repeat signs could enclose the phrase: Anacrusis Bar 4 to Bar 7 (then show arms lowering in empty Bar 8). If needed. 
3) OK, keep it simple.
4) Yes, good idea.

**Comment by rryman** [comment]
Does Ben appear smaller than the girls' animations because he jumps higher so you have to zoom out more?

**Comment by rryman** [comment]
Please ignore this following comment if it isn't possible, or you don't wish to fiddle with it.
On Ben's double tour with the leg in retiré devant, is it possible to "cheat" it? Instead of one tour with the feet in 5th and then one with the retiré at knee height, is it possible to have the leg slowly inching up to retiré as he turns? This may not be possible and may look wrong in the animation, but it is more realistic with what a dancer would do. I noticed it in Book 2 in the Review Question as well, but didn't say anything at the time because there was so much else to deal with. Now that we are starting fresh with Book 3, I thought I would mention it just in case it was something that could be finessed.

If this isn't possible, it might be worth considering having Ben bring his leg up to retiré sooner so that it doesn't look so much like a turn in 5th followed by a turn in retiré. I suspect you were doing it this way because of Anuschka's comment about Rose's tour in retiré in Book 1. Rose only brings her leg to a low retiré and only does one turn, so the fix you did worked well. It doesn't work quite so well with Ben's double tour with the retiré under the knee.

**Comment by rryman** [comment]
Rhonda: Can you lower "Bars 9-14" to centre in the space?
Robyn: Not sure what you want here as it is centred vertically in the space it is in.

Legato line at end of repeat: I looked up RAD Set Exercises and Variations and found one example of where the legato line was written in. Once we have agreed on the rest of the notation, I will send the PDF to Liz and about the "correct" theory.

Part-Bar repeats: I thought we had discussed this by phone and didn't think that part-bar repeats made this example any less complicated. However, I am willing to create a part-bar repeat version if you think it is of value to do so.

**Comment by rsryman** [comment]
On my screen the text "Bars 9-14" looks closer to the shoulder line than the waist line. Perhaps this can't be improved.

I just looked at your BMN for the part bar repeat re Grand Changement, so we're covered already. May not be needed so leave for now.

**Comment by rryman** [comment]
I am afraid it is one of those cases where there isn't an even amount of white space around the text, so either it will be a tad too high, or a tad too low. I tried repositioning it closer to the waist line, so hopefully that will be okay.

Did you see my two previous comments about Ben's animations, or did those comments get too buried in the thread? If so, let me know and I will start another issue called Ben's Tour Animations and transfer the comments there.

**Comment by rsryman** [comment]
I did miss the comments but have read them now. An earlier version had the leg coming up to retiré right away. I change it to have Ben push off into 5th then lift the leg. I have uploaded another version called "Test" with him taking longer to lift the leg (clear legs Fr427 + Fr 435: z+17.95). Better? 

If you like this, just rename it "TourEnchaînementFR" and let me know to send the back view.

**Comment by rryman** [comment]
The gradual lift of the leg to retire looks better, but don't you think it still looks like Ben does one turn in 5th before he lifts the leg to retire? If you don't think it matters, I will go ahead and use this version.

**Comment by rsryman** [comment]
It would seem logical that -- since both legs push off equally from 5th -- the legs stretch (passing briefly thru 5th in the air) before the one is lifted to retiré, no? I could try lifting the foot sooner (tweened Fr 421-443 - no hold in retiré?).  

See uploaded "test2." This looks like what the Russians call it: tire-bouchon (corkscrew).

**Comment by rryman** [comment]
Is it possible to keep the corkscrew action, but also have a brief hold in retire so that the retire under the knee is seen (as that is the position that is notated in the air)?

**Comment by rsryman** [comment]
See uploaded "test3" (tweened + adjusted Fr 423-435).

**Comment by rryman** [comment]
Let's send "test 3" to Anuschka and see what she says. It doesn't look like Ben is doing on turn in 5th and then one turn in retire anymore. Keep the other options in case Anuschka doesn't like the corkscrew!

**Comment by rryman** [comment]
Rhonda has sent Anuschka "test 3". I think it still needs reach retire slightly sooner, but we will wait to hear what Anuschka has to say.

**Comment by rryman** [comment]
Let's not close this issue until we hear back from Anuschka.

**Comment by rsryman** [comment]
I have uploaded another Tour attempt. Should we bother AR with this again? See:

BB7: TourEnchaînementFR..mov

When the front view is approved, I'll update the back view (frames 423-443).

**Comment by rryman** [comment]
Rhonda, do you check these movies in QuickTime before you upload them? If so, did this movie play correctly for you? It does not play correctly for me and iBooks Author can not optimize this movie. It appears corrupted.

If you don't check the movies in QuickTime before you send them to me, can you please start doing so to help me out?

**Comment by rsryman** [comment]
Sorry! Here it is again:

Ben jumps, the foot passes through 5th, and hits retiré as Ben faces front
(1st revolution). Soon enough?

**Comment by rryman** [comment]
I think we should leave it as it is now and just wait and see if Anuschka ever gets back to us on it. We can also wait until folks proof-read to see if it bothers them. At least now Ben is not doing a tour in 5th before a tour in retire, and now you can clearly see the leg in retire on the tour.

The ending of the notation still bothers me - I still think we should have knees notated in Bar 7 count 1 and a straightening of the knees in Bar 7 count 2 ... especially after Liz's comment re the Temps Leve allegro: "You'd have to be a technical nerd to try to read a straightening of the knees into the repeat, certainly if that is what I wanted the dancer to do I'd put both the demi-plie on the landing and the straightening on the last beat before the repeat sign." I am not still not really clear on why you don't want me to change it.

**Comment by rsryman** [comment]
Animation of back view uploaded (retiré timing fixed as per front view).
