### ISSUE TITLE
HelpfulHintsReDanceForms

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#80]
If the timing goes askew, check that the Panel pointer is exactly centred, since DanceForms exports at the default frame rate not the Panel setting.

**Comment by rsryman** [comment]
Be sure to add a second t the end so the dancer's final position is retained.

**Comment by rryman** [comment]
I have transferred these comments to:
Repository - BeneshForBalletBook4
Issue #2 - DanceForms Reminders
