### ISSUE TITLE
BeneshBasics8 - Empty Repeats (pages 41 & 42 as of 2016/01/27)

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#84]
I have uploaded the latest version of the book. I created the pages for the Empty Repeats. Is the notation okay? Is the layout okay?

**Comment by rsryman** [comment]
Notation is good. Please update the text on page 42 (battement tendu is an action not a sequence??):

Empty *repeat* signs are also useful when an action, such as battement tendu, is repeated en croix:

**Comment by rryman** [comment]
Text updated. Can this be closed now?
