### ISSUE TITLE
Chapter 5 - GrandBattement

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#85]
TO BE DISCUSSED BEFORE ROBYN IMPLEMENTS THIS.
See files uploaded into Ch5 folder:
CH5GrandBattement&EnvRacFR.mov
Ch5GrandBattementBMN.jpeg

The Ch 5 grand battement sequence can repeat Other Side (see uploaded j.peg top 2 staves). 
The Ch 7 sequence could build from this and illustrate nested repeats by repeating in Reverse (but we would need to discuss how to show the arms; see uploaded j.peg bottom 4 staves).

The 2 new labels & sound clips for this page would be: "Enveloppé" and "Raccourci"

i-box text (I put head after arms since it didn't make sense before; can we discuss using a more descriptive format -- relating to the arms or room rather than just turn/incline -- for head actions at this point? Also, since I use retiré devant/derrière, I could have Rose do this, so we could use RAD terms for arms):

Jenna performs this grand battement sequence that incorporates enveloppé/raccourci closings.
 Music. Andante 2/4 (8 bars)
 Starting Position. Facing downstage right, 5th left foot front (arms en bas). 
Bar 1.
Count 1: Left leg grand battement devant (arms forward, then open right en haut and left 2nd; head medium turn left OR head to audience). 
Count 1-an: Left foot passes through through retiré devant.
Count 2: Close 5th devant. 
Bar 2.
Count 1: Right leg grand battement derrière (left arm en haut, right arm 2nd; head inclined right and turned left OR head looking under downstage arm??). 
Count 1-an: Right foot passes through retiré derrière.
Count 2: Close 5th derrière. 
Count 2-an: Left foot grand battement to 2nd, en face (arms 2nd, head erect).
Bar 3.
Count 1: Close 5th derrière. 
Count 1-an: Right foot grand battement to 2nd.
Count 2: Close 5th derrière. 
Count 2-an: Left foot grand battement to 2nd, en face (arms 2nd, head erect).
Bar 4.
Count 1: Close 5th derrière, facing downstage left (arms en bas). 
Count 2: Hold
Bars 5-8: Repeat Bars 1-4 on the other side.

**Comment by rryman** [comment]
I have added the handwritten notation, the animation, and iBox text.
I found the glossary entries for  "Enveloppé" and "Raccourci" and linked them.
I found the sound clip for "Enveloppé" but not for "Raccourci".

I am fine with Rose doing this so we can use RAD terminology for the arms and directions. I have put a blue note in the book so we know what has to be decided.

Re the suggestion for Chapter 7:

Rhonda: The Ch 7 sequence could build from this and illustrate nested repeats by repeating in Reverse (but we would need to discuss how to show the arms; see uploaded j.peg bottom 4 staves).

Robyn: I suggest we use this for Chapter 6 Benesh Basics 9 Nested Repeats (page 57)?
Ch 7 is already loaded with the jumping examples and is called "Allegro Enchainements" so I don't think it would fit there.
