### ISSUE TITLE
Chapter 5 - Développé

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#86]
TO BE DISCUSSED BEFORE ROBYN IMPLEMENTS THIS.
See files uploaded into Ch5 folder:
CH5DéveloppéFR.mov
Ch5DéveloppéBMN.jpeg

I have done drafts of 2 versions of the BMN (showing foot at knee versus inwardly curved movement lines), which could both appear on the page. This also illustrates the use of forward qualifications on inwardly curved movement lines (2nd version Bar 2 counts 3-4). Explain via a pop-up?

The only new label & sound clip for this page is: "Grand Rond de Jambe en l'Air"

i-box text (as for Grand Battement, I put head after arms since it didn't make sense before; can we discuss using a more descriptive format -- relating to the arms or room rather than just turn/incline -- for head actions at this point? Also, since I use retiré at side of knee and high arms en avant and high front arm in the arabesque, I could have Anna do this, so we could use Russian terms for arms):

Jenna performs this adage that incorporates développé with passé/enveloppé/raccourci actions.
 Music. Largo 4/4 (8 bars)
 Starting Position. Facing downstage left, 5th right foot front (arms en bas). 
Bar 1.
Counts 1-2: Right leg développé devant (arms forward, then open left en haut and right 2nd; head medium turn left OR head to audience). 
Counts 3-4: Right foot passes the knee and unfolds to 1st arabesque (right arm en avant, left en arrière).
Bar 2.
Counts 1-2: Right leg moves to 2nd en l'air,* en face (arms 2nd). 
Counts 3-4: Right foot passes the knee and closes 5th derrière, facing downstage right (arms move en avant then lower en bas). 
Bars 3-8: Repeat Bars 1-4 three more times, on alternate sides.
*In the English school, this action is called demi-grand rond de jambe en l'air en dedans.

If we decide to use this, I will need to do a generic glossary entry for grand rond de jambe en l'air.

**Comment by rryman** [comment]
I have added the animation, notation, and iBox text to the book.
If we are doing both versions of the notation here, should we do both versions for the Grand Battement page as well?
If the retire goes through the side of the leg instead of devant, should we use either Maria or Anna - or make a pop-up saying that RAD would go through retire devant if we use Jenna?

**Comment by rsryman** [comment]
If there is room we could add both notation versions, as for Développé.

When Ch 5 is mocked up, we can decide which dancers to use, e.g., Rose for
Grand Battement and Maria for Développé, and add a note at the end or a
pop-up to explain the alternative placement.

In any case we could include a note in the i-box text explaining that the
shortform (inwardly curved movement line) is interpreted according to the
conventions of each school re passing the knee at front/side/back.

**Comment by rryman** [comment]
I think there will be room for both in Grand battement if I left align the notation and right align the animations. See Adage page 26.

I have made a blue note in the book about iBox text.

**Comment by rsryman** [comment]
RR TO DO updated animations using Jenna, sound clip & also:
**ROBYN PLEASE ADVISE OR SHOULD WE DISCUSS THIS:**
generic glossary entry for demi-grand rond de jambe en l'air (since Ana confirmed that the Russians use this although I couldn't find it in Vaganova) versus entry for demi-grand rond de jambe en l'air en dedans? (We could shorten the label??) 

Updated i-box text:
Jenna performs this adage that incorporates développé, demi-grand rond de jambe en l'air en dedans, and passé/enveloppé/raccourci actions.
** Music.** Largo 4/4 (8 bars)
** Starting Position.** Facing downstage left, 5th right foot front (arms en bas). 
**Bar 1.**
Counts 1-2. Right leg développé devant (arms forward, then open left en haut and right 2nd; head medium turn left OR head to audience). 
Counts 3-4. Right foot passes the knee and unfolds to 1st arabesque (right arm en avant, left en arrière).
**Bar 2.**
Counts 1-2. Right leg moves to 2nd en l'air, en face (arms 2nd). 
Counts 3-4. Right foot passes the knee and closes 5th derrière, facing downstage right (arms move en avant then lower en bas). 
**Bars 3-8.** Repeat Bars 1-4 three more times, on alternate sides.

**Comment by rsryman** [comment]
We decided to have Maria do this, and Anna do the Relevé if Ana Jojic approves it. Norma Sue has given feedback on the Développé front view which I have revised and sent her for comments. If I don't hear back within 2 days I'll assume all is good and will do a back view & a revised notation draft, then upload all.

**Comment by rryman** [comment]
Sounds like a plan!

**Comment by rsryman** [comment]
See uploaded animation files and updated BMN file:
Ch5DéveloppéMariaBMN.pdf
CH5DéveloppéMariaFR.mov
CH5DéveloppéMariaBK.mov
 
Updated i-box text:

Maria performs this adage that incorporates développé, demi-grand rond de jambe en l'air en dedans, and raccourci actions, described below according to the Italian school.
**Music.** Largo 4/4 (8 bars)
 **Starting Position.** Facing downstage left (2), 5th right foot front (arms 5th en bas). 
**Bar 1.**
Counts 1-2. Right leg développé devant to croisé devant (arms forward, then open left en haut and right 2nd; head slight incline and medium turn right to audience). 
Counts 3-4. Right foot passes the knee and unfolds to 1st arabesque (right arm en avant, left en arrière).
**Bar 2.**
Counts 1-2. Right leg moves to 2nd en l'air, en face (5) (arms 2nd). 
Counts 3-4. Right foot passes the knee and closes 5th derrière, facing downstage right (1) (arms move through 5th en avant then lower to 5th en bas). 
**Bars 3-8.** Repeat Bars 1-4 three more times, on alternate sides.

UPDATED GLOSSARY ENTRY:
![image](https://cloud.githubusercontent.com/assets/15932418/13264027/53cf37d6-da3a-11e5-9989-e8a1a72a34d5.png)

**Comment by rryman** [comment]
Wow, it is crazy how much Maria travels on this just by closing behind 4 times! The difference between front and back views is quite pronounced!

I just made a couple of edits, so check if they are okay.
Bar 1.
Counts 1-2: **Right leg développé to croisé devant (arms move through 5th en avant then open left en haut and right 2nd; head slight incline and medium turn right).**
Counts 3-4: Right foot passes the knee and unfolds to 1st arabesque (right arm en avant, left en arrière, **head erect**).

**Comment by rryman** [comment]
Re the notation:
Why is there an erect head on Bar 2 Count 3?
I have uploaded the latest version of the book.

**Comment by rsryman** [comment]
RR still to do glossary definition and sound clip for demi-grand rond de jambe en l'air. Please correct me if I'm not remembering, but I thought we had decided to omit "en dedans" in the title to shorten the label, and use the basic glossary definition that covers dehors/dedans.

Re the BMN, there is an erect head on Bar 2 Count 3 to prevent the head from turning too soon: it stays erect as the foot touches the knee, then begins to turn/incline/lower with the leg and arms. 

We were going to discuss whether to mention "head to audience," but I see you prefer not. Fine. For head don't we say lowered/raised not bent forward/back? Your revisions ar god except 2 suggested revisions in **bold**:

Bar 1.
Counts 1-2: Right leg développé to croisé devant (arms move through 5th en avant then open left en haut and right 2nd; head slight incline left and **lower**, then slight incline and medium turn right).

Bar 2.
Counts 3-4: Right foot passes the knee and closes 5th derrière, facing downstage right (1) (arms move through 5th en avant then lower to 5th en bas, head slight incline**, lower,** and turn right).

**Comment by rsryman** [comment]
See uploaded files for 2 definitions (re pages 26 revised & 48 new) and 1 sound file:

Demi-grandRdJenl'air.m4a
Glossary26&48.docx

**Comment by rryman** [comment]
Please provide text for the Pop-ups on page 48 Developpe, Italian.
1. the use of forward qualifications on inwardly curved movement lines in bottom stave count 8
2. restating the erect head on count 7

**Comment by rsryman** [comment]
1. the use of forward qualifications on inwardly curved movement lines in
bottom stave count 8

An inwardly curved movement is qualified with a short stroke drawn at right
angles to its curve to show that an extremity moves without flexion,
tracing a forward path en route to its end position. Here, the arms pass
through 5th en avant before lowering to 5th en bas. Compare this with the
unqualified movement line for the right leg which lowers with flexion: the
foot passes the knee before closing 5th derrière. (If no movement line is
used, the leg is understood to close the most direct way, that is, through
pointe tendue.) See *Benesh for Ballet Book 2: *Benesh Basics 4 page 13,
Ex. 7.
[ADD LINK to BK2 and also to video of Lesson 4?]


2. restating the erect head on count 7

On Bar 2 count 3, the head is restated to show that it remains erect until
the arms reach 5th en avant and the foot passes the knee. If the head were
not restated here, it would begin to turn into its final position at the
start of the legato line (Bar 2 count 1).
