### ISSUE TITLE
Chapter 5 - Relevé

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#87]
TO BE DISCUSSED BEFORE ROBYN IMPLEMENTS THIS.
Files not yet uploaded into Ch5 folder:
CH5RelevéFR.mov??
Ch5RelevéBMN.jpeg???

I suggest a basic 8-ct phrase: relevé devant, relevé derrière, echappé relevé to 2nd, relevé 5th.
We just need to decide what type of repeats introduced in BB8 still need to be reinforced (See Issue #88 ).
![image](https://cloud.githubusercontent.com/assets/15932418/12817065/0c74cac0-cb1e-11e5-9c20-886da0a71a44.png)

New label & sound clip for this page: "relevé devant" "relevé derrière"
i-box text TO BE UPDATED:
Jenna performs this relevé sequence.
** Music.** ?? 4/4 (4 bars)
** Starting Position.** Facing downstage right, 5th left foot front (arms en bas, head medium turned left/to audience). 
**Bar 1.**
Counts 1-2: Right leg relevé devant (arms lift en avant and right arm opens to 2nd). 
Counts 3-4: Left leg relevé derrière (left arm opens to 2nd, right arm en avant; head slightly turned right).
**Bar 2.**
Counts 1-2: Échappé relevé to 2nd (arms 2nd, head erect; then arms en bas, head medium turned left/to audience). 
Counts 3-4: Relevé in 5th derrière, facing downstage right (arms move en avant then lower en bas). 
**Bars 3-4:** Repeat Bars 1-2 in reverse, but instead of relevé in 5th do demi-détourné to end facing downstage left with right foot 5th devant.

If we decide to use this, I will need to do a glossary entries for relevé devant, relevé derrière.

**Comment by rryman** [comment]
Before we do this example ...
We have not mentioned what the arms do in reverse repeats on page 38.
In your example, what would the arms and head do on the reverse repeat?

**Comment by rryman** [comment]
Monica's book says: Front/back reversal is understood to refer to leg actions only. Accompanying arm and head movements are usually clear in context.
The encyclopedia says: Front / back reversal is understood to refer to leg actions only. Within the context of ballet accompanying arm and body movements are usually clear in context. In other contexts clarification may be required. 
In one of the example they give, the arms and head are the same on the repeat.
http://beneshinstitute.wearepapertree.com/encyclopedia/encyclopedia-glossary/limb-body-movement/ebmn_01_16_repeats/single-repeats-dance-usage.aspx

So in your example, would the arms and head be the same on the repeat?
In your example, wouldn't the right foot be in front after the echappe to second on the reverse and therefore the demi-detourne wouldn't work?

**Comment by rsryman** [comment]
Yes, reverse repeats are problematic. We could discuss this via Hangout
when you have time.

**Comment by rryman** [comment]
Yes, I called you before but your line was busy.

**Comment by rsryman** [comment]
I have uploaded 2 files:
Ch5RelevéBK.mov
Ch5RelevéBMN.jpeg

Please note that the animation has a 1 bar intro which I haven't shown in the BMN. I had to add this in order to show the preparatory demi-plié on Intro ct 4 (using the metronome beats in 4/4 and adding a silence before I just couldn't just show one beat, please add blue note to update BMN, sorry).

If we name this page Relevé with Détourné, we would need a label, glossary entry, and sound clip for Relevé Devant, Relevé Derrière, and Détourné. RAD and Cecchetti use these terms but I couldn't find them in Vaganova. The enchaînement isn't very Cecchetti-like, so we may need to use Jenna if Rose is used too often. OR I could ask Ana Jojic if it would be Russian enough to use, and if so what they would call the relevé actions and the turn.

For now, here is a basic i-box- text TO BE UPDATED:
Jenna performs this pirouette sequence.
** Music.** Allegro 4/4 (1 bar intro + 4 bars)
 **Starting Position.** Facing downstage right, 5th left foot front (arms en bas, head medium turn left/to front). 
**Intro count 4:** Demi-plié
**Bar 1.** Counts 1-2: Spring up sharply onto the right demi-pointe, drawing the left foot to the knee devant (arms en avant, head incline right) [Footnote 1], then spring down into 5th in demi-plié left foot front. 
Counts 3-4: Spring up sharply onto the left demi-pointe, drawing the right foot to the knee derrière (arms en avant wide, palms up; head inclined and turned left) [Footnote 2], then spring down into 5th in demi-plié left foot front.
**Bar 2.** Counts 1-2: Spring up sharply into 2nd position demi-pointes, (arms 2nd, head medium turn left), then spring down into 5th in demi-plié left foot front (arms lower en bas). 
Counts 3-4: Spring up sharply into 5th position demi-pointes, then spring down into 5th in demi-plié.
**Bars 3-4.** Repeat Bars 1-2 on the same side, but omit the relevé in 5th (Bar 2 counts 3-4).
**Bar 4.** Count 3-4: Spring up sharply into 5th position demi-pointes left foot front, swivel 3/4-turn cw on the left foot to end facing downstage left in 5th position demi-pointes with the right foot front (head medium turn right/to front) [Footnote 3], then spring down into 5th in demi-plié.
Count 4: End 5th position left foot devant in demi-plié, facing downstage right (arms en bas, head to front).
Bars 2-4. Repeat 3 more times alternating sides, with double turns in the 3rd and 4th repetitions:
Bar 2. Repeat on the other side (turning ccw).
Bar 3. Repeat on the original side, with a double turn (2-1/4 cw) and arms en haut.
Bar 4. Repeat on the other side, with a double turn (2-1/4 ccw) and arms en haut.

[Footnote 1] In the English and Italian schools, this action is called relevé devant.
[Footnote 2] In the English and Italian schools, this action is called relevé derrière.
[Footnote 3] In the English and Italian schools, this action is called détourné.

**Comment by rryman** [comment]
Sis, I am a bit confused. I thought this was supposed to be using reverse repeats? The notation is reverse repeats, but the animation and iBox text is repeated the same. Please advise.

**Comment by rryman** [comment]
You seem to have also have the pirouette iBox text at at the end. I am altering the iBox text to say what I think it should and when I have uploaded the book you can check it.

**Comment by rsryman** [comment]
Don't be confused - my error. I copied the original bars and neglected to
alter the reverse parts. That's why we need a second set of eyes.

I copied the pirouette stuff as a template but forgot to remove it, sorry.

Also, I just tried to phone you to reply but MY HOME PHONE ISN'T WORKING!!!
And my cell is in the room where Jack is napping.

Will revise the animation and re-upload asap.

**Comment by rsryman** [comment]
I am closing this item and opening a new one under the name:

Chapter 5 - Sissonne Simple

**Comment by rryman** [comment]
Here is the updated notation for page 51. Is it correct?
I will have to remember to change the "i" info box as well.
![ch5relevedevantderriere narrow](https://cloud.githubusercontent.com/assets/15850667/18616853/66436608-7d91-11e6-9272-0071aaf4fd0b.jpg)

**Comment by rryman** [comment]
Opps ... should be consistent and have the direction sign restated.
![ch5relevedevantderriere narrow](https://cloud.githubusercontent.com/assets/15850667/18616922/2aa998fe-7d93-11e6-88aa-886c29f609a0.jpg)
![ch5relevedevantderriereos](https://cloud.githubusercontent.com/assets/15850667/18616923/2cff4b3a-7d93-11e6-82fa-d381c4d68f89.jpg)

**Comment by rryman** [comment]
Head turns away from the audience on the echappe to second on the repeat to the other side. Did you want me to notate it turned to the left on Bar 4 count 1?

**Comment by rryman** [comment]
Head changed.
![ch5relevedevantderriereos](https://cloud.githubusercontent.com/assets/15850667/18617296/3cae3a4e-7d9a-11e6-8b99-412f2d6237df.jpg)

**Comment by rsryman** [comment]
The head written in Bar 4 ct 1 is what an other side repeat would be, no? I
thought you wanted it to turn L (toward the audience, not away).

**Comment by rryman** [comment]
Yep ... another brain freeze ... finding it hard to focus today ... I'll
change it.

**Comment by rryman** [comment]
If this notation is correct, please create the back views of the two animations for the review and the front view of the animation (reverse) for Page 51.

![ch5relevedevantderriere narrow](https://cloud.githubusercontent.com/assets/15850667/18617850/008ed7d6-7da8-11e6-9510-9d07b1b44ff8.jpg)
![ch5relevedevantderriereos](https://cloud.githubusercontent.com/assets/15850667/18617853/11655aee-7da8-11e6-898e-afd94ddcd1ff.jpg)

**Comment by rsryman** [comment]
I hope I got this right. See 2 uploaded animations:

Ch5RelevéDevantDerrièreBK.mov (for page 51 + to be used in Review 5)
Review5RelDevDerrBKb.mov

Were we also going to use the old one somewhere (reverse other side?)

**Comment by rryman** [comment]
Looks okay to me (but having said that, I don't really trust my brain
today!).
I'll use this back view animation of the reverse on page 51, but I will
also need the front view for page 51.

**Comment by rryman** [comment]
I don't think we are going to use the old one anywhere else.
We have an example with repeats reverse other side in Review 7 with the
glisses.

**Comment by rsryman** [comment]
See uploaded animation: Ch5RelevéDevantDerrièreFR51.mov

Please check it carefully as my brain is mush.

**Comment by rryman** [comment]
Looks good to me. Just a theoretical question.
Should we be consistent with the reverse theory and put in the arms and
head the same on count 1 of the "empty" bars? We don't introduce this
theory until per page 63. I know you made the arms symmetric so it wouldn't
be an issue, but the head isn't symmetric (so I think it is sort of still
an issue).

**Comment by rsryman** [comment]
Since we have said that *reverse* repeats apply to legs only, the default is to assume that the head and arms repeat as written. I'm inclined to leave as is and see what the reviewers say. If you like, we can ask Liz? Perhaps add a pop-up for Bar 1 ct 1 and say: Since *reverse* repeats apply to leg actions only, the head and arms repeat as written. An alternative way to notate *reverse* repeats will be introduced in Chapter 7. (+ link to page, for the keeners?)
