### ISSUE TITLE
Chapter 5 - Content to reinforce BB8 Theory

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#88]
We need to decide what type of repeats introduced in BB8 need to be reinforced in Ch5:

Plié and Tendu: empty
Grand Battement: other side
Développé: alternating
Relevé: reverse (with exclusion bracket and 2nd ending - this simple phrase could be repeated in BB9 to illustrate nested rpt, other side)
Pirouette: alternating (with doubles in empty Bars 3-4)?

**TO BE DISCUSSED NOT YET COVERED IN CH 5:** same side; FIN

Perhaps we should leave in the current p. 46 and show a glissé sequence with accent in that repeats the same, using FIN to eliminate the pickup action?

If we use p. 46 and still want to start with alternate leg, we would need to "mirror" everything I've proposed so far for pp. 47-50. Not a problem at this point, but we should discuss this asap.

**Comment by rryman** [comment]
As discussed via phone. We are going to keep in page 46 and use a glisse sequence using same side and FIN. We will keep the starting legs as is for what Rhonda has already created!

**Comment by rsryman** [comment]
P. 43 text:
In ballet as in any skill practice makes perfect, and careful repetition is key. Today, ballet classes last from one to two hours and often combine set "syllabus" exercises that reinforce physical technique with new arrangements that challenge the dancer's mind. 
[Add a note at the bottom left of the page:]
Giovanni-Léopold Adice, a contemporary of the Italian pedagogue Carlo Blasis, described the gruelling daily class typical of the early 19th century, the era that produced Romantic danseuses such as Marie Taglioni, the first *Sylphide.*  Adice itemized the set exercises done religiously once and sometimes twice a day: each class began with barre work comprising 648 "gymnastic movements" which were then repeated in the centre. This included, for example, 48 pliés and 128 grands battements. Although Taglioni was said to have fainted after such a class, it built the strength and endurance that produced the illusion of defying gravity, a hallmark of Romantic ballet technique. (Hammond in Cohen 1972)
[Add to Sources:]
![image](https://cloud.githubusercontent.com/assets/15932418/12986214/0771d760-d0c4-11e5-87a4-835960c68c40.png)

**Comment by rryman** [comment]
Does this work for you? Sorry, I don't know how to superscript † in GitHub.

Adice* described the gruelling daily class typical of the early 19th century that produced Romantic danseuses such as Taglioni†: each class (sometimes done twice a day) began with barre work comprising 648 "gymnastic movements" which were then repeated in the centre. The barre work included, for example, 48 pliés and 128 grands battements. Although Taglioni was said to have fainted after such a class, it built the strength and endurance that produced the illusion of defying gravity, a hallmark of Romantic ballet technique. (Hammond in Cohen 1972)

*Giovanni-Léopold Adice was a contemporary of the Italian pedagogue Carlo Blasis.
† Marie Taglioni was the first Sylphide.

**Comment by rryman** [comment]
Please translate this into a format you want me to use in "Sources":
"An Account of the Principles of Our Traditions,” G. Léopold Adice, in Dance as a Theater Art: Source readings in dance history from 1581 to the present. Selma Jeanne Cohen, ed., New York: Dodd, Mead & Company, 1974, pp. 71-77.

**Comment by rsryman** [comment]
Adice, G. Léopold. "An Account of the Principles of Our Traditions,” in *Dance as a Theater Art: Source readings in dance history from 1581 to the present.* Ed. Selma Jeanne Cohen. New York: Dodd, Mead & Company, 1974, pp. 71-77.

**Comment by rryman** [comment]
Thanks. Updated as per your suggestions. I am exporting and uploading the book to Dropbox.

**Comment by rsryman** [comment]
Every change ripples. On p. 94, please re-link English Vocabulary, thanks.

**Comment by rryman** [comment]
Actually, the English Vocab should work if you try it as I did re-do all the links on this page.
Unfortunately, the program is buggy and doesn't always underline the link!!!
I'll go back and redo it and hope that it updates correctly this time!

**Comment by rsryman** [comment]
Yes, it does work! I saw that you changed the order so probably redid the
link. Frustrating that the program is not WYSIWYG.

**Comment by rryman** [comment]
Yep ... links are something that I definitely have to recheck on the final proof-read. They are hard enough to keep track of without the "bug" in the code! I can only tell which don't turn up underlined once I see the book on the iPad because they appear underlined when I am in iBooks Author on my Mac - frustrating indeed!
