### ISSUE TITLE
Chapter 5 - Pirouette

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#89]
TO BE DISCUSSED BEFORE ROBYN IMPLEMENTS THIS.
Files not yet uploaded into Ch5 folder:
CH5PirouetteFR.mov??
Ch5PirouetteBMN.jpeg???

I suggest a basic 4-ct phrase for what the RAD calls pirouette en dedans with fouetté (based on *Foundations* p. 74). I plan to use generic Jenna and the i-box text below is worded accordingly. If we use Rose, I will update it based on the wording on p. 74.

We just need to decide what type of repeats introduced in BB8 still need to be reinforced (See Issue #88 ). I suggest we use alternating repeats here, with (single ccw? and) double shown in empty bars.
![image](https://cloud.githubusercontent.com/assets/15932418/12817087/34211984-cb1e-11e5-9e70-164f0d01946c.png)

New label & sound clip for this page: "pirouette en dedans with fouetté, English" ONLY IF NEEDED
i-box text TO BE UPDATED:
Jenna performs this pirouette sequence.
** Music.** ?? 4/4 (4 bars)
** Starting Position.** Facing downstage left, 5th right foot front (arms en bas, head medium turned right/to front). 
**Bar 1.** Count 1: Right foot dégagé front (arms lift en avant then open to 2nd).
Count 2: Shift weight forward into a lunge, front leg in demi-plié (right arm en avant).
Count 2-an: Left leg opens into 2nd just off the floor, right leg in demi-plié 
(right arm opens to 2nd). *[Robyn, if you think we should mention spotting please add: eyes spot to the audience OR spot to 1]*
Count 3: Spring sharply onto the right demi-pointe, drawing the left foot *to the knee*[add asterisk for footnote here] devant (arms join en avant), making 1-1/4 turns en dedans (cw).
Count 4: End 5th position left foot devant in demi-plié, facing downstage right (arms en bas, head to front).
**Bars 2-4.** Repeat 3 more times alternating sides, with double turns in the 3rd and 4th repetitions:
**Bar 2.** Repeat on the other side (turning ccw).
**Bar 3.** Repeat on the original side, with a double turn (2-1/4 cw) and arms en haut.
**Bar 4.** Repeat on the other side, with a double turn (2-1/4 ccw) and arms en haut.

[*Footnote] In the English school, this position is called pirouette position and the turn is called pirouette en dedans with fouetté.

If we decide to use this, I may need to do a glossary entry for pirouette en dedans with fouetté, English.

**Comment by rryman** [comment]
I can't copy this notation. Can you please attach it as a jpeg?

**Comment by rsryman** [comment]
See new files uploaded:
Ch5Pirouette(RAD)BMN.jpeg
CH5PirouetteFR(arms).mov

As I created the animation I had to make adjustments, so I have uploaded a revised BMN, based on the RAD Foundation p. 74. We probably should use Rose for this.

I had to decide about arm transitions between repetitions: I left them in 1st after Bars 1 and 2, but it wasn't clear when the arms lower from 5th to 1st after Bar 3 and if they end in 5th or 1st. 

I have sent this to Anuschka for input.

**Comment by rryman** [comment]
I don't mind the arms, but I will bow to Anuschka's expertise.
I agree that we should use Rose for this.

**Comment by rsryman** [comment]
Robyn, I have updated the front view animation (Dropbox) and i-box text (below) but you can wait until:

**STILL TO DO:** animation back view + glossary entry: pirouette en dedans with fouetté, English (+mention pirouette en dedans without fouetté, English.

Rose performs this pirouette en dedans with fouetté sequence, according to the English school.
 **Music.** Andante 4/4 (4 bars)
** Starting Position.** Facing downstage left (5), 5th right foot front (arms bras bas, head medium turned right to front). 
**Bar 1.** Count 1: Right foot dégagé front (arms lift to 1st then open to 2nd).
Count 2: Shift weight forward into a lunge, front leg in demi-plié (right arm moves forward to 3rd).
Count 2-an: Left leg opens into 2nd just off the floor, right leg in demi-plié 
(right arm opens to 2nd).
Count 3: Spring sharply onto the right demi-pointe, drawing the left foot to the knee devant/pirouette position (arms join in 1st), making 1-1/4 turns en dedans (cw) (eyes spot to the front/audience).
Count 4: End 5th position left foot devant in demi-plié, facing downstage right (6) (head medium turned left to front).
**Bars 2-4.** Repeat 3 more times alternating sides, with double turns in the 3rd and 4th repetitions:
**Bar 2.** Repeat on the other side (turning ccw).
**Bar 3.** Repeat on the original side, with a double turn (2-1/4 cw) and arms 5th.
**Bar 4.** Repeat on the other side, with a double turn (2-1/4 ccw) and arms 5th.

Note: When this turn is initiated by bringing the foot directly into pirouette position without passing through 2nd, it is called pirouette en dedans without fouetté.

**Comment by rryman** [comment]
Thanks. I have implemented these updates to the book.

**Comment by rsryman** [comment]
See back view uploaded to Dropbox: CH5PirouetteRoseBK.mov

Update to i-box text (& addition to BMN):
**In silence.** Re-stretch legs as arms open through 2nd and lower to bras bas.
OR, you can take the wording from the RAD Set Exercises??]

**Comment by rryman** [comment]
I have added the animation and blue notes to the book.
The word notes in the RAD Set Exercises don't have "In silence". They just leave the "count" column empty. I think it is fine how you have worded it.

**Comment by rryman** [comment]
Latest version of Book 3 has been uploaded to DropBox so you can see the updates to Pirouette.
Should I link Pirouette, English and En Dedans (as I have on page 27) because this is in a different chapter?
Should we also have a Glossary entry for fouetté? I couldn't see it in the Glossary doc you sent me.
We have fouette battu (Italian), fouette saute (Italian), and fouette saute en tournant (English) in the Glossary from Book 2, but none of those apply here.
