### ISSUE TITLE
Book Cover

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#9]
Here is the Book 3 cover. It is easy to change the title once we have completed the content of the book and we decide what is most suitable. I used the RAD Set Exercises and Variations spelling for Centre Practice. Do you like the colour of the cover? If not, we can do a Google Hangout and I will share my screen and we can change the colour together. Green reminds me of Spring, and Spring reminds me of new growth, and new growth reminds me of repeating things, and the book is about repeats, so therefore I chose green for the cover. There are lots of other colours and lots of variations on the colour green. I really don't mind what colour we make it, as long as it isn't red or blue, and it doesn't clash on the "book shelf" with the other two covers. See attached JPG:
![book3cover](https://cloud.githubusercontent.com/assets/15850667/11344431/3820c282-91df-11e5-9144-21a6c2c26ad5.jpg)

**Comment by rsryman** [comment]
Yes, let's go with this.

**Comment by rryman** [comment]
Updated cover - title changed to "Centre Work and Repeated Sequences"
![book3cover](https://cloud.githubusercontent.com/assets/15850667/11873817/7aa99768-a4aa-11e5-9724-441e6d0e31e2.jpg)

**Comment by rsryman** [comment]
Yes, I think this better describes what we cover in this book. To be closed for now?
