### ISSUE TITLE
Chapter 5 - Battement Glissé/Dégagé

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#90]
Sample sequence for p. 46 to illustrate same side repeats and FIN:

![image](https://cloud.githubusercontent.com/assets/15932418/12820161/de1867f0-cb2b-11e5-9be3-3583da6f91d3.png)

To make it a bit more interesting, we could add a simple port de bras (en avant, to 2nd, en bas) starting Bar 2 ct 2-an and ending Bar 4 ct 2. When OK'ed I'll do the animation and i-box text.

**Comment by rryman** [comment]
How about not closing into demi-plie in bar 4 so Jenna can finish the sequence with straight legs?
A simple port de bras would be good.
When you redo the notation, can you attach it as a jpeg so I can add it to the book?

**Comment by rryman** [comment]
Discussed via phone. Jenna will end in demi-plie as notated.

**Comment by rsryman** [comment]
See revised notation jpeg and animation back view uploaded:
Ch5GlisséDégagé.jpeg
Ch5GlisséDégagéBK.mov

**Comment by rryman** [comment]
I have added these to the book. Strange how Jenna travels to the left on the glisse/degage.
I have exported and uploaded the latest version of the book.

**Comment by rsryman** [comment]
Yes, it's just by the length of the supporting foot closing in 5th vs 1st. It would be less pronounced if the sequence did an other side repeat. Try it! Of course DanceForms exaggerates for effect. Should I start her a bit to the right to offset the change in location?

**Comment by rryman** [comment]
I think starting her a bit to the right would be a good idea as then she wouldn't finish so far off centre to the left.

**Comment by rsryman** [comment]
Will do. Is there any other refining I should do before I create the front
view?

**Comment by rryman** [comment]
Looks okay to me. Just need to decide who's performing the sequences in Chapter 5 - Jenna, Rose, Maria, or Anna.

**Comment by rsryman** [comment]
OK, so I'll wait until we have a basic mockup of Chapter 5.

I'm just refining the first draft animation for pirouette now; will
probably finish the relevé this afternoon.

**Comment by rryman** [comment]
I uploaded the latest version of the book last night with the mockup of Chapter 5, but I assume you mean you want to wait until I also add the pirouette and releve animations when you have completed them?

**Comment by rsryman** [comment]
Yes, but there is no rush.

I'll wait until you have time to add the pirouette and relevé mockups so we
can discuss refinements before I change the figure colour and do the
remaining front or back view animations for all Ch5.

**Comment by rryman** [comment]
I should be able to add them whenever you upload the two animations. I am just working on the RAD Seminar PowerPoint in the meantime.

**Comment by rryman** [comment]
I can't find the iBox text for the Battement Jete/Glisse. Have I missed it somewhere?

**Comment by rsryman** [comment]
Jenna performs this battement glissé/dégagé sequence to the side, closing 1st or 5th on the beat.
**Music** Andante 2/4 (8 bars)
**Starting Position.** En face, 5th left front (arms en bas).
Pick-up count 2-an. Left foot brushes to side just off the floor.
**Bar 1.** Left foot closes 1st, brushes to side, then closes 5th back: 2 battements left.
Count 2-an. Right foot brushes to side just off the floor.
**Bar 2.** Right foot closes 1st, brushes to side, then closes 5th back in demi-plié: 2 battements right.
Count 2-an. Left foot brushes to side just off the floor (arms begin to lift).
**Bars 3-4.** Four battements alternating feet: left closing 1st, right closing 1st, left closing 1st, right closing 5th behind in demi-plié (arms lift en avant on the first 2 battlements and lower en bas on the next 2).
Count 2-an. Left foot brushes to side just off the floor.
**Bars 5-8.** Repeat Bars 1-4, finishing in 5th right foot behind in demi-plié (omit the final brush to 2nd).
[Robyn, do you think we need to say that the supporting foot re-stretches on ct 2-an in Bars 2&4?. If so:]
Count 2-an. Right leg re-stretches as left foot brushes to side just off the floor (arms begin to lift).

**Comment by rryman** [comment]
I made a few changes just to try to keep some consistency. I hope the following is okay:

Jenna performs this battement glissé/dégagé sequence to the side, closing 1st or 5th on the beat.
Music. Andante 2/4 (8 bars) 
Starting Position. En face, 5th left front (arms en bas). 
Anacrusis. Count 2-an. Left foot brushes to side just off the floor. 
Bar 1. Counts 1-2. Left foot closes 1st, brushes to side, then closes 5th back: two battements left. 		
Count 2-an. Right leg re-stretches as left foot brushes to side just off the floor (arms begin to lift). 
Bar 2. Counts 1-2. Right foot closes 1st, brushes to side, then closes 5th back in demi-plié: two battements right. 
Count 2-an. Left foot brushes to side just off the floor (arms begin to lift). 
Bars 3-4. 	Four battements alternating feet: left closing 1st, right closing 1st, left closing 1st, right closing 5th behind in demi-plié (arms lift en avant to 2nd on the first two battements and lower en bas on the next two). 
Bar 4. Count 2-an. Right leg re-stretches as left foot brushes to side just off the floor. 
Bars 5-8. 	Repeat Bars 1-4 on the same side, finishing in 5th right foot behind in demi-plié (omit the final brush to 2nd).

**Comment by rsryman** [comment]
Yes, this reads well, thanks.
