### ISSUE TITLE
In Silence

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#93]
Rhonda says: "We were considering including an example that show an ending action "in silence," perhaps with a pop-up explaining that this is used throughout RAD set exercises. Or perhaps it is self-evident?"

Robyn says: "If we are going to do this, the examples on page 45 Battement en Croix and page 50 Pirouette en Dedans would work as the arms could lower in silence. However, you would have to redo the animations to have the metronome beat stop and the arms lower in silence."

If we do this, would we then also have to do it for page 68 Jete Battu and Fouette Battu, and page 76 Fouette Saute and Ballotte Saute, to show the leg closing, etc. in silence?

**Comment by rsryman** [comment]
I think giving one example would be enough. Perhaps on p. 50 since this is
an RAD-based one (Rose)? Still awaiting Anuschka's feedback. I'll email her
a reminder at the end of the week.

**Comment by rryman** [comment]
If we only give one example, then won't that be confusing when we don't use it in the other examples that require it?

**Comment by rsryman** [comment]
I'm ok with using it more than once. I don't think of it a something "required" but rather as being shown if there is a specific "choreographed" action in silence, rather than being left up to the dancer.

**Comment by rryman** [comment]
The RAD Set Exercises and Variations seem to use it whenever the exercise doesn't end with the feet together and the arms down. I guess this is "choreographically" what they want the students to do in exams.

Perhaps it would make for less animation "redos" if we just showed it once with a note to say that this practice is used in the RAD Set Exercises and Variations, but that we won't be using it in the remainder of the book because the ending after the music is either not "choreographically" important, or up to the dancer's discretion?

**Comment by rsryman** [comment]
When I redo the p. 50 animations on Rose, I'll remember to add the ending in silence. 

Will resend the message to Anuschka if I haven't heard back by tomorrow.

**Comment by rryman** [comment]
Please provide the wording for the pop-up on page 51 (used to be page 50) to explain the use of "In silence" and why we are not using this convention in the rest of our book.

**Comment by rsryman** [comment]
Suggestions:

A frame or frames may be added after the double bar line to show a set
ending done "In silence," that is, after the music, as in RAD publications.

A frame or frames may be added after the double bar line to show a
choreographed ending done "In silence," that is, after the music. This
practice is used in recent RAD publications.

**Comment by rryman** [comment]
Thanks. I used:
A frame or frames may be added after the double bar line to show a choreographed ending done "In silence," that is, after the music. This practice is used in the published RAD Set Exercises and Variations.
