### ISSUE TITLE
General BMN Theory Questions

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#96]
When we get back to proofreading our reverse repeats theory info, let's discuss the theory point addressed in the uploaded file:

ReverseRepeatTheory.docx

**Comment by rryman** [comment]
I guess the theory point is that you only notate in the empty bars what changes. The direction facing en face doesn't change from the en face direction used in bar 2. Re the arms: once you set up that the arms are to be executed on the other side in the first empty bar, you don't have to notate all the rest of the arms as they are assumed to be to the other side as well.
