### ISSUE TITLE
Chapter 3 Animations to be added

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#97]
I have uploaded 4 BMN clips for pages 22-23 into the For Robyn folder>iBook3 Repeats>Ch3:

Note that these exercises are short. Using the same stave width as Ch 5 notation clips causes bars 1-3 to be on stave 1 and bar 4 to be bumped to stave 2. To fit 4 bars right-left justified on 2 staves, I had to make the stave width narrower than notation clips in Ch 5. I uploaded the narrow and wider versions for your preference.

**Comment by rsryman** [comment]
Another set of files uploaded for page 24 (Ch3BattementTendu8DofB) and 27 (ChPirouetteEnDehors) - (regular and narrow format, your choice) - into the For Robyn folder>iBook3 Repeats>Ch3.

**Comment by rsryman** [comment]
I did my best to update the spotting info re page 28. See uploaded Ch3TourEnDedans.

**Comment by rryman** [comment]
Plie in 1st and 2nd Page 22
I took out the port de bras in counts 1 & 2 in bar 3 to match the animation.
I left in the legato line for smoothness of the demi-plie.

**Comment by rryman** [comment]
Battement Tendu 8 Directions of the Body
Re your MacBenesh file - In the last bar I changed the movement line to come from 5th to second to bras bas.

**Comment by rryman** [comment]
Pirouette En Dehors
Re your MacBenesh file -
I changed the 5th positions on counts 2 & 3 of bar 4.

**Comment by rryman** [comment]
Pirouette En Dedans
Re your MacBenesh file -
I changed the 5th position on count 4 of bar 1 and added wrist directions up.

**Comment by rryman** [comment]
I have uploaded an updated version of Book 3 to the "For Rhonda" folder on DropBox.
I have completed editing your notation for Chapter 3 and updated the wording in the "i" boxes.
I now have to check the glossary definitions once I have the updated book on my iPad.
*Please check the notation and the "i" box information to make sure I have corrected everything*

**Comment by rryman** [comment]
Plie in 5th and 4th Page 23
Re your MacBenesh file -
I changed the first five 5th positions to be on the other foot to match the animation.

**Comment by rryman** [comment]
I think Chapter 3 is now complete, except for the Review Questions.
I have uploaded an updated version of Book 3 to the "For Rhonda" folder on DropBox.
I have completed editing your notation for Chapter 3 and updated the wording in the "i" boxes.
I have checked the glossary content.
*Please proofread the notation, the "i" box information, and the glossary entries to make sure I have corrected everything.*

**Comment by rsryman** [comment]
I have downloaded the iBook and checked your updates to the BMN, thanks. (I did update the MacBenesh files in case we need them.) Will now continue proofreading Chapter 3 "i" box info and glossary entries. Home this morning if you need to check in or talk about the Reviews. Then out to the Apple store to look at iPads and MacBookPros.

**Comment by rryman** [comment]
Is it okay if I work my way through the book editing and adding your MacBenesh files and leave the Reviews until I have completed them all? The Reviews are going to be very challenging because of the restraints of the Review Widget. We are going to have to get creative and I am presently not feeling very creative!

**Comment by rsryman** [comment]
Let's go with what you think best. Maybe we can brainstorm with Anuschka
this Friday.
