### ISSUE TITLE
Ch 3 proofreading text

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#98]
**General**
page 21 line 2: delete "in" (third from last word)

**Glossary text**
page 25 Battement en Cloche glossary: 2nd to last line make Battement Balancé lower case --> battement balancé
page 26 Développé glossary: last para add "school":  *Note: In the Italian school; also, do a global search to see if we use double quotes around "peels off the floor" -- not used in this entry but used in Grand Battement entry)

**i-box text**
1. Do a global search on re-stretch versus restretch. Take out hyphen consistently?
2. re page 24 Bar 1 ct 2: delete semi-colon before end bracket; Bar 8 ct 3 description of arms should be as Bars 1 & 4: "(left arm closing through 2nd to 5th en bas, head erect)"

**Comment by rryman** [comment]
I have made all these changes.
