### ISSUE TITLE
Chapter 5 - Battement Glissé/Dégagé

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#99]
Animation frontview uploaded to For Robyn folder > iBook3 Repeats > Ch5
Ch5GlisséDegagéFR.mov

I compared this to the Ch5GlisséDegagéBK.mov for size, etc., OK?

**Comment by rryman** [comment]
Did you open this file before you put it in DropBox?
It does not open for me, so I can't place it in the book and I can't see the dimensions.

**Comment by rsryman** [comment]
It plays fine for me but it's 50MB -- could that be a problem?

**Comment by rryman** [comment]
I don't think the size should matter. Did you try to play the file you uploaded to DropBox? Open DropBox and try clicking on the file there.

**Comment by rsryman** [comment]
This is what my Dropbox screen looks like. How do I play it here?

**Comment by rryman** [comment]
I can't see what your screen looks like. Did you mean to attach something?

I can only suggest that you try exporting the movie file again and
uploading it to DropBox. I can not open the existing file with QuickTime,
nor paste it into iBooks Author. I get an error message saying it is not a
movie file or that it is corrupted.

---

**Comment by rsryman** [comment]
I just deleted the old file, re-exported from DanceForms and uploaded to
Dropbox. Any success now?

I'll be heading downtown at 11 am to meet Lorie-Gay Galloway at the En
Avant Conference to discuss updates to the CDTA Syllabus.

**Comment by rryman** [comment]
I downloaded the new file you just put in DropBox and I am receiving the same error message (see attached). I have no problem with the other 2 movie files you put in DropBox and they are bigger in size than this one!
![errormessage](https://cloud.githubusercontent.com/assets/15850667/17895248/8152ebd4-691a-11e6-8507-027db6cf9774.jpg)

**Comment by rsryman** [comment]
Can you use this as a place marker and we'll trouble shoot later? Hope this
isn't a problem for the rest of the iBook.

**Comment by rryman** [comment]
I will just leave the space blank. Let me know when you want to try to troubleshoot the problem. I think we had best get it cleared up asap so we know that we can still transfer movie files successfully. Not much point in continuing on with the book if we can't!
